### ISSUE TITLE
with htslib v1.10.1 bcf_index_build() still does not work right

### ISSUE THREAD

**Issue by vanNul** [samtools/htslib#1006]
error:[E::hts_idx_check_range] Region 29449367..4322350815 cannot be stored in a csi index with min_shift = 14, n_lvls = 5. Try using min_shift = 14, n_lvls >= 7
bcf file:
[test.bcf.zip](https://github.com/samtools/htslib/files/3971438/test.bcf.zip)

I do not know if i compile htslib in the wrong way or not, I just compile with command 'make && make install', am i wrong ?

**Comment by pd3** [comment]
The error message is confusing. What happened is that some of the INFO/END coordinates are smaller than POS, which makes the record length negative.

**Comment by vanNul** [comment]
Okay, thank you for your patient debugging, I will check what happened to my bcf creator and feedback soon

**Comment by jmarshall** [comment]
HTSlib 1.10 already has code to detect this problem (via PR #917), though due to other factors it is probably triggered only when indexing .vcf.gz not .bcf and there is room for improvement.

Your patch is probably an improvement, though it now produces BCFs with `rlen` fields that don't match the original VCF POS and INFO/END fields. Shouldn't it have been raised as a pull request so it could be reviewed?

**Comment by pd3** [comment]
Yes, thank you for bringing that up. This is a partial fix only at the level of VCF parsing, also BCF should be checked at either read/write/or both, and in the indexing step as well. This issue remains open and the problem should be addressed properly when there is more time. 

I agree ideally there would be a review first, but things would have to move more swiftly for that. Right now the intention is to minimize the damage caused by releasing a software with known problems. Most people use these "stable" versions and it can take very long time before they update again.

**Comment by vanNul** [comment]
I have review my bcf creator and found that I misusage the END tag for some other meaning instead of the VCF specification, this is my fault, I will go to fix my program now, thank you guys~

**Comment by pd3** [comment]
I'll leave this open as a reminder that probably more checks should be added to other places.

**Comment by vanNul** [comment]
that's a good idea

**Comment by valeriuo** [comment]
This can probably be closed for good.
