### ISSUE TITLE
ssize_t missing definition

### ISSUE THREAD

**Issue by sg-james** [samtools/htslib#1025]
### Background
- Windows 10
- mingw compiled htslib (latest develop)
- msvc 2017 (main program)

### Problem:

My program cannot link / use headers: `bgzf.h` and `kstring.h` since they `ssize_t`, which is not defined for this platform.

### Suggestion:

Could we add a compatibility define somewhere like `hts_defs.h`? e.g.

```cpp
// hts_defs.h

#if defined(_WIN32) && defined(_MSC_VER) && !defined(ssize_t)
#include <BaseTsd.h>
typedef SSIZE_T ssize_t;
#endif
```

### Workaround

I'm currently using this as a work around:
```cpp
// myfile.cpp
#include "aaa_htslib_compat.h" // include before any htslib headers
#include <htslib/bgzf.h"
```
but I have to remember to do this for each and every file that needs compatibility.

Given how close default htslib headers are to "just working", would a PR for something like this be accepted?

**Comment by jkbonfield** [comment]
I don't know when our use of `ssize_t` started, but it predates 2012 when this code was initially checked in to git.  The type is not a formal C99 data type, but comes from POSIX.  Our goal is to support C99/POSIX compliant platforms as far as possible, which (mostly) covers Mingw on windows.  We don't have plans for MSVC compatibiility as it's more work for us and broadly speaking not something we wish to maintain.  My fear and past experience of dealing with MSVC is it's close to "just working" right up until the next thing and the next thing.

Given apparently Microsoft chose to create a `SSIZE_T` instead of a `ssize_t` type, could you not just use the msvc equivalent of `-Dssize_t=SSIZE_T` in CFLAGS?

**Comment by sg-james** [comment]
> or put those into your source prior to inclusion of bgzf.h

Sorry, I didn't fully specify the contents of my `#include "aaa_htslib_compat.h". It is just the additional code block under "Suggestion", which works quite well, but is prone to forgetfulness. 

I was just wondering how much MSVC support / compat would be acceptable, and since I can live without it, I can understand not going down the road to "just working".

Thanks for taking the time to explain

**Comment by jmarshall** [comment]
Harmonising this sort of platform deficiency is the role of _htslib/hts_os.h_, so something like this wouldn't be completely out of place in that header. However the other _htslib/*.h_ headers don't include that one themselves and shouldn't start doing so, so your code would need to `#include <htslib/hts_os.h>` itself before including other HTSlib headers.

Compiling htslib itself using MSVC is another much bigger kettle of fish altogether, but it is true that this `ssize_t` problem is the only issue stopping you from including htslib headers from other code compiled by MSVC.

The problem here is: what if your code also uses some other library that also tries to paper over this `ssize_t` deficiency? The two workarounds will likely clash with each other, especially if they use `typedef` rather than `#define`. Hence it is best for your source code to activate a workaround explicitly itself — either by `#include <htslib/hts_os.h>` if a workaround were added there, or by `#include "aaa_htslib_compat.h"` including your own file, which is effectively very nearly the same thing.
