### ISSUE TITLE
tabix fails to read properly indexed BED file

### ISSUE THREAD

**Issue by PoisonAlien** [samtools/htslib#1085]
Hi,
I have tested this on many bed files and, I cant seem to figure out out the issue is. Tabix for some reason refuses to read the properly formatted tabix indexed BED file.

```bash
$ bgzip samp.bed
$ tabix -p bed samp.bed.gz

$ tabix -H samp.bed.gz
[E::hts_hopen] Failed to open file samp.bed.gz
[E::hts_open_format] Failed to open file "samp.bed.gz" : Exec format error
Could not read samp.bed.gz

$ tabix -l samp.bed.gz #This works
chr21
chr22

$ tabix samp.bed.gz chr21:1000-20000
[E::hts_hopen] Failed to open file samp.bed.gz
[E::hts_open_format] Failed to open file "samp.bed.gz" : Exec format error
Could not read samp.bed.gz


$ tabix
Version: 1.10.1
```

I have also attached a reproducible sample bed file. Thanks.
[samp.bed.gz](https://github.com/samtools/htslib/files/4787116/samp.bed.gz)

**Comment by valeriuo** [comment]
Your BED file doesn't follow the [format](http://genome.ucsc.edu/FAQ/FAQformat#format1). The 4th column should be string label, while the 6th should be a symbol encoding the strand (".", "+", "-").

**Comment by jmarshall** [comment]
Nonetheless you would expect it to work as a generic BED-style file, i.e., what bedtools calls BEDPLUS.

`htsfile` shows us the problem here:

```
$ htsfile samp.bed.gz 
samp.bed.gz:	FASTQ-IDX BGZF-compressed index data
```

So the problem is that this BED file has also happened to match the column-type format for a FASTQ index (`.fqi`) file.

This error message has come from _tabix.c_'s `query_regions()`, caused by `hts_open()` failing to open a file of this type. This is intentional — `hts_open()` was originally for opening SAM/BAM/CRAM/VCF/BCF files, and having it fail to open index files improves the error message reported when users put `foo.bam.bai` on a samtools command line where a BAM file is expected.

This is a similar problem to that considered in https://github.com/samtools/htslib/pull/721#issuecomment-400666150 and the following comments. Unfortunately it is not possible to recode `query_regions()` to use `hopen()`/`hFILE` as `tbx_itr_next` takes a `htsFile`.

Probably the best fix is to add “BED-like” formats like this one to the lists of openable formats in `hts_open()`/`hts_close()` (sigh) and establish the convention in _bgzip.c_, _tabix.c_, and _samtools/*.c_ of checking format categories immediately after `hts_open` so that a more useful error message than ”Can't read header from file” is still produced:

```c
// e.g. in sam_view.c
if (hts_get_format(fp)->category != sequence_data)
    error("expecting a SAM/BAM/CRAM file");
```

Alternatively mode letters or similar could be added to `hts_open()` so the caller could signal their allowable file types. That perhaps could already be possible with `hts_open_format()` if all the pieces were joined together…

**Comment by PoisonAlien** [comment]
Fair enough. Sample file was a BED like (bedgraph) file with metadata. I am not a C expert and, based on above explanation it seems rather complicated to check for discrepancies in file formats. 

For what its worth, it works when I have only 4 columns, or more than 6 columns. If the file contains exactly 5 or 6 columns it seems to expect the file to be in standard BED6 format. 
But again wouldn't something like below should work?

```bash
$ tabix -b 2 -e 3 -s 1 -f samp.bed.gz
$ tabix -H samp.bed.gz
[E::hts_hopen] Failed to open file samp.bed.gz
[E::hts_open_format] Failed to open file "samp.bed.gz" : Exec format error
Could not read samp.bed.gz
```
I am not using any preset so it should avoid expecting BED like input(?).

**Comment by jkbonfield** [comment]
I can understand how this corner case managed to fail filetype auto-detection, but you'd like to think that it could also figure out it's a bed file from the fact it ends in `.bed.gz`.  Maybe we should honour the filename *when known*, even if it's only for formats where it can be questionable to detect them due to ill-defined specifications.

**Comment by jmarshall** [comment]
I see [bedgraph files](https://genome.ucsc.edu/goldenPath/help/bedgraph.html) do indeed have a numeric value in that 4th column, and it can be integer or real.

This format detection is operating at a different level of the code from tabix presets. As you see in this _hts.c_ code https://github.com/samtools/htslib/blob/16f62c5663bc09fda7c87f78322d1c561f483055/hts.c#L461-L475 when you have exactly 5 or 6 columns the file is unluckily recognised as an FAI/FQI index rather than BED because that 4th column matches `i`.

I see some of your 4th column values are real rather than integer. If you make the value on the first line `100.0` so it does not look like an integer, tabix will work as expected on your file.

**Comment by PoisonAlien** [comment]
@jkbonfield Yeah makes sense. I tried to change the file extension from `bed.gz` to `tsv.gz` but tabix was smart enough to tell me that it `Couldn't understand format of samp.tsv.gz`

@jmarshall These kind of BED like files are quite common in WGBS and contains methylation value (0-100 scale) and readcounts supporting methylated and unmethylated reads. If this is an isolated scenario and, not worth spending the time/effort to extend tabix support for BED like files, then please feel free to close the issue.

**Comment by jmarshall** [comment]
It is true that it would be good to recognise these obscure ones only if the filename has `.fai`/`.fqi` in it, and otherwise let them fall through to match the more generic BED. The trouble is this part of the code doesn't know what the filename is. I think I have a branch around here somewhere that refactors that by adding a new `int hts_detect_format2(struct hFILE *fp, const char *fname, htsFormat *fmt)` function…

**Comment by PoisonAlien** [comment]
In my opinion support for generic BED files would drastically improve tabix usage. Especially in scenarios where files are huge - WGBS outputs for instance where these non-standard BED files contain millions of rows (for every CpG in the genome). 
I can see how one can argue that tools like `bedops` or `bedtools` should be of benefit here but, tabix allows faster random access which can not be said for aforementioned tools(?).

**Comment by jmarshall** [comment]
Tabix **does** support generic BED files. This is just a bug for your particular files, which can be worked around in the existing version of tabix by making sure the 4th column on the first line has a `.0` on the end.

**Comment by PoisonAlien** [comment]
Haha.. That was not my intention at all and I apologize if it sounded like one :)
I will proceed with adding a 7th column which seems to do the job. I am closing the issue for now. Thank you all for your time and patience in replying.
