### ISSUE TITLE
cram_to_bam used by other software - please export ("make public")

### ISSUE THREAD

**Issue by smoe** [samtools/htslib#1098]
Hello,

sambamba gave us Debian folks some headache since it produces a link error when built - cram_to_bam is missing (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948919). Guix (overlapping authors with sambamba) took a very pragmatic approach and just [made that part of the API public](http://git.genenetwork.org/guix-bioinformatics/guix-bioinformatics/src/commit/a2a200402b91a352dbdede01eec85accb892b8e1/htslib-add-cram_to_bam.patch):
```
    This patch adds the cram_to_bam function to the public interface of htslib,
    because it is used by code in Sambamba.

    by Roel Janssen <roel@gnu.org>
    --- a/cram/cram_decode.c	2015-12-15 17:34:33.000000000 +0100
    +++ b/cram/cram_decode.c	2016-02-24 11:16:10.491808702 +0100
    @@ -2730,7 +2730,7 @@
      * Returns the used size of the bam record on success
      *         -1 on failure.
      */
    -static int cram_to_bam(SAM_hdr *bfd, cram_fd *fd, cram_slice *s,
    +int cram_to_bam(SAM_hdr *bfd, cram_fd *fd, cram_slice *s,
     		       cram_record *cr, int rec, bam_seq_t **bam) {
         int bam_idx, rg_len;
         char name_a[1024], *name;
    diff -Naur htslib-1.3/cram/cram_decode.h htslib-1.3-patched/cram/cram_decode.h
    --- a/cram/cram_decode.h	2015-12-15 17:34:33.000000000 +0100
    +++ b/cram/cram_decode.h	2016-02-24 11:15:04.556809864 +0100
    @@ -104,6 +104,8 @@
     int cram_decode_slice(cram_fd *fd, cram_container *c, cram_slice *s,
     		      SAM_hdr *hdr);
     
    +int cram_to_bam(SAM_hdr *bfd, cram_fd *fd, cram_slice *s,
    +                cram_record *cr, int rec, bam_seq_t **bam);
     
     #ifdef __cplusplus
     }
```
This looks reasonably harmless such that I would like to add this to the htslib package in Debian, too. There are no objections on your side? If so - would you possibly consider to adopt this for your next release of htslib?

Many thanks and regards,
Steffen

**Comment by valeriuo** [comment]
> Guix (overlapping authors with sambamba) took a very pragmatic approach and just made that part of the API public:

No, it just exposed the method. That part of the API is not public and can be changed without notification. The only public CRAM API is in [htslib/cram.h](https://github.com/samtools/htslib/blob/develop/htslib/cram.h). The fact that third party software (such as sambamba and SeqLib) is using an unofficial API is an implicit contract on its developers' part that they are willing to put in the effort to ensure compatibility and smooth functioning.

It might only be a minor change, but it is also a slippery slope, which would force the maintainers' hand with similar future requests. Please see a detailed discussion [here](https://github.com/samtools/htslib/issues/616).

**Comment by daviesrob** [comment]
See also Debian bug [881170](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=881170)).  It is not possible for us to maintain a stable ABI if distributions are presenting different sets of symbols to upstream, and to each other.

We can look into adding this interface to our official API, although having seen how sambamba links against HTSlib I don't think it will help if you want to use an up-to-date version.  It appears that someone has tried linking sambamba with a modern version already, and run into trouble (biod/sambamba#425).

**Comment by jmarshall** [comment]
See also [this debian-med thread](https://lists.debian.org/debian-med/2020/07/msg00032.html) (that message and its replies). From my requested reply there:

The `cram_to_bam() function` is used in one place in sambamba, in CramSliceReader, which appears to be about reading CRAM files. It would be useful if someone familiar with sambamba could say what this code is all about. Could it be recoded to use `sam_read1()` or iterators, or does it provide access patterns that cannot currently be expressed using the general purpose HTSlib API? [The comment from the sambamba maintainer mentioned by @daviesrob above] suggests that in fact sambamba could be recoded without using this function and so this issue would disappear in due course.

OTOH if there is a problem needing to be solved here, then `cram_get_bam_seq()` (which is a simpler wrapper around `cram_to_bam()`) may be a better candidate for adding to the public API. Would that function suffice for sambamba's needs? At present, htslib/cram.h does not really provide an interface for reading records from CRAM files, so there would be some work for the HTSlib maintainers to do to decide how best to provide such abilities. (If in fact doing so is warranted, as most use cases are satisfied by the general `sam_read1()`/etc API rather than needing CRAM-specific functions.)

**Comment by smoe** [comment]
@daviesrob:  I just read on https://github.com/biod/sambamba/issues/425 (many thanks for the link) that @pjotrp is about to remove a dependency on htslib. While that solves the technical problem, it is also a defeat. Without knowing exactly what @pjotrp will be doing, some functionality of htslib will likely be reimplemented elsewhere. My motivation for this whole thread is of course to concentrate eyeballs and deveolpmental power on one version of htslib and increase the realm of possible adopters of your technology.

@jmarshall: Thank you for these suggestsions. I mentioned @pjotrp, @pjotrp, @pjotrp a few times in this thread aready. With a bit of luck he summons himself. In these github ages it is darn simple to just copy code and modify it to instant needs to then let it bitrot, not at least because of all those nasty short-term academic contracts and fast-paced technical developments. I just had a similar (albeit easier) request here https://github.com/xxsds/DYNAMIC/pull/22#issuecomment-654141715 .

Was there ever something like a chat between htslib and biobamba devs about what is really needed? Maybe you can direct the sambamba folks towards how you think your software should be used. I got the latest vers to compile after a few changes to the wrapper code. Tests pending.

**Comment by jmarshall** [comment]
> (such as sambamba and SeqLib)

Note BTW that the SeqLib problem has been resolved in Debian ([bug 946924](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946924)), and would have been in upstream SeqLib (walaj/SeqLib#53) if that were still maintained.

**Comment by daviesrob** [comment]
If @pjotrp would like to use this interface, or something like it, then he's welcome to come and discuss it with us.  I'm sure we can come up with something suitable, and also help with upgrading sambamba to work with the latest versions of HTSlib.

What I would prefer not to happen is to have Debian creating patches like [this](https://sources.debian.org/patches/htslib/1.10.2-4/cram_to_bam_export.patch/) which change the external interface of the library.  Doing so makes it impossible for us to know which interfaces are actually in use and which parts of the library can be safely changed without breaking third-party code.

Still, this is an improvement on the case in [bug 881170](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=881170) as at least you got in contact with us over this one :smile:.  But I would appreciate if you did not add any more patches like this in the future without getting in touch with us first.

**Comment by pjotrp** [comment]
Sorry all for the upset. It is an old patch by Artem when he added CRAM support. We better drop the dependency altogether because sambamba mostly shines for specific use cases for sam/bam.

**Comment by daviesrob** [comment]
Well, it would be a pity if sambamba lost the ability to read cram, as we really want everyone to be using cram for on-disk storage.  Is there any particular reason why it was implemented in the way it's been done, as opposed to using `sam_read1()`?

**Comment by jkbonfield** [comment]
On a break atm so not going to spend too long thinking, but there is some benefit to using the lower level CRAM APIs as far as speed goes (fewer memcpys) or efficiency of decoding only the bits you care about, but practically speaking we've just never fleshed out the API properly for that as all that people wanted was an in-memory BAM object.  One day, with htslib 2.0, we could do it properly.  Until then I'm not really in favour of opening this up unless there really is no reason why it can't use the normal procedures.

**Comment by pjotrp** [comment]
Alright. Before removing htslib I'll assess if it is worth keeping CRAM support in. At the moment no one is using CRAM with sambamba as far as I know. But how can you really tell ;)

**Comment by smoe** [comment]
@pjotrp, yes, please investigate if the public API would be up to what you need. Sambamba is Debian's final piece for the RoSA (https://github.com/bartongroup/RoSA) packaging puzzle.  To keep spirits up, I suggest if they are not using cram already then we prepare a patch to make them use it :o)

**Comment by pjotrp** [comment]
Sambamba only uses htslib for reading and writing CRAM. There is no real value over using samtools proper for conversions from/to other formats, so we'll drop that. Sambamba is still used for a small number of features and we'll keep supporting those. But other than that it is in maintenance mode. I may pick it up again when we want BAM/CRAM support for pangenome work.

**Comment by jkbonfield** [comment]
I'm closing this issue then as things have moved on.

Looking again, it appears the reason `cram_to_bam` is used is because a partial CRAM implementation has been written.  It knows about containers and slices already, but hasn't yet got the code to convert those to its internal sequence representation so this is a reasonable way to convert the slice to a bam record.  The main heart of this function is a little bit of name and RG aux tag shenanigans and then calling `bam_construct_seq`.  This latter function is now exposed in the new name of `bam_set1` so rewriting the rest of `cram_to_bam` should be quite simple.

Failing that, just call `sam_read1` as an interim solution until the CRAM implementation is finished.  Either way sounds like a better solution.
