### ISSUE TITLE
kstring.h ks_free() use of `free()` crashes alternative compilers

### ISSUE THREAD

**Issue by sg-james** [samtools/htslib#1114]
### Descriptions

On windows, in an msvc application, with htslib (v1.10-ish?) compiled via mingw.

`ks_free()` is defined in the header `kstring.h` which uses `free()`.

This uses the msvc's free, while the alloc call inside htslib uses mingw's alloc, resulting in a crash

related #807

### Example:
```
sam_hdr_t* hdr = ...
bam1_t* rec = ...
kstring kstr;
ks_initialize(&kstr);

const int nbytes = sam_format1(hdr, rec, &kstr);
std::string s(kstr.s, kstr.l); // do something with kstr

ks_free(&kstr); // <-- crashes here 
```

### Workaround

```
#include <htslib/hts.h>

// ks_free(&kstr)
hts_free(kstr.s); // use the hts_free wrapper, in this case to mingw's `free()`
```

### Possible solution(s)

- moving ks_free definition into `kstring.c` (ABI issue?)
- including `hts.h` and using `hts_free()` (more header dependencies)
- moving `hts_free()` to some independent header file (preventing dragging large header)
- do nothing - it's easy enough to work around (once you know about it)

**Comment by valeriuo** [comment]
> Possible solution(s)
> 
>   - moving ks_free definition into kstring.c (ABI issue?)

That would need to be part of a concerted effort to make HTSlib fully compatible with MSVC and would also imply synchronizing with the upstream Klib [repo](https://github.com/attractivechaos/klib/). So it's probably not going to happen very soon.

>  - moving hts_free() to some independent header file (preventing dragging large header)

Considering the issue is loosely tied to Windows, `hts_free()` might be moved to `hts_os.h`.

**Comment by daviesrob** [comment]
The problem here is that 04b71e6b (part of #1051) moved the `realloc()` into a non-inlined function, while leaving the `free()` in the header.  Moving `ks_free()` wouldn't be a major problem, apart from the added function call overhead.  Adding new exported functions does not cause any backwards-compatibility problems with the ABI, and I think we've been slowly diverging from klib for a while now.

Moving `hts_free()` to `hts_os.h` would require `hts.h` to include `hts_os.h` for backwards-compatibility.  Another solution might be to have a Windows-specialised version of `ks_free()` that calls `hts_free()`.  The `hts_free()` protoype could be included in that function to avoid dragging in the whole of `hts.h`.  It would be a little bit ugly, but it should work.

**Comment by jmarshall** [comment]
I suppose an alternative would be to revert 04b71e6b10bdc55cd288a45118a9a563b67add5f and restore both `realloc` and `free` to the inlined functions in the header. Fortunately #1051 has not appeared in a release, so all options are available.

I've been testing that and have not yet been able to reproduce the warnings that lead to moving the `realloc` to a non-inlined function.

**Comment by jkbonfield** [comment]
One pertinent comment from #1051 is "Yep and for this reason IMHO there's little point in inlining the rounding up..." (John).

It does make me think that it could well use a roundup function rather than that complex inline, but the logic of caling roundup and calling realloc could indeed be in the static inline.  Hopefully it won't bloat things too much to prevent inlining (which was happening sometimes with the original code pre-1051 if I recall).   We could redo Rob's -Winline tests to check.

**Comment by jkbonfield** [comment]
Or this, which is the minimal I can think of for inlined code, but keeping realloc:

```
// As ks_resize_b, but assignment logic is in a func to minimise inlined code
int ks_resize_b2(kstring_t *s, size_t size)
{
        extern int ks_resize3(kstring_t *s, size_t size, char *buf);

        if (s->m < size) {
            extern size_t kroundup_size_t(size_t size);
            char *tmp = (char*)realloc(s->s, size=kroundup_size_t(size));
            return kresize3(s, size, tmp);
        }
        return 0;
}

**Comment by jkbonfield** [comment]
> I've been testing that and have not yet been able to reproduce the warnings that led to moving the `realloc` to a non-inlined function.

https://github.com/samtools/htslib/pull/1048/commits/b73fe4e802a747ed0d973ecec66b63b207d836cc suggests it was a gcc 9 addition.  Possibly it got removed again in later gcc 9s and 10s, because it was tripping up a lot of people and although helpful in some situations, it also had false positives.
