### ISSUE TITLE
uncompressed bcf slower than compressed

### ISSUE THREAD

**Issue by goranvinterhalter** [samtools/htslib#1128]
I find that bcf is a lot slower to read when uncompressed than with default compression level.
tested on:
 - mac OS
 - htslib 1.10.2 and 9.1
 - using both bcftools and with pysam

As deflation should be the most expensive step it makes no sense?

**Comment by jkbonfield** [comment]
I'm not on MacOS, but I've tested this with `bcftools view -f PASS` (which discards everything on my test file so is a naive read speed tester) and it's around 50% faster on uncompressed BCF than compressed BCF.

If you've built htslib from source, you can also run the `test/test_view -B` command for benchmarking read-only speeds. For me this shows around 2x speed up with uncompressed data.

It's still not as fast as it ought to be, with over half the CPU time being spent doing record sanity checking (which isn't in the correct spot either so it's done in the main thread instead of any child threads), but I can find no circumstance where compressed data is quicker.

Do you have the exact command lines you are using?  Also please report the file sizes so we can see what sort of compression ratio there is between the two files.

Thanks

**Comment by goranvinterhalter** [comment]
Well this is embarrassing...
I was not using bcftools, but `pysam` to convert files. 
When you open a file in mode "w0" (instead of "wb0") it writes a vcf instead of a bcf :) 
Sorry I wasted you your time!

**Comment by jkbonfield** [comment]
No problem, we all have those silly moments and thanks for letting us know.
