### ISSUE TITLE
Fail to index using samtools for a bam file

### ISSUE THREAD

**Issue by HanXiaoEvo** [samtools/htslib#1141]
Hello people,

I am posting this question aiming to solve another error in ANGSD but related to samtools indexing.

As my bam file can not be open by ANGSD, I did some exploration in samtools, what I found:
1. santools view XXX.bam | head works.
2. samtools index XXX.bam, didn't work, the error is:
[E::hts_idx_push] Region 1747042382..1747042497 cannot be stored in a bai index. Try using a csi index with min_shift = 14, n_lvls >= 6samtools index: failed to create index for "ThPI_1.bam": Numerical result out of range

The reference genome is in a draft state and has many scaffords. Thank you very much for any suggestions!

Best regards,
Han Xiao

**Comment by HanXiaoEvo** [comment]
Some more info may be relevant. 

The bam files were generated from ddRADSeq and aligned to the fish genome by BWA. The original bam files were indexed successfully while not working when I copy just the bam files and do this again. I will check the original index log now.

**Comment by jkbonfield** [comment]
This error message is because you have a reference sequence > 512Mb in length.   This isn't possible to index using .bai indices.

As it states, you'll need to use a CSI index.  The defaults are sufficient to cope with a reference this large.  Please try `samtools index -c file.bam`.

**Comment by HanXiaoEvo** [comment]
Thanks for your suggestions! However I did that and got this error now: 
samtools index -c ThPI_1.sort.bam 
[E::hts_idx_push] Region 1747042382..1747042497 cannot be stored in a csi index with min_shift = 14, n_lvls = 5. Try using min_shift = 14, n_lvls >= 6
samtools index: failed to create index for "ThPI_1.sort.bam": Numerical result out of range

I am actually trying to figure out why this bam files can not be read by samtools ( htslib) for ANGSD. We ever indexed the files successfully but no idea why it didn´t work now.

**Comment by jkbonfield** [comment]
Hmm, one for @pd3 then (author of CSI).

Petr, "samtools index" only offers -m for changing min_shift.  There isn't an option to adjust n_lvls.  How do these relate?  Presumably it's possible to increase min_shift instead of increasing n_lvls, but it's really unhelpful if the guidance the program gives is for the other way around.  Ideally it'd report example "samtools index -c" command line options to make it crystal clear what to do.

Also, what's actually most useful to do from an index / random-access efficiency?  Larger bins means more data pulled back on small queries, but deeper levels means more separate file offsets to pull back from (more seeking).  I'm not sure what's optimal given a "normal" (whatever that is) work load.

For @HanXiaoEvo, try `samtools index -c -m 16`  maybe, which should have bins of 64Kb instead of 16Kb and hopefully then still fits within 5 levels.

**Comment by daviesrob** [comment]
Are the lengths in your BAM header correct?  HTSlib uses the information in the header to calculate the `n_lvls` parameter for the index.  If you later get a read with a position ending beyond the highest length reported in the header it may trigger this error.

**Comment by HanXiaoEvo** [comment]
Thanks to all of your attributions!

I will check the header. The thing is that I just talked to my supervisor and he said the bam files were indexed by bamtools before as there seems something wrong using the samtools at that time.

My point is mostly not to index it again but to check why the file can not bye read by samtools, which is needed to run ANGSD.

So I will go for the header,, thank you very much again!

Cheers,
Han

**Comment by jkbonfield** [comment]
Note "succeeding" to index doesn't necessarily mean it worked!  I've no idea what checking bamtools has, but we've seen this before (with early samtools) where malformed data just gets glossed over and the index isn't entirely complete.

I suspect your alignment file is corrupted in some manner with records out of position.

**Comment by jkbonfield** [comment]
Infact, yes I've just done the test.  I produced a malformed file with POS wildly out of range and `bamtools index -in fail.bam` "succeeds".   If I attempt to do a region query on it though I don't get the data back.

You'd probably be best using samtools to index so it can spot this data (which is now what you're seeing).

**Comment by valeriuo** [comment]
Similar to https://github.com/samtools/samtools/issues/1118 and https://github.com/samtools/samtools/issues/1126

**Comment by HanXiaoEvo** [comment]
I see what you mean! Well not sure if it is the case, but the bam files have been used in SNP calling and the downstream analyses work well. I assume the files should be more or less OK. I will check it out as you suggested still! Thank you very much again!

**Comment by jkbonfield** [comment]
Well "Region 1747042382..1747042497" is huge.  That's 1.75Gbase.  You can do something like  `samtools view ThPI_1.bam | awk '$4 > 1e9'` to view all records with positions beyond 1Gb into their chromosomes.

You can also look at the SAM header to find the longest `@SQ` line with something like this:

```
samtools view -H ThPI_1.bam|grep '^@SQ'|sed 's/.*LN:\([0-9]*\)/\1 &/'|sort -nr | head -1
```

That fact that it "works" may be simply that it "works well enough" rather than 100% works.  For example if some records have been badly aligned and emitted with bogus positions, then it may not affect SNP calling significantly, if at all, provided the prevalence of such broken alignments is low.  That doesn't however mean it is wise to ignore the problem.  Ideally if there is something emitting broken records then the author of that bit of software should be informed.

**Comment by HanXiaoEvo** [comment]
Sry that I just got time to get through carefully all the new comments and suggestion, thank you very much again!

To summarize:

1. samtools index -c -m 16  made the index .csi file, while as you said it may not be used by any other program but it works :) 

2. To check the longest:
samtools view -H ThPI_1.bam|grep '^@SQ'|sed 's/.*LN:\([0-9]*\)/\1 &/'|sort -nr | head -190519428 @SQ	SN:NC_036842.1	LN:90519428
samtools view ThPI_1.bam | awk '$4 > 1e9'  nothing found, so there should be no such long reads/region or whatever if I understand it not correctly.
However I got quite confused with what you said that "Region 1747042382..1747042497" is huge. That's 1.75Gbase." As the whole genome is 2.3 GB, not to mention it is a draft genome and my data are ddRADSeq and paired-end reads of 151 bp. I am not really familiar with this but if you can help me with this naive question I will really appreciate it! 

3. As the header was mentioned so I check a bit and hopefully it is the right way to do so, what I go is like this:

@HD     VN:1.5  SO:coordinate@SQ     SN:NC_036838.1  LN:58017395@SQ     SN:NC_036839.1  LN:43538721@SQ     SN:NC_036840.1  LN:36001405@SQ     SN:NC_036841.1  LN:28292882@SQ     SN:NC_036842.1  LN:90519428@SQ     SN:NC_036843.1  LN:29595583@SQ     SN:NC_036844.1  LN:37080635@SQ     SN:NC_036845.1  LN:30249148@SQ     SN:NC_036846.1  LN:26025374@SQ     SN:NC_036847.1  LN:34303021@SQ     SN:NC_036848.1  LN:54842065

4. Finally, it will be really nice if you can explain a little bit more about the possibility of bad indexing, to what context it might be due to external factors like the quality of the reference genome, and what context may due to internal factors by us, e.g. alignment? Does it because of bad alignments? I think we get more than 90% of mapping at least and with some tight criteria. I can find it if these are necessary. 

All in all, I just hope there won´t be any improper processing of the data and if so, I´d like to check and try to solve it. However my initial reason to try the samtools indexing is that my bam file can not be read in ANGSD. If any of you has any ideas will be also highly welcome!

Best regards,
Han Xiao

**Comment by HanXiaoEvo** [comment]
Actually the problem in ANGSD is just solved as one file name was a bit wrong, which is not found by the ANGSD guys. Still thank you so much for your considerations and if you check and reply to my previous post I will really appreciate it!

**Comment by jkbonfield** [comment]
>     1. samtools index -c -m 16  made the index .csi file, while as you said it may not be used by any other program but it works :)

Ok so that confirms the data can at least be indexed, just not with the default BAI.  This also confirms that there is a mismatch between your headers and the data records themselves, as CSI auto-scales based on the header, but in your case you had to be explicit to get that to work.

>     2. To check the longest:
>        samtools view -H ThPI_1.bam|grep '^@sq'|sed 's/._LN:([0-9]_)/\1 &/'|sort -nr | head -1
> 90519428 @sq	SN:NC_036842.1	LN:90519428

That's your longest reference then, approx 90 Mbases.

>        samtools view ThPI_1.bam | awk '$4 > 1e9'  nothing found, so there should be no such long reads/region or whatever if I understand it not correctly.

I don't understand why you got nothing there.  It worked for me on a test file.  Somewhere however there must be something out of range.  Maybe it's just a different version of awk or something not accepting 1e9 as a number.  I really don't know.

It's possible to find the read with the largest POS field using unix sort, but it'd be slow!  Eg

```
samtools view in.bam | sort -k 4n | tail -1
```

>        However I got quite confused with what you said that "Region 1747042382..1747042497" is huge. That's 1.75Gbase." As the whole genome is 2.3 GB, not to mention it is a draft genome and my data are ddRADSeq and paired-end reads of 151 bp. I am not really familiar with this but if you can help me with this naive question I will really appreciate it!

Obviously it's erroneous data.  Yes your whole genome may be highly fragmented with no long references (as we see the longest is 90Mb), but this error is produced when reads have a large POS field.  The problem is our data files are now all so huge that you cannot just read through it to spot the errant record.  We probably need a better error message, with the full line or a record name included.

This code is what emits that message:

https://github.com/samtools/htslib/blob/develop/hts.c#L1862-L1890

It's given the start and end coordinate of every record it processes while indexing, so somewhere it found one with position 1747042382 (or 1747042383 maybe as it may be reporting a 0-based).

>     1. Finally, it will be really nice if you can explain a little bit more about the possibility of bad indexing, to what context it might be due to external factors like the quality of the reference genome, and what context may due to internal factors by us, e.g. alignment? Does it because of bad alignments? I think we get more than 90% of mapping at least and with some tight criteria. I can find it if these are necessary.

I wouldn't expect a low quality reference genome to cause issues, nor the percentage of reads mapping.  These things happens all the while.  It's probably low quality software instead!  What that could be however I have no idea as it'll depend on what you've used.

**Comment by HanXiaoEvo** [comment]
Thank you soooo much for all your detailed answers! I am learning a lot! I am more or less done with this question for now (although the consideration never ends) so you could close this issue if you want! Or I can do that! Thank you again!

Cheers,
Han
