### ISSUE TITLE
Strange library version numbers

### ISSUE THREAD

**Issue by ryandesign** [samtools/htslib#1144]
Hi, I'm the maintainer of htslib in MacPorts. I'm sure I've noticed this before but I guess I never reported it before so I'm reporting it now.

Your project's library has very strange version numbers. Here's what I see on my Mac after installing htslib 1.11:

```
$ ls -l /opt/local/lib/libhts*
-rwxr-xr-x  1 root  admin  1362172 Sep 25 03:39 /opt/local/lib/libhts.1.11.dylib
lrwxr-xr-x  1 root  admin       17 Sep 25 03:39 /opt/local/lib/libhts.3.dylib -> libhts.1.11.dylib
-rw-r--r--  1 root  admin  1837824 Sep 25 03:39 /opt/local/lib/libhts.a
lrwxr-xr-x  1 root  admin       17 Sep 25 03:39 /opt/local/lib/libhts.dylib -> libhts.1.11.dylib
```

That number between "libhts." and ".dylib" is the library's major version number. You're claiming that your library's major version number is both 3 and 1.11. That's strange. Usually a library's major version number is just an integer, and you increase it when you make a huge backward-incompatible change and want to force everyone who uses your library to have to relink. (So, ideally, you never do that.)

Now let's look at the minor version numbers:

```
$ otool -L /opt/local/lib/libhts.1.11.dylib
/opt/local/lib/libhts.1.11.dylib:
	/opt/local/lib/libhts.3.dylib (compatibility version 3.0.0, current version 1.11.0)
	/opt/local/lib/liblzma.5.dylib (compatibility version 8.0.0, current version 8.5.0)
	/opt/local/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.8)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/opt/local/lib/libcurl.4.dylib (compatibility version 11.0.0, current version 11.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

You're claiming that your library's minor version is currently 1.11.0, and that it's compatible with minor version 3.0.0. That's strange. Your library can't claim to be compatible with a minor version of itself that hasn't been released yet.

It's also unusual that one of your library's major version numbers and its current minor version number appear to be the same as your project's release version number. Normally these are separate things that are incremented on their own separate timetables.

**Comment by jmarshall** [comment]
HTSlib uses the usual Unix SOVERSION model even on macOS. So what Apple calls the “major version” (the thing in the filename) and the Apple-invented “compatibility version” are both set to the soversion, and this is unrelated to the value in what Apple calls the “minor version”.

>     $ ls -l /opt/local/lib/libhts*
>     -rwxr-xr-x  …  Sep 25 /opt/local/lib/libhts.1.11.dylib
>     lrwxr-xr-x  …  Sep 25 /opt/local/lib/libhts.3.dylib -> libhts.1.11.dylib
>
> That number between "libhts." and ".dylib" is the library's major version number.

“3” is the shared library's SOVERSION (in the usual Unix fashion), and “1.11” is the package's version number. These are separate things that are incremented on their own separate timetables.

 The _libfoo.SOVERSION.dylib_ is of course what is needed at runtime, but it's not unusual to install it as a symlink to a more exactly-versioned dylib — even though that extra exactly-versioned copy is not strictly necessary. See also #932, the discussion on [Fedora's package in 1326504](https://bugzilla.redhat.com/show_bug.cgi?id=1326504), and the [resulting Fedora mailing list discussion](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/WHZBVT3Y7TKYAEK6EXEY6L77W42T7LJX/). As mentioned in https://github.com/samtools/htslib/issues/932#issuecomment-536212327 et al, `libhts.so.X.Y` / `libhts.X.Y.dylib` followed the conventions of the time (2013; see 67993487db423a7c438eae72777946fd9aa81c63); since then some other packages appear to have moved to `libhts-X.Y.so` / `libhts-X.Y.dylib` for the fully-package-versioned copy — which is more clearly separated from `libhts.so.SOVER` and HTSlib may wish to follow that newer convention next time it bumps its soversion.

So far, so generic; now to the macOS- and dylib-specific aspects.

Apple's separate compatibility version / current version values embedded in the dylib header allow for more general shared library versioning schemes than simple soversions, but HTSlib chose not to take advantage of that, preferring instead to use the same soversion on macOS as on other platforms.

Hence, following Apple's [Dynamic Library documentation](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryDesignGuidelines.html#//apple_ref/doc/uid/TP40002013-SW23) and various tutorials that I no longer recall, we set HTSlib up on OS X so that it uses an integer SOVERSION for both the filename component (“major version”) and compatibility version. The ambiguous text now in Apple's documentation notwithstanding —

> Before loading a dynamic library, the dynamic loader compares the current version of the `.dylib` file in the user’s file system with the compatibility version of the `.dylib` file the client was linked with in the developer’s file system.

— as I understand it, the dylib header compatibility and current versions are never directly compared to each other. Rather it is the _current **major** version per the filename in the user's file system_ that is compared to the compatibility version recorded at link time. Hence AIUI using a SOVERSION like this as a simplified mechanism is compatible with Apple's mechanisms. This is borne out by the fact that executables dynamically linked against _libhts.SOVER.dylib_ have ever been able to start up on macOS at all. (Unless you have evidence to the contrary?)

(Hmmm… _liblzma.5.dylib_ in your `otool` listing would appear to be a counter-example to this. Perhaps the truth is that this check is not implemented.)

**Comment by ryandesign** [comment]
> Apple's documentation notwithstanding —
> 
> > Before loading a dynamic library, the dynamic loader compares the current version of the `.dylib` file in the user’s file system with the compatibility version of the `.dylib` file the client was linked with in the developer’s file system.
> 
> — as I understand it, the dylib header compatibility and current versions are never directly compared to each other. Rather it is the _current **major** version per the filename in the user's file system_ that is compared to the compatibility version recorded at link time.

If this was your understanding, then I understand how htslib got to where it is. It's a misunderstanding, however; that's not how it works.

macOS never compares your library's major version with anything. macOS doesn't know or care what your library's major version is, nor is your library required to have one at all. Your library happens to use an integer major version of "3", but other libraries like the Mac's own System library have an alphabetic major version like "A" and "B", and the Apple documentation you linked to even gives the strange but valid example of using Roman numeral library major versions like "I" and "II". You could even name the major versions of your library "one" and "two", "alpha" and "beta", or "alice" and "bob" if desired. All that matters is whether the exact absolute library path that was written into the program when it was linked with the library exists at runtime. If it does, it tries to use the library; if not, then a "Library not loaded" error occurs.

Consider bcftools:

```
$ otool -L /opt/local/bin/bcftools
/opt/local/bin/bcftools:
	/opt/local/lib/libhts.3.dylib (compatibility version 3.0.0, current version 1.11.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
```

To compile this program, a command such as the following was used:

```
clang -L/opt/local/lib -lhts [lots of other flags] -o bcftools
```

At link time, the linker looked through /opt/local/lib and other library paths for libhts.dylib or libhts.a and found /opt/local/lib/libhts.dylib:

```
$ ls -l /opt/local/lib/libhts*
-rwxr-xr-x  1 root  admin  1362172 Sep 25 03:39 /opt/local/lib/libhts.1.11.dylib
lrwxr-xr-x  1 root  admin       17 Sep 25 03:39 /opt/local/lib/libhts.3.dylib -> libhts.1.11.dylib
-rw-r--r--  1 root  admin  1837824 Sep 25 03:39 /opt/local/lib/libhts.a
lrwxr-xr-x  1 root  admin       17 Sep 25 03:39 /opt/local/lib/libhts.dylib -> libhts.1.11.dylib
```

It happened to be a symlink to libhts.1.11.dylib. It opened that library and found that its install_name was /opt/local/lib/libhts.3.dylib:

```
$ otool -D /opt/local/lib/libhts.dylib
/opt/local/lib/libhts.dylib:
/opt/local/lib/libhts.3.dylib
```

and it baked that install_name into bcftools.

At runtime, when I run bcftools, the dynamic library loader will iterate over all of the linked libraries and try to load them from that exact path. So for example it will look for a file /opt/local/lib/libhts.3.dylib. In this case, it exists and it happens to be a symlink to libhts.1.11.dylib, so it tries to load that library -- first checking its minor version.

This is where your current setup shouldn't work at all. According to the Apple documentation you provided and how I've always understood it to work, the following should happen:

> Before loading a dynamic library, the dynamic loader compares the current version of the .dylib file in the user’s file system

which is 1.11.0

> with the compatibility version of the .dylib file the client was linked with in the developer’s file system.

which is 3.0.0

> If the current version is earlier (less) than the compatibility version,

which it is: current version 1.11.0 is less than compatibility version 3.0.0

> the dependent library is not loaded. Therefore, the launch process (for client apps) or the load process (for client libraries) is aborted.

So what you have now should not work -- we should see an "Incompatible library version" error -- yet it works. I have now looked at the [source code of dyld](https://opensource.apple.com/source/dyld/dyld-750.6/src/ImageLoader.cpp.auto.html) (line 744) and determined that it does *not* do what the documentation says it does. In fact it compares the *compatibility version* of the .dylib file in the user’s file system (3.0.0) with the compatibility version of the .dylib file the client was linked with in the developer’s file system (3.0.0). Since the former is not less than the latter, the library is loaded successfully. I believe this is a bug in dyld -- I think it should behave the way it is documented -- and have filed it with Apple as [FB8747098](https://feedbackassistant.apple.com/feedback/8747098) (you will not be able to access this link).

Back to my point of separating the package version from the library version, maybe it helps to look at some of the libraries libhts is linked with:

```
$ otool -L /opt/local/lib/libhts.1.11.dylib
/opt/local/lib/libhts.1.11.dylib:
	/opt/local/lib/libhts.3.dylib (compatibility version 3.0.0, current version 1.11.0)
	/opt/local/lib/liblzma.5.dylib (compatibility version 8.0.0, current version 8.5.0)
	/opt/local/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.8)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/opt/local/lib/libcurl.4.dylib (compatibility version 11.0.0, current version 11.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

* liblzma is part of xz version 5.2.5. Its major library version is 5, its minor version is 8.5.0, and it is compatible with minor versions as low as 8.0.0, meaning if I use my computer to link a program with my liblzma which is major version 5 minor version 8.5.0, I can distribute that program to someone who has an older version of liblzma major version 5 as long as its minor version is 8.0.0 or greater.
* libcurl is part of curl version 7.72.0. Its major library version is 4, its minor version is 11.0.0 and it is compatible with minor versions as low as 11.0.0.
* And libSystem is part of macOS version 10.13.6. Its major library version is B, its minor version is 1252.50.4 and it is compatible with minor versions as low as 1.0.0.

Note how the package versions 5.2.5, 7.72.0, and 10.13.6 do not appear anywhere in the library versioning.

libbz2 and libz are antiexamples. Their library versioning does include the package version, which is not advisable: There is no reason to tie the package version and library major or minor version together. What if you need to do a release that does not modify the library at all, for example you're fixing a bug in a sample program that uses the library or you're updating the documentation? What if you decide to introduce a new companion library libhtsplus that is part of the same source code package? There's no reason why its version number should start from the same place that libhts left off, nor is there any reason why you should need to increase the version of both libraries if perhaps only one of them has changed in a particular release.

Your library's minor current version *should* increase in every release in which it has changed. Unfortunately I don't know what criteria one should use to decide whether to increase the first, second, or third number of the minor current version when making a backward-compatible chnage, nor how to decide whether to increase the minor compatibility version or the major version when making a backward-incompatible change.

You *can* (in the sense that it will technically work) have a symlink libhts.1.11.dylib pointing to libhts.3.dylib, or vice versa as you currently do, but it serves no purpose other than confusion. It makes exactly as much sense as having a symlink libhts.happy-birthday.dylib pointing to libhts.3.dylib or vice versa, since neither "happy-birthday" nor "1.11" are your library's major version number. Or, per the Fedora discussion you linked to, "Unusual, but valid."

If you used libtool for your library, it would handle library versioning correctly for you if you follow [their rules](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html). Their current:revision:age does not correspond directly to macOS major or minor library version numbers or Linux soversions; there are different calculations involved for each platform. You would have to experiment with different values of current:revision:age to find the one that corresponds to major version 3, current minor version 3.0.0, compatibility minor version 3.0.0 as a starting point (or possibly higher; you would need to check that the version on each platform does not decrease), then increment following their rules for subsequent releases.

**Comment by jkbonfield** [comment]
> At runtime, when I run bcftools, the dynamic library loader will iterate over all of the linked libraries and try to load them from that exact path. So for example it will look for a file /opt/local/lib/libhts.3.dylib. In this case, it exists and it happens to be a symlink to libhts.1.11.dylib, so it tries to load that library -- first checking its minor version.
> 
> This is where your current setup shouldn't work at all. According to the Apple documentation you provided and how I've always understood it to work, the following should happen:
> 
> > Before loading a dynamic library, the dynamic loader compares the current version of the .dylib file in the user’s file system
> 
> which is 1.11.0

I think this is not correct.  The *filename* happens to contain 1.11.0 but it is not the library version as far as compatibility checks go, simply the source / package release number.   I'm not a Mac user though, so it's possible they may well be sailing against the wind with regards to how to do this vs other unix/linux systems.

Well, it *shouldn't* be correct.  I'm a bit lost as to how things were setup on Mac vs Linux.  For linux we set -soname 3.0.0

```

> So what you have now should not work -- we should see an "Incompatible library version" error -- yet it works. I have now looked at the [source code of dyld](https://opensource.apple.com/source/dyld/dyld-750.6/src/ImageLoader.cpp.auto.html) (line 744) and determined that it does _not_ do what the documentation says it does. In fact it compares the _compatibility version_ of the .dylib file in the user’s file system (3.0.0) with the compatibility version of the .dylib file the client was linked with in the developer’s file system (3.0.0). Since the former is not less than the latter, the library is loaded successfully. I believe this is a bug in dyld -- I think it should behave the way it is documented -- and have filed it with Apple as [FB8747098](https://feedbackassistant.apple.com/feedback/8747098) (you will not be able to access this link).

I suspect this is more likely to be a documentation flaw than a library strategy flaw.  I think how it's currently working is compatible with other systems, and I would imagine that was their intention, even if not worded as such.

> 	/opt/local/lib/libhts.3.dylib (compatibility version 3.0.0, current version 1.11.0)
> 	/opt/local/lib/liblzma.5.dylib (compatibility version 8.0.0, current version 8.5.0)
> 	/opt/local/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.8)
> 	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
> 	/opt/local/lib/libcurl.4.dylib (compatibility version 11.0.0, current version 11.0.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
> ```
> 
>     * liblzma is part of xz version 5.2.5. Its major library version is 5, its minor version is 8.5.0, and it is compatible with minor versions as low as 8.0.0, meaning if I use my computer to link a program with my liblzma which is major version 5 minor version 8.5.0, I can distribute that program to someone who has an older version of liblzma major version 5 as long as its minor version is 8.0.0 or greater.

I'm not entirely sure what MacOS X uses "current version" for, but if it really is checking it vs compatibility version then I agree ideally it should be reporting 3.0.0 as the current version (or 3.0.1 etc if we've done compatible code patches, etc).  I wonder if this is just a side effect of using symlinks?


> 
>     * libcurl is part of curl version 7.72.0. Its major library version is 4, its minor version is 11.0.0 and it is compatible with minor versions as low as 11.0.0.
> 
>     * And libSystem is part of macOS version 10.13.6. Its major library version is B, its minor version is 1252.50.4 and it is compatible with minor versions as low as 1.0.0.
> 
> 
> Note how the package versions 5.2.5, 7.72.0, and 10.13.6 do not appear anywhere in the library versioning.
> 
> libbz2 and libz are antiexamples. Their library versioning does include the package version, which is not advisable: There is no reason to tie the package version and library major or minor version together. What if you need to do a release that does not modify the library at all, for example you're fixing a bug in a sample program that uses the library or you're updating the documentation? What if you decide to introduce a new companion library libhtsplus that is part of the same source code package? There's no reason why its version number should start from the same place that libhts left off, nor is there any reason why you should need to increase the version of both libraries if perhaps only one of them has changed in a particular release.
> 
> Your library's minor current version _should_ increase in every release in which it has changed. Unfortunately I don't know what criteria one should use to decide whether to increase the first, second, or third number of the minor current version when making a backward-compatible chnage, nor how to decide whether to increase the minor compatibility version or the major version when making a backward-incompatible change.
> 
> You _can_ (in the sense that it will technically work) have a symlink libhts.1.11.dylib pointing to libhts.3.dylib, or vice versa as you currently do, but it serves no purpose other than confusion. It makes exactly as much sense as having a symlink libhts.happy-birthday.dylib pointing to libhts.3.dylib or vice versa, since neither "happy-birthday" nor "1.11" are your library's major version number. Or, per the Fedora discussion you linked to, "Unusual, but valid."
> 
> If you used libtool for your library, it would handle library versioning correctly for you if you follow [their rules](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html). Their current:revision:age does not correspond directly to macOS major or minor library version numbers or Linux soversions; there are different calculations involved for each platform. You would have to experiment with different values of current:revision:age to find the one that corresponds to major version 3, current minor version 3.0.0, compatibility minor version 3.0.0 as a starting point (or possibly higher; you would need to check that the version on each platform does not decrease), then increment following their rules for subsequent releases.

**Comment by jkbonfield** [comment]
[Sorry, accidental early post midediting due to odd github keybindings.]

> At runtime, when I run bcftools, the dynamic library loader will iterate over all of the linked libraries and try to load them from that exact path. So for example it will look for a file /opt/local/lib/libhts.3.dylib. In this case, it exists and it happens to be a symlink to libhts.1.11.dylib, so it tries to load that library -- first checking its minor version.
> 
> This is where your current setup shouldn't work at all. According to the Apple documentation you provided and how I've always understood it to work, the following should happen:
> 
> > Before loading a dynamic library, the dynamic loader compares the current version of the .dylib file in the user’s file system
> 
> which is 1.11.0

I think this is not correct.  The *filename* happens to contain 1.11.0 but it is not the library version as far as compatibility checks go, simply the source / package release number.   I'm not a Mac user though, so it's possible they may well be sailing against the wind with regards to how to do this vs other unix/linux systems.

Well, it *shouldn't* be correct.  I'm a bit lost as to how things were setup on Mac vs Linux.  For linux we set -soname 3.0.0

```
libhts.so: $(LIBHTS_OBJS:.o=.pico)
        $(CC) -shared -Wl,-soname,libhts.so.$(LIBHTS_SOVERSION) $(LDFLAGS) -o $@ $(LIBHTS_OBJS:.o=.pico) $(LIBS) -lpthread
        ln -sf $@ libhts.so.$(LIBHTS_SOVERSION)
```

That ends up passing `-soname libhts.so.3` to the link line.

On MacOS we have a different set of options:

```
# Similarly this also creates libhts.NN.dylib as a byproduct, so that programs
# when run can find this uninstalled shared library (when $DYLD_LIBRARY_PATH
# includes this project's build directory).

libhts.dylib: $(LIBHTS_OBJS)
        $(CC) -dynamiclib -install_name $(libdir)/libhts.$(LIBHTS_SOVERSION).dylib -current_version $(NUMERIC_VERSION) -compatibility_version $(MACH_O_COMPATIBILITY_VERSION) $(LDFLAGS) -o $@ $(LIBHTS_OBJS) $(LIBS)
        ln -sf $@ libhts.$(LIBHTS_SOVERSION).dylib
```

Here we set `-current_version 1.11.0` and `-compatibility_version 3`.    I struggled to find documentation on the compiler, but https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/CreatingDynamicLibraries.html seems to imply that indeed we shouldn't be using our package version for current_version, instead supply 3 or 3.0.0 as our ABI version.

**Comment by jkbonfield** [comment]
Relevant changes to this code for discussion.

2a86c68b - addition of MACH_O_COMPATIBILITY_VERSION text.  I think this only made a different between releases though as it's now the same as LIBHTS_SOVERSION again.

67993487 - initial addition of shared libraries.  `current_version` was set to package release number and `compatibility_version` to soname.

I suspect it's been wrong all along then.  Where MacOS is totally borked though is the insistance that these are minor version numbers with the major version being in the filename.  That's just... odd!  I don't get it.

I assume our intention was we'd write the filename as e.g. libhts.3.dylib for major version 3, and the minor version as package 1.11.0, and the compatibility version as 3 also.  The docs state under updating libraries "The major version (filename) and compatibility version of the library must remain the same".  It doesn't mention minor version in that bit.  However elsewhere I do find explicit linkage: https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryDesignGuidelines.html#//apple_ref/doc/uid/TP40002013-SW20

"The compatibility version number is similar to the minor version number; it’s set through the compiler -compatibility_version command-line option. The compatibility version number of a library release specifies the earliest minor version of the clients linked with that release can use. For instance, the example in Defining Client Compatibility indicates that Client 1.1 cannot use versions of the Draw library earlier than 1.2 because they don’t export the draw_polygon function. To view a library’s current and compatibility versions, use the otool -L <library> command."

So we have explicit statements that compatibility version is checked against filename, but elsewhere we have text (if not code apparently) implying that current version is using the same name-space and numbering as compatibility version.  I can understand how confusion arises as the docs spread the information over a large area.

**Comment by ryandesign** [comment]
> I think this is not correct. The _filename_ happens to contain 1.11.0 but it is not the library version as far as compatibility checks go, simply the source / package release number.

I agree 1.11.0 is your package release number. It does not belong anywhere in your library filename or its versioning info.

```
$ otool -L /opt/local/lib/libhts.1.11.dylib | head -n 2
/opt/local/lib/libhts.1.11.dylib:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               (a)
	/opt/local/lib/libhts.3.dylib (compatibility version 3.0.0, current version 1.11.0)
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                        ^^^^^                  ^^^^^^
	             (b)                                      (c)                     (d)
```

* (a) is your library's filename. It contains "1.11". It should instead contain your library's major version, "3".
* (b) is your library's install_name. It contains "3", your library's major version, as it should.
* (c) is your library's compatibility minor version. It is the earliest minor version of the library that could be used by an executable linked with this current minor version of the library. When you increase the major version, you reset this to 1.0.0.
* (d) is your library's current minor version. It should not be less than the compatibility version. You should increase it when you change your library. When you increase the major version, you reset this to 1.0.0.

> I'm not a Mac user though, so it's possible they may well be sailing against the wind with regards to how to do this vs other unix/linux systems.

I'm not a Linux user, but I have used Macs for 31 years and have been a manager of the MacPorts project for 11 years, so I know a bit about how macOS dynamic libraries work :) and they definitely are different from Linux shared libraries.

**Comment by jkbonfield** [comment]
> I'm not a Linux user, but I have used Macs for 31 years and have been a manager of the MacPorts project for 11 years, so I know a bit about how macOS dynamic libraries work :) and they definitely are different from Linux shared libraries.

It's not too dissimilar, except I think for the insistance of only using the minor versions in the soname equivalent rather than the full thing.  That's a bit odd, but I guess it does give them flexibility to have non-numeric versioning.  Maybe a hangover from wanting to name all verions after cats. ;-)

**Comment by ryandesign** [comment]
> The docs state under updating libraries "The major version (filename) and compatibility version of the library must remain the same".

You may be misreading this as "The major version (filename) and compatibility version of the library must remain the same *as one another*" which is not what it means. It means that (in this scenario where you are making a backward-compatible update of your library) the major version (filename) will stay the same *as it was*, and the compatibility minor version (which is not the same thing as the major version) will stay the same *as it was*, and only the current minor version will be increased.

> It doesn't mention minor version in that bit.

You missed the preceding sentences: The full bit was:

> When you can guarantee that the API of the new version of the library is compatible with the API that clients linked with earlier versions know about, you can deem the new version a minor revision. When you want to publish a minor revision of a dynamic library to users of the library’s clients (for example, the users of a program that uses your library) the only version information item you need to change is the library’s current version. The major version (filename) and compatibility version of the library must remain the same.

So it does mention minor version, in that "current version" means "current minor version" and "compatibility version" means "compatibility minor version".

> Moreover, how can the compatibility version and major (filename) version be compared when one is numeric and the other is "A"? Seriously Apple make this clearer...

As I stated, the major version is never compared with anything, except to the extent that it is part of the library's filename. If you change the major version of the library, you have changed the filename, thus you are now a different library than before.

> So we have explicit statements that compatibility version is checked against filename,

No, it does not say that.

**Comment by jmarshall** [comment]
> If this was your understanding, then I understand how htslib got to where it is. It's a misunderstanding, however; that's not how it works.

Thank you for your long treatise on the obvious parts of soname-based searching of shared library filenames and how you think Apple's compatibility/current version checking ought to work. While your fictional scheme is fairly sensible, as has been established it is not in fact how this works on macOS to date.

> I believe this is a bug in dyld -- I think it should behave the way it is documented -- and have filed it with Apple as FB8747098 (you will not be able to access this link).

Perhaps you would like to copy your report to [Open Radar](http://openradar.appspot.com/) so that there is a link that other people can access.

Both interpretations are compatible with the way macOS has worked to date, which is why _libhts.dylib_ has worked at all for the last seven years. However should your bug report produce any change from Apple (this has surely been reported many times before!), it seems likely that what would be enforced would be the comparison between linktime-embedded-compatibility-version and filesystem-dylib-current-version that you describe. Hence PR #1146 which I believe addresses all your reasonable concerns.

**Comment by jkbonfield** [comment]
> > So we have explicit statements that compatibility version is checked against filename,
> 
> No, it does not say that.

Agreed.  I realised my misinterpretation and edited my comment above, but you were already replying by then I guess.  Thanks for the reply though.   With hindsight saying they must remain the same would be better as "must remain unchanged" as there is no ambiguity as to whether "the same" implies equality.

Their fluid interchange between current version and minor version is unhelpful too, but I think I now understand what it's saying.

**Comment by daviesrob** [comment]
The MacOS [ld manual page](https://www.unix.com/man-page/OSX/1/ld/) is rather more clear on how these options work than the developer documentation:

```
-compatibility_version number
    Specifies the compatibility version number of the library.  When a library is loaded by dyld, the compatibility
    version is checked and if the program's version is greater that the library's version, it is an error.  The format
    of number is X[.Y[.Z]] where X must be a positive non-zero number less than or equal to 65535, and .Y and .Z
    are optional and if present must be non-negative numbers less than or equal to 255.  If the compatibility version
    number is not specified, it has a value of 0 and no checking is done when the library is used.  This option is also
    called -dylib_compatibility_version for compatibility.

-current_version number
    Specifies the current version number of the library. The current version of the library can be obtained
    programmatically by the user of the library so it can determine exactly which version of the library it is using.
    The format of number is X[.Y[.Z]] where X must be a positive non-zero number less than or equal to 65535,
    and .Y and .Z are optional and if present must be non-negative numbers less than or equal to 255.  If the version
    number is not specified, it has a value of 0.  This option is also called -dylib_current_version for compatibility.
```

So the dynamic loader only checks the compatibility version, which is why loading HTSlib works, and it looks like the current dyld code is working as intended.  Note that it doesn't mention major or minor versions here - the way they're done in the developer documentation looks like convention, and evidently from the output of `otool` above not everyone is following it in the same way.

The current version number appears to be something that programs linking against the library can interrogate to find out exactly what version they got (although it's not entirely clear how you do this).  It's a bit of a philosophical issue as to exactly what should go in there - `1.11` does after all describe exactly which version the library contains.  However `1.11` is obviously confusing as it's less than the ABI version (3).

I think the main problem is that we need to increment the `Y` digit of the compatibility version on each ABI compatible release, as currently `dyld` can't spot attempt to link a newer samtools against an older HTSlib.  Setting the current version to the same number would also be a good idea, if only to reduce the confusion it's causing.

**Comment by jmarshall** [comment]
@daviesrob: It's hard to remember exactly which sources I used when writing this part of the Makefile in 2013, but certainly this man page was part of it — especially as…

> When a library is loaded by dyld, the compatibility version is checked and if the program's version [as was embedded during linking] is greater that the library's version, it is an error.

…if this man page is correct, then setting compatibility_version to the platform-agnostic soversion is an entirely valid approach. You don't take advantage of macOS's extra knobs and checking, but you also don't need anything in addition to the generic soversion.

It's not confusing if you think of `compatibility_version` as being a fancy word for `soversion`.

**Comment by jmarshall** [comment]
> I think the main problem is that we need to increment the Y digit of the compatibility version on each ABI compatible release, as currently dyld can't spot attempt to link a newer samtools against an older HTSlib.

But linking a newer samtools against an older HTSlib is a valid thing to do (until the newer samtools uses a newer API function or similar, which will fail when the loader tries to resolve the symbol).

**Comment by jkbonfield** [comment]
> It's not confusing if you think of `compatibility_version` as being a fancy word for `soversion`.

Indeed, although Apple managed to make it confusing by calling it the minor version (!) in their other documentation.  However when that man page say "greater than the library's version" I think it's referring to the library current_version rather than filename "version", which is where our problem lies with treating one as package namespace and the other as soname namespace.  This PR fixes this, hence my +1.

@daviesrob
> I think the main problem is that we need to increment the Y digit of the compatibility version on each ABI compatible release, as currently dyld can't spot attempt to link a newer samtools against an older HTSlib. Setting the current version to the same number would also be a good idea, if only to reduce the confusion it's causing.

This is precisely what we do when we bump the minor version number of the library; eg 1.10, 1.11, etc.  As I mention above technically it's possible we could have no API nor ABI changes and still make a release, but it's unlikely and the consequences of falsely bumping the version are minor anyway.  The change in this PR to make compatibility version also use the same nomenclature is compatible with your wish to increment the Y digit.

**Comment by ryandesign** [comment]
> if this man page is correct

It does at least seem to match what the dyld source code says it does, as discussed above.

> Indeed, although Apple managed to make it confusing by calling it the minor version (!) in their other documentation. However when that man page say "greater than the library's version" I think it's referring to the library current_version rather than filename "version",

It is referring to the compatibility version. To clarify Apple's docs:

> When a library is loaded by dyld, the compatibility version is checked and if the program's version [the compatibility version of the library at the time the program was linked] is greater that the library's version [the compatibility version of the library found at runtime], it is an error.

Nothing compares anything with the version that is part of the filename.

**Comment by jmarshall** [comment]
> However when that man page say "greater than the library's version" I think it's referring to the library current_version rather than filename "version"

Who knows :smile: This comes immediately after text saying “the compatibility version is checked”, so “greater than the library's version” could equally be referring to “greater than the library's version of the compatibility_version”.

The word “version” here could refer to at least four different things, so if Apple wanted this man page to be unambiguous perhaps they could have fully qualified it each time they used it.

**Comment by daviesrob** [comment]
> But linking a newer samtools against an older HTSlib is a valid thing to do (until the newer samtools uses a newer API function or similar, which will fail when the loader tries to resolve the symbol).

I think the idea behind `-compatibility_version` is that you can reject the older library at the opening stage, maybe also allowing the loader to search more paths to see if it can find the right version.

Looking in `/usr/lib` on the Mac I'm using, it appears some libraries (e.g. `libiconv`) follow the Apple guidelines and put the minor ABI version into the first digit of the compatibility version, while others (e.g. `libz`) use the major ABI version for the first digit and minor for the second.  Also `libSystem` obviously follows the Apple rule of putting the minor ABI in compatibility version but has a current version that's way ahead, showing that current version and compatibility version don't really need to be related.

**Comment by jmarshall** [comment]
> I think the idea behind -compatibility_version is that you can reject the older library at the opening stage, maybe also allowing the loader to search more paths to see if it can find the right version.

That does seem likely. Nonetheless a portable library like HTSlib has the liberty of choosing whether to accept the maintenance burden of updating compatibility_version carefully enough to enable that potential functionality on macOS or to simplify the burden by just applying the generic soversion mechanism on macOS too.

One of the criteria used when setting up these Makefile rules was to avoid a macOS-specific burden by doing the latter. It seems certain that the status quo was arrived at (back in 2013) based on the it-means-compatibility_version reading of the man page; PR #1146 is similar but based on the idea that compatibility/current_version should be comparable (which as you say is maybe not borne out by libSystem). Both of them are IMHO elegant solutions that don't add any macOS-specific maintenance burden. I'm happy to expand on the reasoning behind either if needed while the HTSlib maintainers consider what, if any, changes are needed here.

**Comment by jkbonfield** [comment]
> 
> 
> > I think the idea behind -compatibility_version is that you can reject the older library at the opening stage, maybe also allowing the loader to search more paths to see if it can find the right version.
> 
> That does seem likely. Nonetheless a portable library like HTSlib has the liberty of choosing whether to accept the maintenance burden of updating compatibility_version carefully enough to enable that potential functionality on macOS or to simplify the burden by just applying the generic soversion mechanism on macOS too.

I certainly have some sympathy with that viewpoint, however I would suggest that if we don't want to carry the burdon of explicitly tracking which versions are compatible with each other we do one of two things.

1) Set both to the package release.  Ie always claim 1.10 needs >=1.10, 1.11 needs >=1.11 etc.  It's not guaranteed to be true, but it probably will be as I can't expect we've ever had a release when we didn't add at least one API and as we're not using symbol version tracking it's the next best thing.

2) If you don't want to support the notion of package version tracking and instead let the run-time linker do the missing-symbol errors as a way of spotting compatibility, then be explicit in this and don't use package versions anywhere as it just leads people up the garden path.  Just set current and compatible versions to the same constant, eg 0.

**Comment by ryandesign** [comment]
> Also `libSystem` obviously follows the Apple rule of putting the minor ABI in compatibility version but has a current version that's way ahead, showing that current version and compatibility version don't really need to be related.

I don't know how many more times I can say it, but the current version and compatibility version are most definitely intended to be related to one another. In the dyld source code, for example, the compatibility version is stored in a variable named minVersion and the current version is stored in a variable named maxVersion; hopefully that finally makes the intended relationship clear. In the case of libSystem, its current version is 1252.50.4, because Apple has followed its guidelines and increased its version every time a feature is added, and macOS has been around for 20 years so many features have been added during that time. Its compatibility version is still 1.0.0, because Apple has carefully maintained backward compatibility so that a program I compile on my system with libSystem.B 1252.50.4 could still be loaded on any earlier version of macOS with an earlier version of libSystem.B. There may be other reasons why my program wouldn't work on older systems, like relying on features introduced in newer macOS versions, but libSystem library versioning will not be a contributing factor.
