### ISSUE TITLE
Printing out bcf_float_missing not working

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [samtools/htslib#1185]
Hey there,

I'm trying to change cyvcf2, which uses htslib underneath, to print '.' in float format fields with missing values (currently it prints 'nan'). I'm doing this by setting the appropriate spots of the array to `bcf_float_missing`. However, the format field is always printed out as `2.1391e+09` and not '.' Any idea why this is happening? Or how I might go about debugging this?

Reference code is similar to 
```
bcf_hdr_t *hdr ;
bcf1_t *b ;

// ... 

// array of floats afloat, length of array size, byte string name
// set some spots of afloat to bcf_float_missing, for example
afloat[0] = bcf_float_missing ;
bcf_update_format_float(hdr, b, name, &afloat[0], size) ;

// ...

kstring_t s ;
s.s, s.l, s.m = NULL, 0, 0 ;
vcf_format(hdr, b, &s) ;
// print s
// see 2.1391e+09 not . 
```

**Comment by jmarshall** [comment]
The `bcf_update_format_*` family of functions deal with int/float/string data types so need to do some elaborate C type gymnastics. For example, `bcf_float_missing` is in fact of type `uint32_t` and should in general not be used directly.

You need to use `bcf_float_set_missing(afloat[0])` instead of `afloat[0]=bcf_float_missing`.

**Comment by LiterallyUniqueLogin** [comment]
Thank you! That works.
