### ISSUE TITLE
1.12 is an incomplete release

### ISSUE THREAD

**Issue by ghost** [samtools/htslib#1260]
Greetings, 

The tarball for release 1.12 [here](https://github.com/samtools/htslib/archive/refs/tags/1.12.tar.gz) is giving me an error on `./configure`. It is missing the cram codecs, and it looks like this is a release that moved them to a different source tree. Should the release tarballs include the codecs, or are these intentionally left out of official releases now?

**Comment by valeriuo** [comment]
Indeed, that archive file seems to be incomplete, but you should use the official [tarball](https://github.com/samtools/htslib/releases/download/1.12/htslib-1.12.tar.bz2).

**Comment by jvanalstine** [comment]
Got it thanks! Didn't know that one was official.

**Comment by jkbonfield** [comment]
If anyone knows how to prevent github from uploading its own tarballs we'd be glad to hear!  We always add our own, which is the working one, in addition to the non-functioning ones added by github.

**Comment by jvanalstine** [comment]
https://github.community/t/disable-tarball/139966

Might be relevant.

**Comment by valeriuo** [comment]
We followed up on that community thread, but there seems to be no current solution for disabling the auto-generated (incomplete) archives. However, we'll keep this issue open, in case there is new development on GitHub's part.

**Comment by ryandesign** [comment]
> If anyone knows how to prevent github from uploading its own tarballs we'd be glad to hear!

GitHub doesn't add its own tarballs. It does provide links by which you can request that GitHub generate a tarball from the repository on the fly. The generated tarballs do not include git submodules and are thus inappropriate for use by projects like htslib that require git submodules. I know of no way to prevent GitHub from displaying the links to those auto-generated tarballs. It is unfortunate that the GitHub web UI groups the links to these auto-generated tarballs with your manually-uploaded assets into a single category called "Assets". GitHub users should already understand that if a project offers a release download then that should be used instead of the auto-generated ones, but, since the GitHub web UI does not differentiate them, to help users who are not yet aware of this GitHub feature the best you could do would be to clearly explain how to access the correct tarball in the release notes that you add to each GitHub release. I see that you already do this so I don't think there's any need to keep this issue open.

> https://github.community/t/disable-tarball/139966

This link now redirects to the GitHub community main page. Here is a link to the Wayback Machine's archived version:

https://web.archive.org/web/20211209104525/https://github.community/t/disable-tarball/139966

**Comment by jmarshall** [comment]
The relevant community thread is now https://github.com/orgs/community/discussions/6003 but, as with most issues reported to them, GitHub shows no inclination to address it.

The assets list has moved between the top and bottom of release pages a couple of times, most recently returning to the bottom of the page a couple of years ago. IMHO the bulk of the “The "Source code" downloads are generated by GitHub and are incomplete as they are missing some generated files” text should be moved back to the bottom of the release notes to be alongside the list of asset links — at least for the more recent releases.

**Comment by ryandesign** [comment]
> The relevant community thread is now https://github.com/orgs/community/discussions/6003

Thanks for the pointer!

I suggest retitling the issue to better reflect what it's about, since the current title is not accurate. Something like "Auto-generated release assets are incomplete". Or, title it after the error message that a user trying to build with such an auto-generated tarball would receive, so that if they search for the error message they will find this issue. The error I get today is `sh: ./configure: No such file or directory`. I suppose by listing it in a comment, that would be enough to be found by a search.

**Comment by jkbonfield** [comment]
The original issue isn't something we can fix, so I'll close it here.  As reported above, it's tracked elsewhere (with the people that can actually fix it, unlike us).

The most recent issue reported by @ryandesign is due to cloning from git without running `autoreconf -i` to build/install the autotools assets.  I recommend reading the INSTALL notes.  It covers this amongst other topics:

https://github.com/samtools/htslib/blob/develop/INSTALL#L79-L86

> Building Configure
> ==================
>
> This step is only needed if configure.ac has been changed, or if configure
does not exist (for example, when building from a git clone).  The
configure script and config.h.in can be built by running:
>
 >   autoreconf -i

**Comment by jmarshall** [comment]
I agree that the main problem here is in GitHub's court, not HTSlib's, but there is part of https://github.com/samtools/htslib/issues/1260#issuecomment-2067536812 that IMHO could be usefully implemented by the release manager @daviesrob:

> The assets list has moved between the top and bottom of release pages a couple of times, most recently returning to the bottom of the page a couple of years ago. IMHO the bulk of the “The "Source code" downloads are generated by GitHub and are incomplete as they are missing some generated files” text should be moved back to the bottom of the release notes to be alongside the list of asset links — at least for the more recent releases.
