### ISSUE TITLE
citing

### ISSUE THREAD

**Issue by atks** [samtools/htslib#128]
How do we cite htslib?

**Comment by odelaneau** [comment]
Any news on this?
What citation do you recommend when using HTSlib API?

**Comment by jkbonfield** [comment]
Sadly we don't have a publication on htslib itself, so either use the Samtools paper (https://academic.oup.com/bioinformatics/article/25/16/2078/204688) or cite the www.htslib.org website as appropriate.

See http://www.htslib.org/doc/#publications for more specific references rather than the library as a whole.
