### ISSUE TITLE
[E::hts_idx_push] Chromosome blocks not continuous

### ISSUE THREAD

**Issue by Shicheng-Guo** [samtools/htslib#1292]
I am trying to use tabix to index eQTL data as the following, but failed with error: `[E::hts_idx_push] Chromosome blocks not continuous` any suggestion? Thanks. 

```
wget ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Schmiedel_2018/ge/Schmiedel_2018_ge_Treg_naive.all.tsv.gz
tabix -b 2 -S 1 -p vcf Schmiedel_2018_ge_Treg_naive.all.tsv.gz
[E::hts_idx_push] Chromosome blocks not continuous
tbx_index_build failed: Schmiedel_2018_ge_Treg_naive.all.tsv.gz
```

**Comment by valeriuo** [comment]
Your file is not in VCF format. So drop the `-p vcf` option and try this instead:
`tabix -S 1 -s 2 -b 3 -e 0 Schmiedel_2018_ge_Treg_naive.all.tsv.gz`

It skips the header line (`-S 1`) and sets the reference column to 2 (`-s 2`), the start coordinate column to 3 (`-b 3`) and the end coordinate column to 0 (`-e 0`), since there is none.
