### ISSUE TITLE
Can I go through all the reads in bam file using binning index in bai file?

### ISSUE THREAD

**Issue by HatakeKakaxi** [samtools/htslib#1296]
I want to go through all the reads in bam file by iterating all the regions saved in bai file in multi-thread mode, each thread holding a region. However, it seems that bin A may be a child of bin B and the region represented by A is contained in B in the UCSC binning scheme. So can I achieve my goal? And why are there many chunks in a distinct bin in the bai file?

**Comment by jkbonfield** [comment]
The many chunks is because this isn't a binary tree, but an octa-tree.  If you place reads in the smallest bin they fit in, then the parent node will have reads which span the junction of two child trees.  With 8-way splitting that means 7 junction points.

It's easy to then see that these junction points represent sparse stop-start locations.  eg:

```
+---------------------------------------+
|   ...   ..  ...   .   ..   ...   ..  .|  (parent bin with 7 chunks)
+----+----+----+----+----+----+----+----+
|....|....|....|....|....|....|....|....|  (8 child bins probably with 1 chunk each)
+----+----+----+----+----+----+----+----+ 
```

Each of those blocks of `.`s is a chunk of data with a virtual file offset.  When doing in index lookup, it's useful to know if your query range lands in one of the gaps between those chunks or not.

Similarly very sparse coverage may give multiple chunks, even at the lowest bin level.
