### ISSUE TITLE
Unchecked return values of pthread_mutex_lock

### ISSUE THREAD

**Issue by ryancaicse** [samtools/htslib#1366]
Hi, I have a suggestion about error handlings for locking. Would it be better to handle the possible errors that return from pthread_mutex_lock.

https://github.com/samtools/htslib/blob/43c127ec10d5e38c9f5b5ec3679c3745148f7c61/thread_pool.c#L95-L99

https://github.com/samtools/htslib/blob/43c127ec10d5e38c9f5b5ec3679c3745148f7c61/thread_pool.c#L201-L203

**From pthread_mutex_lock the possible causes of error return are:**

```
     EAGAIN The mutex could not be acquired because the maximum number
              of recursive locks for mutex has been exceeded.

       EINVAL The mutex was created with the protocol attribute having
              the value PTHREAD_PRIO_PROTECT and the calling thread's
              priority is higher than the mutex's current priority
              ceiling.

       ENOTRECOVERABLE
              The state protected by the mutex is not recoverable.

       EOWNERDEAD
              The mutex is a robust mutex and the process containing the
              previous owning thread terminated while holding the mutex
              lock. The mutex lock shall be acquired by the calling
              thread and it is up to the new owner to make the state
              consistent.

       EDEADLK
              The mutex type is PTHREAD_MUTEX_ERRORCHECK and the current
              thread already owns the mutex.

       EOWNERDEAD
              The mutex is a robust mutex and the previous owning thread
              terminated while holding the mutex lock. The mutex lock
              shall be acquired by the calling thread and it is up to
              the new owner to make the state consistent.

       EDEADLK
              A deadlock condition was detected.
```

**Comment by jkbonfield** [comment]
We should probably at least do a blanket error check, but most of these aren't appropriate to do anything with other than hard error.

EGAIN can only happen if we (or perhaps someone using htslib?) have a coding error I think.

EINVAL cannot happen as we don't use PTHREAD_PRIO_PROTECT.

ENOTRECOVERABLE I don't even understand how it can happen.  If it does there's nothing we can do except fail I think.

EOWNERDEAD similarly.  I don't think we could trigger it, but if so all we can do is fail.

EDEADLK (first - why listed twice?) cannot be triggered I believe (unless PTHREAD_MUTEX_ERRORCHECK  is a default status).

Then you have repeats.  Anyway we can't really handle these cases individually as there's nothing we can do to "handle" them.  Just fail!


Also, the only ones reported in the linux man page are EINVAL, EDEADLK, and EPERM.  I think all of these would be caused through programming errors rather than unexpected system issues that we'd need to guard against.

Even so, a blanket `!= 0` error check wouldn't go amiss.

**Comment by ryancaicse** [comment]
Thank you for your detailed reply.

**Comment by daviesrob** [comment]
`ENOTRECOVERABLE` and `EOWNERDEAD` can only happen on robust mutexes, which we're not currently using.  See the [pthread_mutexattr_setrobust](https://man7.org/linux/man-pages/man3/pthread_mutexattr_setrobust.3.html) man page.  It only really matters if a thread exits while holding a lock, which we shouldn't do as long as we're careful about releasing them.

So as noted above, most of these errors can't happen, and in the unlikely event that they do, we're going to be in a big mess that's not easy to recover from.  I think we should concentrate on the remaining missing checks on `malloc` etc. before we try doing anything about `pthread_mutex_lock()`.
