### ISSUE TITLE
Some erros occured during make ! such as undefined reference to `regcompA'

### ISSUE THREAD

**Issue by zahngwenda05** [samtools/htslib#1367]
I'm sorry to bother you, but I really can't to solve this problem. When I compiled and installed samtools, it occured  the below errors.Could you give me some suggest to solve it?
Thanks !The best wish to you !

```
gcc -fvisibility=hidden  -o bgzip bgzip.o libhts.a -llzma -lbz2 -lz -lm   -lcurl -lcrypto -lpthread
libhts.a(hts_expr.o): In function `eq_expr':
htslib/hts_expr.c:586: undefined reference to `regcompA'
htslib/hts_expr.c:597: undefined reference to `regexecA'
htslib/hts_expr.c:601: undefined reference to `regfreeA'
htslib/hts_expr.c:589: undefined reference to `regerrorA'
libhts.a(hts_expr.o): In function `hts_filter_free':
htslib/hts_expr.c:674: undefined reference to `regfreeA'
collect2: error: ld returned 1 exit status
make: *** [Makefile:413: bgzip] Error 1
```

**Comment by jmarshall** [comment]
It appears that you have managed to pick up [Boost's `regcomp()`/etc implementation](https://www.boost.org/doc/libs/1_78_0/libs/regex/doc/html/boost_regex/ref/posix.html) rather than an implementation provided by your platform's ordinary libc. You could fix this by adding
```
LIBS=-lboost_regex
```
to your `./configure …` command, but it would be better to fix your build to use the ordinary one instead.

(HTSlib's _configure.ac_ could check for this library in the `AC_SEARCH_LIBS(regcomp, …)` line, but as this is primarily a C++ library, it's probably not a great idea.)

You don't say what platform you're on, or why the normal libc's implementation has not been picked up. My guess would be that you have _/usr/include/boost_ or similar in a `$CPATH` or `$C_INCLUDE_PATH` environment variable, which would cause the compiler to pick _…/boost/regex.h_ instead of the ordinary libc's _…/regex.h_. The fix would be to remove that directory from these environment variables: IIRC you should be including boost headers via `#include <boost/regex.hpp>` etc anyway (i.e., with the `boost/` in the `#include` line rather than the search path).

**Comment by zahngwenda05** [comment]
Thank you for your reply . I have successfully solved this problem under your suggests. 

I used CentOS 8.3 . After reading your message, I checked my $LD_LIBRARY_PATH and $C_INCLUDE_PATH. 

`#export LD_LIBRARY_PATH=/opt/biosoft/boost/lib:$LD_LIBRARY_PATH
#export C_INCLUDE_PATH=/opt/biosoft/boost/include:$C_INCLUDE_PATH`

As you said that, I added the boost‘s libs . After mv  it out , everything goes well .

A word awakens the dreamer！Thanks again for your help.Best wish to you！

**Comment by jkbonfield** [comment]
While it's possible to add a check for `C_INCLUDE_PATH` in the configure script, or even just zero it out, I'd argue it's basically analogous to setting CC to `gcc -I/some/path`.  We shouldn't really be checking for failure to compile due to changing the compiler behaviour in a broken manner, or at least I don't view it worth the time taken to check vs the very occasional bug report.

PS. Good spot John on the cause.
