### ISSUE TITLE
Tabix support for HTTPS access

### ISSUE THREAD

**Issue by habeggel** [samtools/htslib#139]
Hi all – 

Would it be possible to add Tabix support for HTTPS access?

Thanks in advance!

**Comment by godotgildor** [comment]
I'll second the request.

**Comment by jmarshall** [comment]
See the **libcurl** branch, which will be landing in **develop** shortly.

**Comment by snarfed** [comment]
thanks for the pointer to the libcurl branch! we used it today to get a samtools build that could talk HTTPS. our use case is extracting small regions from large indexed BAM files in S3. while libcurl is still in progress, here are the gory details in case someone else finds them useful.

(cc @krishnapant2 @justincolor. #164 also looked related.)

after we got samtools built with libcurl, we tried an `s3://` URL, but that didn't work because it didn't know to also look for the `.bai` file via `s3://`:

```
./samtools view s3://[BUCKET]/xyz.bam 2:123-456
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
```

i then tried HTTPS, and with the right S3 permissions (details below), it worked:
```
./samtools view https://s3.amazonaws.com/[BUCKET]/xyz.bam 2:123-456
```

here's how i built samtools. the key was to rebase the libcurl branch onto the develop branch:

```sh
git clone https://github.com/samtools/samtools.git
cd samtools

git clone https://github.com/samtools/htslib.git
cd htslib
git checkout libcurl
git rebase develop
autoconf
./configure --enable-libcurl
make

# patch Makefile to use libcurl and our htslib
patch -p 1 <<-\EOF
	diff --git a/Makefile b/Makefile
	index 99f34cf..712c415 100644
	--- a/Makefile
	+++ b/Makefile
	@@ -25,7 +25,7 @@ CC       = gcc
	 CPPFLAGS =
	 CFLAGS   = -g -Wall -O2
	 LDFLAGS  =
	-LIBS     =
	+LIBS     = -L/usr/lib/x86_64-linux-gnu -lcurl -lssl -lcrypto
	 
	 DFLAGS=     -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_CURSES_LIB=1
	 LOBJS=      bam_aux.o bam.o bam_import.o sam.o \
	@@ -84,7 +84,7 @@ all: $(PROGRAMS) $(BUILT_MISC_PROGRAMS) $(BUILT_TEST_PROGRAMS)
	 
	 
	 # Adjust $(HTSDIR) to point to your top-level htslib directory
	-HTSDIR = ../htslib
	+HTSDIR = htslib
	 include $(HTSDIR)/htslib.mk
	 HTSLIB = $(HTSDIR)/libhts.a
	 BGZIP  = $(HTSDIR)/bgzip
EOF

make

# now use the ./samtools binary!
```

i added this bucket policy to our S3 bucket to allow our EC2 instances in a VPC to read from it over HTTPS, without any other creds.

```json
{
	"Version": "2012-10-17",
	"Id": "[...]",
	"Statement": [
		{
			"Sid": "[...]",
			"Effect": "Allow",
			"Principal": "*",
			"Action": "s3:*",
			"Resource": "arn:aws:s3:::[BUCKET]/*",
			"Condition": {
				"StringEquals": {
					"aws:sourceVpc": "[VPC ID]"
				}
			}
		}
	]
}
```

**Comment by jmarshall** [comment]
HTTPS is now supported (on the **develop** branch; see #292) when you configure htslib with `--enable-libcurl`.

@snarfed, the _didn't work because it didn't know to also look for the .bai file via s3://_ thing should work now, as now that the plugin support is complete, `hisremote()` knows about all the URL schemes — including _s3://_.  Using that instead of plain HTTPS, you won't need to hack your bucket permissions.

To build samtools against current htslib **develop** configured with `--enable-plugins --enable-libcurl`, you now just need `make LDFLAGS=-rdynamic LIBS=-ldl` (and probably to have configured htslib's plugin path to something sensible). This too will go away with a sufficient sprinkling of pkg-config and/or configure…

**Comment by snarfed** [comment]
that's great news, thanks @jmarshall! cc @krishnapant2 @justincolor

**Comment by jmarshall** [comment]
Thanks @snarfed for trying it out, and please let us know (as new issues) if you run into more rough edges.  See also #232: we plan to also support reading credentials from ~/.aws/credentials and ~/.awssecret, and $AWS_SESSION_TOKEN and temporary security credentials.

**Comment by shubhamLondhe** [comment]
Hello, i am facing some issues in using tabix against the url I created using aws s3 presign, I have 2 s3 buckets, tabix works fine for the open s3 bucket but for the one which  is secured, tabix doesnt give output. it says file not found.

**Comment by daviesrob** [comment]
@shubhamLondhe Please could you open a new issue instead of reviving this ancient one.

Also, you may want to try the `develop` branch of htslib (if you haven't already) as it understands AWS version 4 signatures and should work with more endpoints than htslib 1.9.
