### ISSUE TITLE
bgzf_seek fails for seeks > 65296?

### ISSUE THREAD

**Issue by fnevgeny** [samtools/htslib#1392]
```C
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <htslib/bgzf.h>

int main(int argc, char **argv)
{
    int c, res;

    assert(argc == 3);

    BGZF *fp = bgzf_open(argv[1], "r");
    assert(fp != NULL);

    res = bgzf_seek(fp, atol(argv[2]), SEEK_SET);
    assert(res >= 0);

    printf("position is %ld\n", bgzf_tell(fp));

    c = bgzf_getc(fp);
    printf("read char '%c'\n", c);

    exit(0);
}

```
```
$ zcat /tmp/a.dat.gz | ( dd status=none skip=65200 count=1 bs=1 ; echo )
6
$ zcat /tmp/a.dat.gz | ( dd status=none skip=65296 count=1 bs=1 ; echo )
0
$ zcat /tmp/a.dat.gz | ( dd status=none skip=65297 count=1 bs=1 ; echo )
3
```
```
$ ./tz /tmp/a.dat.gz 65200
position is 65200
read char '6'
$ ./tz /tmp/a.dat.gz 65296
position is 65296
read char '0'
$ ./tz /tmp/a.dat.gz 65297
position is 65297
read char ''
```
(the test file was produced with bgzip). Am I missing something obvious?

**Comment by daviesrob** [comment]
This is because the value returned by `bgzf_tell()` and taken by `bgzf_seek()` is a [virtual file offset](https://samtools.github.io/hts-specs/SAMv1.pdf#subsubsection.4.1.1).  It combines the position of a block in the compressed stream with an offset into that block.  `bgzf_seek()` will seek to the indicated block, read it and then discard data until it gets to the desired offset. In your last example, you were pointing at the first block, but presumably discarded everything inside it.

In general it's not a good idea to `bgzf_seek()` to a location unless it was originally returned by a call to `bgzf_tell()` when reading the same file.

**Comment by fnevgeny** [comment]
Sorry, I'm confused. First, I'd expect that if `bgzf_seek()` in a particular situation is unable to fulfill its promise, it should return an error, but it doesn't (see `assert()`). More importantly, I still don't understand how to use random seek in a compressed file using the library. Please note that I don't use any predefined format like BAM. Do you say that the BGZF API is not usable for a generic b**g**zip-compressed file, even with an index generated?

**Comment by fnevgeny** [comment]
Thanks, I'll have a look at these APIs soon. Just had to put the whole project aside for a while.
