### ISSUE TITLE
hts_parse_decimal() silently fails on non-numeric strings starting with G

### ISSUE THREAD

**Issue by pd3** [samtools/htslib#1395]
The function does not reject strings like `G A`, thinking it was able to parse a coordinate due to https://github.com/samtools/htslib/blob/1c8829a9a189004c6229bab923753aa5569cff0c/hts.c#L3513

This leads to problems reported in https://github.com/samtools/bcftools/issues/1598 where region format is autodetected by first attempting to read `chr beg end` and, upon failure, reads `chr pos`. One relevant part of code that can be mislead by this is https://github.com/samtools/htslib/blob/1c8829a9a189004c6229bab923753aa5569cff0c/synced_bcf_reader.c#L1126-L1130

**Comment by jmarshall** [comment]
Indeed, it shouldn't be recognising `G` as 0 gigabases/gigabytes; those suffixes should require some digits first, e.g. `1G`.

I think it would be appropriate to only do the E and K/M/G processing if a non-zero number of digits have been seen. Or pretty much equivalently, by wrapping `if (s > str)` around this processing.

`1e+3k` doesn't seem good to accept, so I would suggest merging the E/e processing into the `switch`, so that only one instance of any of E/K/M/G is accepted.

**Comment by pd3** [comment]
I issues a pull request here https://github.com/samtools/htslib/pull/1396.

Although expressions like `1e+3k` are ambiguous, `(1e3)k` vs `1e(3k)`, I don't mind those as much as they are interpreted the expected way `(1e3)k`.
