### ISSUE TITLE
[E::hts_idx_push] Chromosome blocks not continuous for gnomad.tsv.gz

### ISSUE THREAD

**Issue by tcwong1994** [samtools/htslib#1412]
Hello, I am trying to tabix a gnomAD tabbed tsv.gz, but the error "[E::hts_idx_push] Chromosome blocks not continuous" popped up.

I followed this [guideline](https://github.com/Ensembl/VEP_plugins/blob/release/105/gnomADc.pm) to format the source file `gs://gcp-public-data--gnomad/release/3.0.1/coverage/genomes/gnomad.genomes.r3.0.1.coverage.summary.tsv.bgz` into `gnomad.genomes.tabbed.tsv.gz`. 

I then ran the command: `tabix -s 1 -b 2 -e 2 gnomad.genomes.tabbed.tsv.gz`. It took > 2 hours to run tabix before throwing up the error.

Here are the first few lines of the `gnomad.genomes.tabbed.tsv`:
```
#locus	mean	median_approx	total_DP	over_1	over_5	over_10	over_15	over_20	over_25	over_30	over_50	over_100
chr1:10001	2.4117e+00	0	172926	0.12482218	0.118518315	0.09123874	0.06953781	0.051476948	0.038841315	0.026205685	0.0022732979	0.0
chr1:10002	4.6130e+00	0	330760	0.22010544	0.21497308	0.17945106	0.13896404	0.10231235	0.076009035	0.050626203	0.004825528	2.7893224E-5
chr1:10003	6.3821e+00	0	457611	0.2620429	0.25947672	0.24101141	0.206633	0.15918663	0.118016236	0.07769658	0.0076148505	5.5786448E-5
chr1:10004	1.0388e+01	0	744840	0.42676634	0.4240328	0.39926362	0.3434632	0.2595883	0.18699618	0.12119606	0.01202198	1.6735935E-4
chr1:10005	1.1847e+01	0	849441	0.48274803	0.48008424	0.4556916	0.39198348	0.29622605	0.21359237	0.13842013	0.014211598	2.370924E-4
```

May I know how to troubleshoot to see if the source file format is problematic? Thank you very much!

**Comment by daviesrob** [comment]
The problem is that the file you downloaded has a different format to the one in the guidelines you linked to.  That one was `https://storage.googleapis.com/gcp-public-data--gnomad/release/2.1/coverage/genomes/gnomad.genomes.coverage.summary.tsv.bgz`, which looks like this:
```
#chrom	pos	mean	median	over_1	over_5	over_10	over_15	over_20	over_25	over_30	over_50	over_100
1	10001	6.6013e+00	6	9.8698e-01	6.6640e-01	1.8714e-01	5.0448e-02	1.2205e-02	4.8820e-03	1.6273e-03	0.0000e+00	0.0000e+00
1	10002	9.4418e+00	8	9.9593e-01	8.4947e-01	4.0277e-01	1.4483e-01	5.2889e-02	2.4410e-02	7.3230e-03	0.0000e+00	0.0000e+00
1	10003	1.2810e+01	11	9.9837e-01	9.4223e-01	6.5338e-01	3.1082e-01	1.3263e-01	6.4280e-02	3.1733e-02	1.6273e-03	0.0000e+00
```

Compared with the newer file, the  `chrom` and `pos` columns have been changed to a single `locus` one, `median` has changed to `median_approx` and there's also a new `total_DP` column.    So the `tabix` command you used won't work on the newer file as it's interpreting each locus as a new chromosome and trying to use the `mean` value as the position.  Unfortunately the new format is incompatible with `tabix` as it currently has no way of splitting the `locus` column up.  I think your best option would be to reformat the file you downloaded into the format expected by the VEP plugin.  Using this perl 1-liner in place of the `sed` command in the instructions should do the trick, I think:

```
perl -lane 'if ($F[0] eq "locus") { $F[0] =~ s/locus/chrom\tpos/; $F[2] =~ s/_approx//; } else { $F[0] =~ s/(.*):(\d+)/$1\t$2/; } splice(@F, 3, 1); print join("\t", @F);' gnomad.genomes.r3.0.1.coverage.summary.tsv | bgzip > gnomad.genomes.tabbed.tsv.gz
```

You should also raise an issue on https://github.com/Ensembl/VEP_plugins to ask them to update their plugin and instructions to be compatible with newer gnomAD releases.

**Comment by tcwong1994** [comment]
@daviesrob Thanks for your help! I could tabix the file. Two minor points - "#" is required on the first line and "-c" needs to be specified for bgzip to read stdin. So I used this command instead:

`perl -lane 'if ($F[0] eq "locus") { $F[0] =~ s/locus/#chrom\tpos/; $F[2] =~ s/_approx//; } else { $F[0] =~ s/(.*):(\d+)/$1\t$2/; } splice(@F, 3, 1); print join("\t", @F);' gnomad.genomes.r3.0.1.coverage.summary.tsv | bgzip -c > gnomad.genomes.tabbed.tsv.gz`

Will raise this issue on VEP_plugins too. Thanks again!
