### ISSUE TITLE
An error " Could not write 32768 bytes: Error 0" while running bgzip 

### ISSUE THREAD

**Issue by se2cheeese** [samtools/htslib#1425]
Hi, 
I was trying to uncompress gzip file "${i}.gz" (around 6TB size) and bgzip it. 
After 3 days of running it finally ended up with the following error:
"Could not write 32768 bytes: Error 0"

My command was as below. 
gzip --decompress --to-stdout ${i}.gz \
  | bgzip --index --index-name ${i}.bgz.tbi -@256 \
  > ${i}.bgz

Could you help me find out what the problem is? 

Thank you in advance.

**Comment by jkbonfield** [comment]
Error 0 isn't exactly helpful.  It seems to come from bgzip.c:

```
                if (bgzf_block_write(fp, buffer, c) < 0) error("Could not write %d bytes: Error %d\n", c, fp->errcode);
```
Errcode gets set in bgzf.c, but in this case apparently not.  It's hard to track all the paths to work out how `bgzf_block_write` could return < 0 without setting an error code.  One possible case though is an issue in the threading library - unable to launch threads or something being killed off?  `-@256` is quite extreme, especially given it'll almost certainly be bottlenecked on the input non-threaded `gzip -d` process, but it still shouldn't error.

I know you don't want to hear this given it took 3 days!  However I cannot think of an obvious cause.  Perhaps there will be some tell-tale signs in the system logs; try `dmesg` to check.  You may also wish to edit the bgzip.c source to amend the printing of that error message to print up `errno`.  Eg:

```
                if (bgzf_block_write(fp, buffer, c) < 0)
                    error("Could not write %d bytes: Error %d, %s\n", c, fp->errcode, strerror(errno));
```

(Note this error can be printed in two places, both near each other.)  It's possible it died due to a system issue, suich as running out of disk space or out of quota, in which case the system errno will be meaningful.  Or perhaps it's something unexpected like a failure to allocate memory for the index being built.  I'm not sure we've ever tested bgzip indices on files that large!  It should work, but without testing it's hard to be 100% certain.

Some hints also for speeding up the process.  Add in `mbuffer` too to provide some level of disconnect between the gzip pipe and the multi-threaded encoder.  Also pick fewer threads (maybe benchmark a smaller file to work out what's best). Eg:

```
gzip -d < ${i}.gz | mbuffer -q | bgzip --index --index-name ${i}.bgz.tbi -@32
```

**Comment by se2cheeese** [comment]
Thank you very much for your kind advice. I've split the file and am trying it again.

**Comment by Jesson-mark** [comment]
Hi, I encountered the same message but without "Error 0" information. 
After some tests, I figured out the codes to reproduce this message (Could not write 65536 bytes):

```
a_compressed_file=test.tsv.gz
bgzip -dc $a_compressed_file | head -1 > header.txt
```

I modified the source code of `bgzip.c` and the message turns out to be "Could not write 65536 bytes. Error info: Broken pipe". 
It seems that this message is originated from the broken pipe. When I used `gzip` instead of `bgzip`, it gives the same message "gzip: stdout: Broken pipe". 

However, even if there is the message, the contents are accurate. 
Due to the concern that in some instances it may produce wrong results, do you have any idea about how to handle this message?

Sincerely, 
Jie Wang.

**Comment by jkbonfield** [comment]
It's normal for broken pipes to trigger error messages like this, although it's the overly detailed error from bgzip which is causing confusion I think.  Gzip is less alarmist, but it essentially means the same thing.  From an strace of gzip:

```
write(1, "%\1\0\0\0\0\0\0002\256\1\0 \0O\22\1\0c\0d\0\0\0\0\0\0\0\7\257\1\0"..., 32768) = -1 EPIPE (Broken pipe)
```

It's simply not reporting the failure to write 32768 bytes.

The one thing I find odd though is that we report Error 0 instead of EPIPE, which would be more instructive and less worrying as it's something expected.
