### ISSUE TITLE
golang bindings

### ISSUE THREAD

**Issue by matthdsm** [samtools/htslib#1471]
Hi,

I'm not sure if this is the right place to ask, but here I go anyway.
We'd like to have a robust go package that binds to htslib, so we're able to leverage all the goodness that it brings. AFAIK the only packages available now are homebrew, native go implementations.

Questions are:
- Are you aware of a htslib interface for go?
- If not, how involved would this be for a (somewhat) junior developer with very limited experience in go? Do you think this is manageable or should we stick with something else?

Thanks
M

**Comment by jkbonfield** [comment]
It turns out that searching for "go" bindings is impressively hard due to the minimal language name.  I'm not aware of any bindings though, just reimplementations in Go itself (eg biogo/hts).

As for how hard it would be, I have no idea as I'm not a Go developer.  Best to ask another language binding author perhaps, such as those who wrote the Rust, R, and Python interfaces.  They'd have a better grasp on how big a task it is.

**Comment by brentp** [comment]
There is one here: https://github.com/biogo/boom
I think it'd need a bit of updating, but it's quite high quality as is all of Kortschak's stuff.

**Comment by matthdsm** [comment]
Thanks for the tip! I'll look into it.
