### ISSUE TITLE
Installation on mac

### ISSUE THREAD

**Issue by akr55** [samtools/htslib#1540]
I have tried with homebrew, conda and base computer to install htslib, no matter what I do it shows up as htsfile in /usr/bin, but it always says no such file htslib. Is there a straightforward way to install htslib on a mac and make sure that it works?

**Comment by jkbonfield** [comment]
I expect you already have it installed via another route, if you keep finding htsfile in /usr/bin.  That will be in your PATH before other directories probably.  You'll need to modify your PATH to see another location (eg the conda install bin) as the first thing in the path in order to override any system installed packages.
