### ISSUE TITLE
Cannot install htslib in Python 3.10 conda environment because of OpenSSL

### ISSUE THREAD

**Issue by sjdv1982** [samtools/htslib#1578]
The bioconda htslib packages require OpenSSL 1.1 (in case of htslib 3.9, implicitly).

However, Python 3.10 requires OpenSSL 3:

`package python-3.10.9-he550d4f_0_cpython requires openssl >=3.0.7,<4.0a0, but none of the providers can be installed`

**Comment by jkbonfield** [comment]
I'm not aware of htslib requiring a specific version of openssl.  Indeed compiling from source htslib works fine with the system openssl on our Ubuntu system, and python 3 is using that same library too.

So I suspect this is another overly strict dependency added incorrectly by bioconda.  I couldn't find any specific pinning of version numbers though at https://github.com/bioconda/bioconda-recipes/blob/master/recipes/htslib/meta.yaml, but probably best to raise the issue on their github as we don't maintain the conda packages ourselves.

**Comment by sjdv1982** [comment]
Hmm, I ran into the issue when I tried to run bcftools:

bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot
open shared object file: No such file or directory

Since bioconda lists no dependency bcftools -> openssl, but it does list
bcftools -> htslib -> openssl, I though the issue must be with htslib. It
seems I was wrong?

**Comment by jkbonfield** [comment]
The software does build and execute from source, as our continuous integration tests do this for every commit.  That includes building and testing bcftools.  If it's failing within a prepackaged install then the problem is highly likely due to that packaging, or attempting to do a hybrid of conda and source together which we don't support.

You're correct that bcftools depends on htslib and htslib on openssl, but if your htslib is bundled by someone else then that's initially where you should ask for assistance (regarding libraries and environment - of course algorithmic things are down to us).

**Comment by sjdv1982** [comment]
Ok, thanks for the clarification. I will take it up with the maintainers.
cheers
Sjoerd

**Comment by jmarshall** [comment]
This is bioconda/bioconda-recipes#39356.

**Comment by jkbonfield** [comment]
Oh so it's a bioconda vs conda-forge thing.  That explains why I couldn't find any mention of a specific pinned openssl in the bioconda htslib recipe.  Thanks John.

As I use it so rarely I always stumble on the different moving parts and which bit fits with which.  Such a can of worms!
