### ISSUE TITLE
Loosing precision due to avoidable rounding of float annotations in VCF

### ISSUE THREAD

**Issue by vruano** [samtools/htslib#1695]
We are handling VCF files that have a float INFO annotation that usually has values on the low 'ints' e.g. from 0.0 to say 10.0  (It is an estimate of gene copy number  if you want to know)

Some of the records in the input VCF should be passed thru to the output without changes whereas some others need to be changed somewhat. Amongst those pass thru records, there is one with such annotation taking a value of 3.618826 which when loaded into memory as 32bit float no precision is lost (cast to double it becomes 3.618825912475586). 

However htslib (thru pysam) when outputting vcf you get 3.61883 != 3.618826. 

It turns out that `vcf_format` calls `kputd` that in turn uses the equivalent of a  `sprintf("%g", val)` call to produce the output with a fix default precision of 6 (not sure if it is significant digit or decimal). It seems that for this value range "%f" would be more appropriate option as it uses the float's type spec precision as a default instead. 

I know this might all sound a bit pedantic as usually in practice this differences are negligible but makes VCF comparisons between releases  more difficult  and perhaps more importantly they are difficult to justify to non-bioinformatic stakeholders that don't see the reason why we could simply "copy the input text line" for those pass thru records.

**Comment by jkbonfield** [comment]
We discussed this in our weekly meeting and concluded that comparisons of floating point numbers without some approximation component is always going to be problematic.  For example large numbers like 36188261 get turned into "3.61883e+06" with %g.  Htsjdk is I think using double, so there's no guarantee that tools are going to write out text values to any specific number of digits, and some may write out numbers to more significant digits than float can even store.  Such things are valid VCFs as the specification simply defines the limits (FLT_MIN/MAX) accepted and doesn't have anything to say on the representation other than capitalisation of exponents.

People could write a VCF with "1e-1" or "0.1" or "0.10" and all be valid and identical.  You'd see this if you changed from %g to %f.  Eg:

| Value | %f | %g |
| - | - | - |
| 0.0001 | 0.000100 | 0.0001 |
| 0.00001 | 0.000010 | 1e-05 |
| 5 | 5.000000 | 5 |

So this switch would make some things round trip better and a vast array of other things round trip worse.  Even if it become round-trippable for VCF, we would break round-tripping with other packages.

It's possible we could improve things with say `%.7g` (I'm not sure what the correct value is, but float is 31-bit + sign and log(2^31)/l(10) is 9.3 decimal digits, but it's probably the size of mantissa that matters with 23-bit = 6.9 decimal digits worth), but it will never be possible to round-trip every input file due to the aforementioned non-uniqueness of specifying identical data.

Given that, it feels excessive to add bloat to every VCF file in the world solely for the purposes of papering over what is, fundamentally, a bad way of checking for identity and round-tripping, so the group decided to do nothing for now unless a better case can be made for this requirement.

**Comment by jkbonfield** [comment]
We discussed this in the working group and concluded changing this probably isn't justified given it makes all the files a bit bigger for what is very little actual benefit and the fix would need more work to validate that it doesn't break other things (as the suggested `%f` would).  The fidelity of these numbers is almost certainly already way lower than the perceived precision as listed in VCF right now.

So closing sorry.  If you feel you can make a stronger case then please comment.
