### ISSUE TITLE
formerly caught bgzf_idx_amend_last symbol

### ISSUE THREAD

**Issue by emollier** [samtools/htslib#1722]
Greetings,

I'm trying to bump the htslib suite to version 1.19 in Debian sid, and symbols tracking caught the drop of the bgzf_idx_amend_last function.  As far as I understand, this function was not supposed to be part of the ABI in the first place, given its declaration in hts_internal.h.  Besides, running the test suites of the many reverse dependencies, without rebuilding them first, does not raise any ill effects (except perhaps cyvcf2, which seems to have a test item failing to write VCF4.1 files properly, but as far as I can see, it is unrelated to the missing symbol).  So the function does not look to have made it to the ABI by accident to consumers of the htslib.

Just checking, may I go ahead with the missing symbol without soversion bump, or was the drop actually unintended?

Have a nice day,  :)
Étienne.

**Comment by emollier** [comment]
Nevermind the parenthesis about cyvcf2 test failure, there is work in progress on their side to get the code compatible with htslib 1.19; see https://github.com/brentp/cyvcf2/pull/290.

**Comment by daviesrob** [comment]
Yes, it was dropped deliberately in PR #1672, although it looks like I forgot to remove the prototype from `hts_internal.h`.  It's not part or the ABI, and should not have been exported in the `.so` file (at least after we tidied up the exports in #946 for release 1.10).

Since PR #1560, htslib has symbol versioning via [`htslib.map`](https://github.com/samtools/htslib/blob/develop/htslib.map), which should make tracking ABI changes a bit easier.

**Comment by emollier** [comment]
Hi Rob,
Thank you for the clarification, that makes sense to me.
Have a nice day,  :)
Étienne.
