### ISSUE TITLE
CRAM and BAM remote index behaviours in iRODS differ (htslib 1.2.1)

### ISSUE THREAD

**Issue by keithj** [samtools/htslib#176]
````
$ ils
  toy.cram

$ ./samtools index irods:toy.cram

$ ils
  toy.cram

$ ls
irods:toy.cram.crai
````

~~An analgous situation exists for bam files.~~

**Comment by jmarshall** [comment]
A resulting `samtools view irods:toy.cram 1:1000-5000` will use the index file that has been created, no?

HTSlib does the same thing over HTTP, creating a file named _http:fred.bam.bai_ for use with _http://host/path/to/fred.bam_.  So I'm not sure that it's malformed as such, so much as a wacky design choice that we may wish to revisit...

**Comment by jkbonfield** [comment]
On Mon, Feb 09, 2015 at 06:55:45AM -0800, John Marshall wrote:
> A resulting `samtools view irods:toy.cram 1:1000-5000` will use the index file that has been created, no?

I think the main point is that it uses zfopen (wrapped around fopen)
instead of hopen and so always generates local filenames rather than
on irods.

It ought to be a trivial change to get it to use the hfile interface
instead.  Indeed I thought I'd done this already, but it was probably
another part of cram (ref maybe?).

I'll investigate anyway.

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by keithj** [comment]
I was surprised by the renaming. Now that I undertstand, I can see that it is working correctly
for BAM files. If the BAM file is remote, but not local, it downloads it from iRODS. If it is local, but not
remote, it uses the local. The local copy has the prefix.

However, cram is not behaviing the same way. Given the files described above, having indexed the cram file:

```
$ ./samtools view irods:toy.cram 1:10

irods:toy.cram.crai: No such file or directory
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
````

However, if I put the index into iRODS:

````
$ iput irods:toy.cram.crai toy.cram.crai
$ ./samtools view irods:toy.cram 1:10
r001    163     ref     7       30      8M4I4M1D3M      =       37      39      TTAGATAAAGAGGATACTG      *       XX:B:S,12561,2,20,112   MD:Z:12^G3      NM:i:5
r002    0       ref     9       30      1S2I6M1P1I1P1I4M2I      *       0       0       AAAAGATAAGGGATAAA        *       MD:Z:10 NM:i:8
r003    0       ref     9       30      5H6M    *       0       0       AGCTAA  *       MD:Z:2A3NM:i:6
````

I'm finding that for BAM I can use either a local or remote index, but for CRAM I can use only a
remote one (in iRODS) which will not get downloaded.

**Comment by jkbonfield** [comment]
See https://github.com/samtools/htslib/pull/178 for changes to the CRAM index loading.

It now appears to behave in the exact same was that .bai does. (Note, only tested on irods: files and local files).
