### ISSUE TITLE
fatal error: curl/curl.h: No such file or directory     

### ISSUE THREAD

**Issue by sawma-k** [samtools/htslib#1793]
even though i have installed libcurl and curl i still get these errors 
 'fatal error: curl/curl.h: No such file or directory'
     . Can somebody help me

**Comment by jkbonfield** [comment]
Did you run ./configure?  If so it should say in the output whether it found a working libcurl.

```
checking for curl/curl.h... yes
checking for curl_easy_pause in -lcurl... yes
```

If not, you can look in config.log.  It should have something like this:

```
curl/curl.h
configure:5690: gcc -c  -Wall -g -O2 -fvisibility=hidden -I/nfs/users/nfs_j/jkb/ftp/compression/libdeflate conftest.c >&5
configure:5690: $? = 0
configure:5690: result: yes
configure:5699: checking for curl_easy_pause in -lcurl
configure:5724: gcc -o conftest  -Wall -g -O2 -fvisibility=hidden -I/nfs/users/nfs_j/jkb/ftp/compression/libdeflate -L/nfs/users/nfs_j/jkb/ftp/compression/libdeflate -Wl,-R/nfs/users/nfs_j/jkb/ftp/compression/libdeflate -fvisibility=hidden conftest.c -lcurl  -ldeflate -llzma -lbz2 -lz -lm  >&5
configure:5724: $? = 0
configure:5733: result: yes
```

I'm assuming you're getting an error in there somewhere.

If you didn't use configure, then please consider switching to it instead of just using "make" as-is.

**Comment by Sha-Dox** [comment]
migger
