### ISSUE TITLE
tabix 1.17 v 1.20+ 

### ISSUE THREAD

**Issue by mike2vandy** [samtools/htslib#1841]
This is awkward and I'm sorry if this has been answered before. I've been adding ID information to a vcf from a tab delimited file that looks like

```
#CHROM  POS     ID
NC_058368.1     112     NC_058368.1_112
NC_058368.1     7637    NC_058368.1_7637
NC_058368.1     7671    NC_058368.1_7671
```
I tabix this file to use it for bcftools annotate
```
tabix -p vcf ids.tab.gz 

bcftools annotate --force -Oz -c CHROM,POS,ID -a ids.tab.gz vcf.gz
```

Historically htslib/tabix (i.e. 1.17) works fine. 

but tabix v1.20 + gives an error like: 
```
[E::hts_idx_push] Invalid record on sequence #1: end 1 < begin 112
tbx_index_build3 failed: annot.tab.gz
```
What's changed between versions? Have my ID annotation lines become outdated?

**Comment by whitwham** [comment]
The change that makes it not work was in 1.18.  For some reason it doesn't like the REF field not being there.  I am not sure yet which change causes this not to work.

**Comment by jmarshall** [comment]
The behaviour changed in 90af5ee56f84779d27a03fa2aaa59a6bd4ee90cf, which did not account for the 0 sentinel value of `conf->ec` as used in `tbx_conf_vcf`. But as that sentinel value signals special handling for `intv->end` the new behaviour is arguably more correct.

However the real problem is that you are using `tabix -p vcf` with a file that is not VCF at all, which worked only by luck previously. As you have specified VCF, the genomic interval end position is calculated based on the value of REF (and INFO/END if present) — but your file doesn't have those fields, so `end` remains unset.

This will work better if you index the file based on the fields it actually has, e.g. with `tabix -s1 -b2 -e2`.

**Comment by whitwham** [comment]
@mike2vandy does @jmarshall suggested tabix command work for you?

**Comment by mike2vandy** [comment]
Sorry for the delay. Yes that change to the tabix line worked. Thank y'all for looking into it.
