### ISSUE TITLE
specify CRAM output format

### ISSUE THREAD

**Issue by ekg** [samtools/htslib#196]
I've [followed this pattern to configure different output formats for a hts file](https://github.com/ekg/vg/blob/c0b6cf70aaf2c4468e0005a517c4264c9e19ffbc/main.cpp#L188-L200) but I find that I can only output BAM, even if I set the output type to `c`.

Is there an obvious problem with how I'm using the API here? I think it's likey to be another programming problem on my end, but any other examples of how to do this using the API would be very helpful. I basically copied and pasted from sam_view.

**Comment by dpryan79** [comment]
I imagine that using hts_set_fai_filename() might be useful, though I don't know that it will resolve the problem.

**Comment by jmarshall** [comment]
Your default `compress_level` is triggering line 194.

However coming up with a better API to specify file formats and flavours is something we need to come up with soon.  One thought is to add something like `hts_open_fmt(const char *filename, const htsFormat *format)` so that you can specify format, compression level, etc in a C structure rather than encoding it into a string.  (It might need a `mode` parameter too just for `r`/`w`, though really it's only of interest for `w`...)

**Comment by ekg** [comment]
So it looks like I will need to use `hts_set_fai_filename()` in order to get the cram output to work. Seems I was masking the problem previously.

**Comment by ekg** [comment]
@jmarshall And I strongly support a single call using a C struct for options.

**Comment by jmarshall** [comment]
This will be addressed by PR #233.

**Comment by jkbonfield** [comment]
#233 has now been merged so closing this.

Please reopen this if you still have problems.  Thanks.
