### ISSUE TITLE
BGZF/gzip interoperability

### ISSUE THREAD

**Issue by mdshw5** [samtools/htslib#198]
I know that block gzip compressed streams can be fed to GNU gzip and decompressed with no issue. However, I recently discovered that GNU gzip compressed streams cannot be decompressed using `bgzip`. Is this by design? Is there anything limiting the `bgzip` binary from becoming a drop-in replacement for GNU gzip in any application where you would like BGZF?

**Comment by jmarshall** [comment]
BGZF format is a special case of GZIP format, so it would not be surprising if `bgzip -d` did not work with plain gzipped files.  Being specialised to work with BGZF files, `bgzip` would be justified in expecting to see BGZF extras when processing a compressed file.  (Whereas vice versa is a different kettle of fish: `gzip` should work fine decompressing a BGZF file, because a BGZF file really is just a (particular flavour of a) GZIP file.  Modulo well-known bugs in Java gunzip implementations, etc.)

Having said that, it works for me with bgzip 1.0, 1.1, and 1.2.1.  So in fact **decompression** apparently does not depend on the BGZF extras, which is also not too surprising and an ability that we can probably [commit to maintaining](https://github.com/samtools/htslib/blob/26229a368e3045a827f04fc03f3879e25f110ba3/NEWS#L40).

Perhaps you are using an older `bgzip` that predates 165850e14af322eedf0c1d9207f4acc771970577?

**Comment by mdshw5** [comment]
> Perhaps you are using an older bgzip that predates 165850e?

Yes, that was actually the problem. I've just tested with bgzip 1.0 and the behavior is exactly what you describe. I would be a +1 for maintaining the current behavior, as it's very handy to assume the API of bgzip == gzip for most tasks.

**Comment by wookietreiber** [comment]
Maintaining they work the same: Unit tests!
