### ISSUE TITLE
Add hts_opt for filesystem block size

### ISSUE THREAD

**Issue by jkbonfield** [samtools/htslib#216]
hfile_init takes a blocksize which for filesystems is returned via struct stat.st_blksize.   Unfortunately some filesystems are just broken.  E.g. lustre sometimes recommends 4Kb as its blocksize, which is (was?) totally wrong as it prefers around 1Mb.  Maybe this has changed, but it warrants testing.

We could add an option to use via the --input-fmt-option and --output-fmt-option parameters that allows manual control over the block size.  This would also allow for a way to override the hacked 32768 limit in hfile_init(), put in place to prevent large scale merging and mpileup from consuming too much memory.

Whether it really makes any difference I don't know.

... edit - tested! ...

32K block size on lustre: 49.6sec to read ~3Gb via samtools.
2Mb block size: 47.7 sec. 

Minimal, but still a difference.

**Comment by wookietreiber** [comment]
:+1: for such an option. File systems used by HPC clusters usually are parallel file systems (Lustre, BeeGFS, GPFS, ...) that are not local but provided by some kind of network. In this case, it is much more preferable to have fewer larger I/O requests than to have lots of small ones, not to mention that the block size of these file systems increases with the size of the cluster and its storage. I have heard people speak at the International Supercomputing Conference who are using block sizes of 16 Megabytes and that was two years ago (remember Moore's law?). Shooting at such a file system with 4K I/O requests is just ... well ... don't do it ;)

On the verge of going HPC, a lot of software I have seen (especially bioinformatics software, and I am an HPC cluster admin, not a user, so I know all the *I/O bad boys* out there ;) ) suffers I/O-wise from the fact that it was developed on notebooks with SSDs (or more general: local storage) and just does not perform on the parallel file systems on HPC clusters because what @jkbonfield suggested has not (properly) been considered and implemented. One of the worst cases we experienced was that our parallel file system just broke down under the I/O load of a few tophat jobs that *just used a too small block size for reading files*.

The approach to solve this I am considering most at the moment is to have HPC cluster admins thoroughly test their particular cluster (each one is different / differently configured) and recommend their users the resulting optimal I/O block size (which may or may not be different from the one set in the file system configuration because of others factors like network configuration). Probably even separate block sizes for reading and for writing. These values could be recommended in the cluster user documentation. However, each user would need to set this manually in their job scripts and this gets kinda annoying for users and will never be fully enforced. Thus, what I would recommend at the moment, is to not only provide the possibility to configure the I/O block size via command line parameters but also via environment variables. This way, cluster administrators can set these environment variables *globally* and whatever application is used can pick that up. This is much more convenient for the users because they don't need to set it in each and every job script, it can be somehow enforced, etc. To make this approach more viable beyond the scope of samtools/htslib I would even recommend a more general name for the environment variable than maybe `HTS_BLOCK_SIZE` but name it `IO_BLOCK_SIZE` and point the devs of other software to this approach and convince them to use it as well. This would be amazing.
