### ISSUE TITLE
it is not possible to safely use htslib in a static executable

### ISSUE THREAD

**Issue by ekg** [samtools/htslib#259]
I'd like to compile `vg` as a static binary, but I can't because of an interesting dependency problem.

If I try to make a static executable with `g++` and `-static` like so,

```text
g++ -O3 -std=c++11 -fopenmp -g  -o vg gssw_aligner.o vg.o cpp/vg.pb.o main.o index.o mapper.o region.o progress_bar/progress_bar.o vg_set.o utility.o path.o alignment.o edit.o sha1/sha1.o json2pb.o entropy.o -I./ -Icpp -Ivcflib/src -Ivcflib -Ifastahack -Igssw/src -Iprotobuf/build/include -Irocksdb/include -Iprogress_bar -Isparsehash/build/include -Ilru_cache -Ihtslib -Isha1 -Isdsl-lite/install/include -Igcsa2 -L./ -Lvcflib -Lgssw/src -Lprotobuf -Lsnappy -Lrocksdb -Lprogressbar -Lhtslib -Lgcsa2 -Lsdsl-lite/install/lib -lvcflib -lgssw -lprotobuf -lhts -lpthread -ljansson -lncurses -lrocksdb -lsnappy -lz -lbz2 -lgcsa2 -lsdsl -lrt -static -static-libstdc++ -static-libgcc
```

I get a sad error about it not being possible to use `getaddrinfo` if I run with different dynamic libraries:

```
htslib/libhts.a(knetfile.o): In function `socket_connect':
/home/erik/vg/htslib/knetfile.c:98: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

And the binary does appear to be static:

```
➜  vg git:(master) ✗ ldd vg
        not a dynamic executable
```

And it runs on other systems with different library versions than mine with no issue, whereas the non-static one doesn't.

I'm guessing I'll be fine unless I open URLs with htslib.

As for fixing it, is there equivalent functionality in a more portable library?

**Comment by adamnovak** [comment]
After doing some research, it seems like this is due to a combination of two factors:

1. The glibc people don't really like the staticly linked binary usecase.
2. `gethostbyname()` isn't a DNS query function; it has to be able to understand and execute any name resolution system supported by the local `nsswitch.conf`, including things like Windows computer names and obscure old Sun naming systems. This sort of inherently involves dynamically invoking whatever code is used to actually interface with those name resolution systems. People who want to statically link in DNS name resolution and don't want to obey `nsswitch.conf` are advised to use something like `libresolv` from BIND.

**Comment by ekg** [comment]
It seems there is a fully self-contained c library that provides DNS resolution and some other relevant features. [DNS.c](http://25thandclement.com/~william/projects/dns.c.html), but I haven't tried it.

**Comment by jkbonfield** [comment]
On Thu, Aug 27, 2015 at 12:54:36AM -0700, Erik Garrison wrote:
> It seems there is a fully self-contained c library that provides DNS
> resolution and some other relevant
> features. [DNS.c](http://25thandclement.com/~william/projects/dns.c.html),
> but I haven't tried it. 

There are several potential work-arounds.

Eg an htslib could (atm cannot, but "could" meaning it would be
possible to) be built with any code that resolves hostnames removed, eg
via a configure command line option.  This would give an htslib that
cannot handle fetching data from http (either bam filenamess or cram
references), but it'd work fine on local files.

Deliberately linking against your own static DNS library, as you
mention, is another alternative if these features are required.

I'm not sure of the need for a fully static final program though.  For
example libcurl can be linked against dynamically using libcurl.so or
statically with libcurl.a, but the latter then requires the
application doing the linking to itself have additional dynamic
libraries in order to resolve the missing dependencies:

    jkb$ curl-config --libs
    -L/usr/lib/x86_64-linux-gnu -lcurl -Wl,-Bsymbolic-functions -Wl,-z,relro
    jkb$ curl-config --static-libs
    /usr/lib/x86_64-linux-gnu/libcurl.a -Wl,-Bsymbolic-functions -Wl,-z,relro -lidn -lssl -lcrypto -llber -lldap -lrt -lgssapi_krb5 -lssl -lcrypto -lz -lrtmp -lz -lgnutls

This is perfectly normal behaviour and well understood.  Htslib isn't
different in this regard.


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jmarshall** [comment]
I was going to say that building your static `vg` against something like that DNS.c would mean that your `vg` executable would not conform to sites' local policies so would be less useful for your users, but (having skimmed its documentation) if it does indeed consult _/etc/nsswitch.conf_ etc in the standard way then that may not be an issue.

In any case, `vg`'s experiments with static linking are mostly outside **htslib**'s scope.  We could assist by resurrecting `_USE_KNETFILE` as a configure option (but disabling networking would of course potentially remove functionality for your users), or might possibly entertain your patches to add `#ifdeffery` to enable knetfile.c to invoke DNS.c (if its interface is different).  But the direction in htslib is to move towards linking against libcurl (by default) rather than having its own networking code (delenda est knetfile)… at which point you will have other problems.

And the problem you are currently encountering is `getaddrinfo()`, but you will surely encounter others…

FYI my advice continues to be that statically linking against _system_ libraries is a fool's errand.  Sure, maybe bundle esoteric libraries that `vg` is using or link statically to them, to make life easier for your users.  But linking statically against _system libraries_ is just trading one support nightmare for another!

**Comment by jmarshall** [comment]
So this remains outwith **htslib**'s scope, especially as it moves towards libcurl.

It might also be interesting to compile `vg` on the lowest common denominator (w.r.t. glibc) platform that you wish to support, or use `objdump -x` and the techniques [here](http://www.trevorpounds.com/blog/?p=33) and [here](http://www.trevorpounds.com/blog/?p=103) to find the libc functions that are forcing the later libc, to build a `vg` linked dynamically against system libraries that works on all your platforms of interest.
