### ISSUE TITLE
detecting a sam/bam/cram file that is of 0 size.

### ISSUE THREAD

**Issue by atks** [samtools/htslib#261]
It's possible to open a bam/cram file that is of size 0 and then reading it without encountering any errors.

hts_open will still return a file handle
sam_hdr_read will return a struct
the format detected is SAM.

Is there an existing mechanism that I can check to throw an error in such cases?

**Comment by SamStudio8** [comment]
The new quickcheck command may catch this?

**Comment by atks** [comment]
where is the function? I can't find it in the latest pull of htslib.

**Comment by SamStudio8** [comment]
Ah sorry! I was talking about a new samtools subcommand (
https://github.com/samtools/samtools/pull/406) not something in the API...

**Comment by atks** [comment]
thanks for that! it's actually useful, I can go there and check how they do things.  So samtools quickcheck will also be silent about an empty sam/bam/cram file.

**Comment by jkbonfield** [comment]
On Wed, Aug 26, 2015 at 07:58:00AM -0700, Adrian Tan wrote:
> hts_open will still return a file handle
> sam_hdr_read will return a struct
> the format detected is SAM.
> 
> Is there an existing mechanism that I can check to throw an error in such cases?

This is correct though.  A zero length SAM file conforms to the SAM
specification! Pointless though that is...

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by SamStudio8** [comment]
I believe quickcheck will error on 0-length files as it checks for the
presence of at least one sequence.

**Comment by jmarshall** [comment]
There are improvements (related to #200) to `hts_detect_format()` approaching that could have it return `unknown` or a new `empty` code for 0-length files.

What would you prefer `hts_open()` et al to do for such files?

An empty file is technically a valid SAM file, so the existing behaviour can be construed as correct.

OTOH @daviesrob has made the point in the past that an empty file is not a _useful_ SAM file: a likely scenario is `somecmd | samtools view` with `somecmd` aborting and outputting nothing, and it would be useful for samtools to propagate the error rather than happily processing no input.

I suppose we now have the infrastructure to fail to recognise an empty file by default, but use `--input-fmt-option accept-empty` to accept even empty SAM files.

**Comment by atks** [comment]
I think using hts_detect_format() is a good idea.  

I think hts_open's job is to simply open a file; not to check for content.

**Comment by jmarshall** [comment]
Triage meeting consensus is disallowing 0-size files is desirable, and no need for `accept-empty`-style option.  Perhaps also consider dictating this in the SAM spec.
