### ISSUE TITLE
compress use gzip output with large file

### ISSUE THREAD

**Issue by yelliver** [samtools/htslib#270]
I run main() in bgzip.c to compress then decompress output file, the original file and the last result file are indentify. But when I change mode bgzf_open('w') to bgzf_open('wg'), compress large file (> 5MB), then decompress it, the last result file is shorter than the original file.

**Comment by jmarshall** [comment]
Could you please attach some test code demonstrating this problem?

**Comment by yelliver** [comment]
I test with this input file: https://tesseract-ocr.googlecode.com/files/tesseract-ocr-setup-3.02.02.exe
```c
    char *buf = malloc(1024);
    FILE *inp = fopen("tesseract-ocr-setup-3.02.02.exe", "r");
    BGZF *out_normal = bgzf_open("out_normal.gz", "w");
    BGZF *out_gzip = bgzf_open("/out_gzip.gz", "wg");
    ssize_t c;
    while ((c = fread(buf, 1, 1024, inp)) > 0) {
        bgzf_write(out_normal, buf, c);
        bgzf_write(out_gzip, buf, c);
    }
    fclose(inp);
    bgzf_close(out_normal);
    bgzf_close(out_gzip);
```
Extract result file using `gunzip *.gz` then calc checksum `md5sum *`
```
5fd026b3c316e8fb6b30511d64d45db0  out_gzip
27b63e93f2ff646a60da867f6881272c  out_normal
27b63e93f2ff646a60da867f6881272c  tesseract-ocr-setup-3.02.02.exe
```

**Comment by jmarshall** [comment]
Confirmed.  The bug is in `bgzf_gzip_compress()`, which does not allow for the fact that `deflate()` may not consume all input, leaving `avail_in` non-zero afterwards.

**Comment by jkbonfield** [comment]
Sorry it's been a while.  I think the bug is due to a misunderstanding of deflateBound().  Specifically it gives the maximum output size for a given input, **if** called directly after a deflateInit(). 

Our code carefully ensures that the input buffer is slightly smaller than the output buffer such that additional room in the output covers the maximum deflateBound() size.  Unfortunately for gz streams we're not doing block by block independently with deflateInit between each one, so it can flush the previous block during the next call to deflate() and break with expected maximum growth assumption.  The entire code is assuming blocks rather than streams and changing that is challenging.

Maybe it's sufficient to allocate twice as much, but I need to dig into zlib internals to check that.
