### ISSUE TITLE
Abort thrown when trying to check for a missing tag's presence

### ISSUE THREAD

**Issue by dnephi** [samtools/htslib#279]
Code:
 ```c
inline void check_inc_aux_tag(bam1_t *p, bam1_t *b, const char key[2])
{
   fprintf(stderr, "Looking for tag %s.\n", key);
    uint8_t *p_ptr = bam_aux_get(p, key);
    uint8_t *b_ptr = bam_aux_get(b, key);
    if(!(p_ptr && b_ptr)) {
        fprintf(stderr, "Found pointers for both reads with key %s.\n", key);
        *(int *)(p_ptr + 1) += *(int *)(b_ptr + 1);
    }
    else {
        fprintf(stderr, "Didn't find pointers for both aux tags with key %s.\n", key);
        int val = -1;
        bam_aux_append(p, key, 'i', sizeof(int), (uint8_t *)&val); // Set the value to -1 if the tag is not present.
    }
    //*(int *)(bam_aux_get(p, key) + 1) += *(int *)(bam_aux_get(b, key) + 1);
    return;
}
```
Output: 
Looking for tag NC.
Aborted
Only when a tag not present is found is the typecode returned 0 and the abort therefore thrown.

htslib commit: 8197cfdfa076d1c3ed5fd8428cf6c8c62c3d1d31

**Comment by jmarshall** [comment]
Presumably the abort encountered is the one on [line 1232](https://github.com/samtools/htslib/blob/develop/sam.c#L1232), which is triggered when trying to parse past an aux field with an invalid val_type.  Usually this would be because the input BAM file is corrupted or your code has corrupted the `bam1_t` record.

Recall that there are six differently-sized flavours of `i` field in BAM files and in **htslib**'s internal representation.  You should use `bam_aux2i()` to read a `c/C/s/S/i/I`-tagged field rather than assuming that the data at `b_ptr+1` will be an `int`.  Unfortunately the API doesn't currently provide a lot of help for _updating_ tagged fields; you could either use `bam_aux_del()`/`bam_aux_append()` or replicate the relevant code in [`bam_aux2i()`](https://github.com/samtools/htslib/blob/2c89e84e523b68ad1afaf6b7fd6c52a979af58f2/sam.c#L1265-L1275) or [`sam_parse1()`](https://github.com/samtools/htslib/blob/2c89e84e523b68ad1afaf6b7fd6c52a979af58f2/sam.c#L944-L966).

**Comment by dnephi** [comment]
What is the preferred method for checking for a field's presence? I know that pysam's wrapping of htslib checks for a null value from bam_get_aux(bam1_tObject, tagString). The abort is being thrown before I try to update or modify it.
For reference:
https://github.com/pysam-developers/pysam/blob/master/pysam/calignedsegment.pyx

**Comment by jmarshall** [comment]
`bam_aux_get(…) != NULL` is appropriate.  If this is aborting before your code has updated/corrupted the record, you'll have to show us a failing test case that we can reproduce.
