### ISSUE TITLE
samtools 1.3 test suite incompatible with htslib 1.3.1.

### ISSUE THREAD

**Issue by charles-plessy** [samtools/htslib#374]
In Debian, during the brief time window where `htslib` was version `1.3.1` and `samtools` version `1.3` only, the continuous integration tests showed that they are incompatible, since the regression tests of `samtools` failed with the following message:

```
UNEXPECTED PASS: Task worked when we expected failure;
when running $samtools mpileup -x -d 8500 -B -f mpileup.ref.fa deep.sam|awk '{print $4}'
See PASS-47.out.1 vs expected/47.out
```

The full build log is available as an attachment at <https://bugs.debian.org/822701>.

We will make sure these versions can not be co-installed, but I am reporting this in case it is a bug you were not aware of.

Cheers,

-- 
Charles Plessy
Debian Med packaging team

**Comment by jmarshall** [comment]
This does not mean that samtools-1.3 is incompatible with htslib-1.3.1; rather it means that the samtools‑1.3 **test suite** is incompatible with htslib-1.3.1.  This was previously an expected-fail test involving the samtools mpileup command.  The cause of the bug turned out to be in htslib, and htslib-1.3.1 fixes the bug.  So the samtools test now unexpectedly passes.

See samtools/samtools@664cc5fee8d8f75add2d6bf79db3f74465a7b723.  We like to think of this change as a feature, not a bug. :smile:

However I can see that this may be an unfortunate scenario for packagers.  This may say something about the wisdom of having expected-fail tests in a test suite whose successful execution some may consider to be a “build from source” prerequisite…

**Comment by jkbonfield** [comment]
The "unexpected pass" is almost certainly due to a bug fix in htslib. See
https://github.com/samtools/samtools/commit/664cc5fee8d8f75add2d6bf79db3f74465a7b723
https://github.com/samtools/htslib/commit/df4a80e9c387bb1d84cdb47c02e44e77b0f57770

Our testing setup isn't too great really as we have many samtools tests that really should be in htslib instead.   A consequence of this is that we have a few known failures in samtools tests that are actually issues in htslib (although we don't always know where the bug lies initially of course).

**Comment by charles-plessy** [comment]
Thanks a lot for the prompt answer; it makes total sense.
