### ISSUE TITLE
memory leak in hts_set_fai_filename

### ISSUE THREAD

**Issue by pd3** [samtools/htslib#394]
There is a memory leak when calling `sam_open` followed by `hts_set_fai_filename` and `sam_close`, please see valgrind output here: 

    ==6901== 1,704 bytes in 3 blocks are still reachable in loss record 1 of 1
    ==6901==    at 0x4C2B6CD: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==6901==    by 0x57D409A: __fopen_internal (iofopen.c:76)
    ==6901==    by 0x4E3818: refs_load_fai (cram_io.c:1816)
    ==6901==    by 0x4E582A: cram_load_reference (cram_io.c:2793)
    ==6901==    by 0x4EA1E0: cram_set_voption (cram_io.c:4513)
    ==6901==    by 0x4EA846: cram_set_option (cram_io.c:4424)
    ==6901==    by 0x496181: hts_set_fai_filename (hts.c:949)

**Comment by jmarshall** [comment]
Only for CRAM files, or have you seen this for a BAM file too?

**Comment by pd3** [comment]
CRAM files only

**Comment by jkbonfield** [comment]
On Thu, Jun 23, 2016 at 03:10:41AM -0700, pd3 wrote:
> There is a memory leak when calling `sam_open` followed by `hts_set_fai_filename` and `sam_close`, please see valgrind output here: 
> 
>     ==6901== 1,704 bytes in 3 blocks are still reachable in loss record 1 of 1
>     ==6901==    at 0x4C2B6CD: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
>     ==6901==    by 0x57D409A: __fopen_internal (iofopen.c:76)
>     ==6901==    by 0x4E3818: refs_load_fai (cram_io.c:1816)
>     ==6901==    by 0x4E582A: cram_load_reference (cram_io.c:2793)
>     ==6901==    by 0x4EA1E0: cram_set_voption (cram_io.c:4513)
>     ==6901==    by 0x4EA846: cram_set_option (cram_io.c:4424)
>     ==6901==    by 0x496181: hts_set_fai_filename (hts.c:949)

That looks more like it's a leak of file handle (failing to close, and
hence leaking the associated memory) rather than the more common leak
type.

I can see the issue too.  I'll investigate why it ended up this way
and fix it.  Thanks for the bug report.

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jkbonfield** [comment]
Oddly I couldn't get this to show up in valgrind as a leak, which is perhaps why I haven't spotted it before.  It may depend on the implementation of your C library.

It does however show up with valgrind --track-fds=yes

Thanks for the bug finding.
