### ISSUE TITLE
parallel read of bgzf

### ISSUE THREAD

**Issue by brentp** [samtools/htslib#433]
As far as I can see there is no way to set the number of threads (or use > 1) for reading. Even for .vcf.gz that do a lot with each record the parsing step is a bottleneck in our pipeline.

I see there have been previous attempts at this: https://sourceforge.net/p/samtools/mailman/message/33140257/

Can this be supported in the same way that parallel writing is supported?

**Comment by jkbonfield** [comment]
I added code to do this a while back and it's been merged into htslib develop recently.  It will appear in an official release once 1.4 is shipped.  There is still an outstanding PR (#595) for samtools to use this in -@ options, but it's usable right now via --input-fmt-option; plus not all commands had -@ anyway.

Eg: (yes this file is truncated - I couldn't be bothered to wait for it all to copy over)

```
@ deskpro107386[samtools.../samtools]; time ./samtools flagstat /tmp/SRR065390_1.srt.bam 
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[bam_flagstat_core] Truncated file? Continue anyway.
15077640 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
15077640 + 0 mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

real	0m9.028s
user	0m8.966s
sys	0m0.068s


@ deskpro107386[samtools.../samtools]; time ./samtools flagstat --input-fmt-option nthreads=4 /tmp/SRR065390_1.srt.bam 
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[bam_flagstat_core] Truncated file? Continue anyway.
15077640 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
15077640 + 0 mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

real	0m2.592s
user	0m9.664s
sys	0m0.540s
```

NB: this method of multi-threading has been there for CRAM for some time (IIRC), which had multi-threaded decoding since the start.

That said, you explicitly mention vcf.gz.  The bottleneck here will probably be parsing and not uncompression.  The patch only multi-threads the bgzf code and not the parsing functions, so maybe it won't help much.

**Comment by brentp** [comment]
ah thank you, I missed that. so the change to my code will be, e.g. `bgzf_mt(fp, threads, 256)` with no additional/changed destroy calls?

**Comment by jkbonfield** [comment]
Yes that's the theory. 

The new multi-threading is based on a thread pool and operates continuously rather than buffering up 256 blocks before launching and syncing a bunch of threads.  Hence the n_sub_blks parameter (256) is completely ignored now, but was kept in the API for compatibility, but it's probably best to keep it at 256 anyway for backwards compatibility with older htslib implementations.  Having said that I think it may have simply died before if specified on an input file descriptor.

**Comment by brentp** [comment]
thanks.
