### ISSUE TITLE
tabix gff error: unsorted positions

### ISSUE THREAD

**Issue by billzt** [samtools/htslib#434]
I sort my GFF3 file using genome tools:
```
gt gff3 -sort -tidy -retainids in.gff3 >out.gff3
```
Then I use bgzip and tabix. Some gff3 are OK, but some are not:
```
[E::hts_idx_push] unsorted positions
tbx_index_build failed: 
```

Well, how do I know which positions are unsorted?

**Comment by pd3** [comment]
Try `sort -k1,1d -k4,4n -c out.gff3`

**Comment by jmarshall** [comment]
This error message has been improved in **develop**; if you build a copy of `tabix` from current GitHub it'll tell you the positions it's confused about.  See 11661a57306a048528d0a223c86c62bcdc20eb18, in particular the note about how it prints out the ordinal number rather than the name of the reference sequence in question.

**Comment by billzt** [comment]
Well, I know, this is due to the overlaping genes. I'll close it and open a new issue.
