### ISSUE TITLE
Is there a detailed usage introduction  about htslib ?

### ISSUE THREAD

**Issue by zeronot** [samtools/htslib#476]
HI,
     htslib team can provide detailed document to tell us how to use htslib ?

**Comment by jkbonfield** [comment]
I'm afraid there aren't any tutorials.  Some of the header files have doxygen formatting documentation, while others are still either undocumented or with more traditional C style commenting.  Therefore your best bet is simply to look at the htslib/*.h public header files for API information.

This can be coupled with grepping through the samtools and bcftools package source to find example usage patterns.

I'm sorry it's not more helpful.

(Closing this as a question rather than issue and I believe we already have doxygen generation in the issues.)
