### ISSUE TITLE
Near NULL write AV in cram_gamma_decode

### ISSUE THREAD

**Issue by cryptoad** [samtools/htslib#554]
This doesn't have a direct security implication, but I am filing it nonetheless as it could potentially hide something else. The attached file leads to a NULL deref on write:
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555559ab468 in cram_gamma_decode (slice=0x611000001800, c=0x616000006f80, in=0x6070000006b0, out=0x0, out_size=0x7fffffff8220)
    at third_party/htslib/htslib_1_4_1/cram/cram_codecs.c:801
801             out_i[i] = val - c->gamma.offset;
(gdb) p c
$1 = (cram_codec *) 0x616000006f80
(gdb) p out_i
$2 = (int32_t *) 0x0
(gdb) p i
$3 = 0
```
[poc.zip](https://github.com/samtools/htslib/files/1056498/poc.zip)

**Comment by cryptoad** [comment]
Same one in `cram_subexp_decode`:
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555559aa532 in cram_subexp_decode (slice=0x611000001800, c=0x616000006c80, in=0x6070000006b0, out=0x0, out_size=0x7fffffff8220)
    at third_party/htslib/htslib_1_4_1/cram/cram_codecs.c:735
735             out_i[count] = val - c->subexp.offset;
(gdb) p out_i 
$1 = (int32_t *) 0x0
(gdb) p count
$2 = 0
```
[poc.zip](https://github.com/samtools/htslib/files/1056500/poc.zip)

**Comment by cryptoad** [comment]
Somewhat identical one in `cram_huffman_decode_char`:
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555559ac9d1 in cram_huffman_decode_char (slice=0x611000001800, c=0x616000004b80, in=0x6070000006b0, out=0x0, 
    out_size=0x7fffffff81c0) at third_party/htslib/htslib_1_4_1/cram/cram_codecs.c:918
918                     out[i] = codes[idx].symbol;
(gdb) p out
$1 = 0x0
(gdb) p i
$2 = 0
```
[poc.zip](https://github.com/samtools/htslib/files/1056502/poc.zip)

**Comment by daviesrob** [comment]
These are triggered when a byte decoder gets called with a NULL pointer for the output.  This was allowed by commit 1a050b4fc, as a way of dealing with records that have a CIGAR string, but no sequence data.  The commit also updated some, but not all, decoders to consume input but not store it when the output pointer is NULL.

The only data series that try to pass a NULL output pointer are DS_BA, DS_BB, DS_IN and DS_SC.  These all have type BYTE, or BYTE_ARRAY.  Since f613867, the gamma and subexp codecs can only be used for type INT, so that commit has fixed the first two cases.

I'll drop a very tiny commit that fixes `cram_huffman_decode_char()`, which is the only one left that needs to check `out != NULL`.
