### ISSUE TITLE
Adding a license to a repository

### ISSUE THREAD

**Issue by tmozgach** [samtools/htslib#566]
Licenses API can't recognize your License.
Could you please add a license to your repository based on the following guide: 
https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by jkbonfield** [comment]
We already have a LICENSE file.  I expect the problem is that not all software came from a single source, so some has MIT license and some BSD license.  They're completely compatible and both included in the LICENSE file, but I assume this has meant that the automatic detection failed due to it not matching any one single template.  There isn't much we can do about this I think.

**Comment by jkbonfield** [comment]
Actually that said, the cram subdirectory (which originated from Staden "io_lib" under the BSD license) has been pruned bit by bit and I suspect now there is very little code left which *wasn't* written at Sanger Institute.  So in theory most (if not all) could be reissued under MIT, to simplify matters.  It'd need careful consideration though.
