### ISSUE TITLE
increment SOVERSION please

### ISSUE THREAD

**Issue by detrout** [samtools/htslib#616]
Hello,

I was working on fixing build issues with htslib 1.5 and python-pysam 0.12 on Debian and discovered that symbols were removed between htslib 1.4.1 and 1.5. Which should've triggered a SOVERSION increase.

Looks like there's other symbols that were removed in 1.6. I found debug_vbuf, hopen_json_redirect which were public and implemented in 1.5.

Would it be reasonable to update the SOVERSION number to 4 for 1.6? and I can set it to 3 for Debian's 1.5?

**Comment by jmarshall** [comment]
Please list the particular symbols you are concerned about.

You will likely find they are not public HTSlib functions in the sense that they are not declared in _htslib/*.h_, so are not part of the public HTSlib API, so changes in them do not affect the HTSlib ABI. (This is certainly the case for `debug_vbuf` and `hopen_json_redirect`.) So no SOVERSION bump would be necessary. Compare #311.

**Comment by daviesrob** [comment]
I've tried building [pysam-0.11.2.2](https://github.com/pysam-developers/pysam/releases/tag/v0.11.2.2), which is the last release to wrap htslib 1.4.1.  As far as I can tell, it works fine with shared libraries for htslibs 1.4.1, 1.5 and develop.  So it should be both API and ABI compatible as far as pysam is concerned.

Looking at the [debian bugs page for htslib](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=libhts2;dist=unstable), I think I can see what's going on:

[Bug 879867](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879867) reports the missing symbol `hts_log()` for pysam 0.12.0.1.  That's because pysam 0.12.0.1 requires at least htslib 1.5, as described in its [release notes](https://github.com/pysam-developers/pysam/releases/tag/v0.12.0).

This links to [bug 871314](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871314), where pysam is complaining that its embedded samtools is not the same version as the system-installed one.  I'm not sure why it does this test, but it doesn't look like a good idea as it completely locks pysam to a specific release of samtools and bcftools.  You might want to discuss disabling that test with the pysam developers.  As far as htslib is concerned, version 1.6 should be compatible with all versions of pysam going back to [version 0.11.0](https://github.com/pysam-developers/pysam/releases/tag/v0.11.0) (which was the first to support the current SOVERSION).

The debian package for htslib seems to do some very odd things, like [expose static functions](https://anonscm.debian.org/cgit/debian-med/htslib.git/tree/debian/patches/htslib-add-cram_to_bam.patch) and [copy the private cram header files to /usr/include](https://anonscm.debian.org/cgit/debian-med/htslib.git/tree/debian/libhts-dev.install).  It would be nice to fix these as its very likely that they will cause compatibility problems.

**Comment by detrout** [comment]
@daviesrob thank you for looking up the relevant bugs. I really should've linked to them.

There's also [#879886](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879886) which has most of our discussion on htslib2's symbol problems.

Debian has a mechanism to track changes in the exposed symbols for a library [https://wiki.debian.org/UsingSymbolsFiles](https://wiki.debian.org/UsingSymbolsFiles), but the previous maintainers gave up using it. (I'm guessing because there's a fair amount of churn in what symbols are exposed in the library.

If the symbols files had been maintained properly pysam's 0.12's dependency on htslib 1.5 should have have been detected.

> The debian package for htslib seems to do some very odd things, like expose static functions and copy the private cram header files to /usr/include. It would be nice to fix these as its very likely that they will cause compatibility problems.

I found why the private cram files are exposed. Debian has a policy that packages should not make use of these convenience copies unless the included package is explicitly intended to be used in this way. SeqLib and Sambaba both include specific copies of htslib2 which access the private cram functions, but the typical behavior is to remove the embedded library and use the shared library.

But your indicating htslib2 consideres the cram api private... Do you have any advice about software that's linking to the cram functions?

Unfortunately I'm also out of practice with maintaining symbols files... I was checking to see if they'd been present in the source, but I needed to be checking the installed headers in /usr/include.

Thank you for your input I need to go back and talk to the other Debian developers.

**Comment by jkbonfield** [comment]
The problem here is a difference between "exposed" symbols and "public" symbols.  C only defined static functions and external functions, but unless we make the entire library one .c file then this doesn't help.  There are *compiler specific* ways of removing functions from a library so we can have them as library-only external, but we don't use these due to portability.  Hence tools like "nm" will claim there is an exported function, but that doesn't make it public and we don't deem it necessary to bump the library version every time we change an internal-only function. 

This is why we define our public API as the functions having an externally visible prototype in our public header files.  This is also why **overriding our decision on what is public by patching the source is a bad thing to do**!

Perhaps we should jump through more hoops and explicitly list the symbols to export, but it's more work for all concerned.

Regarding the use of internal functions by SeqLib and Sambamba, we weren't aware of them using these internal functions as I can't recall ever having an issue raised on it. We'd need to review what is appropriate and to see if there is a better way for them to be working (eg calling a supported function instead) or for us to make more functions public.

I appreciate as a distribution it is far from ideal to have duplicate copies of code, but it is more correct to permit someone to incorporate and patch their own copy of the library than to misrepresent the official library by changing it to expose more functions without notifying the upstream maintainers.

**Comment by jmarshall** [comment]
> [jkbonfield] This is why we define our public API as the functions having an externally visible prototype in our public header files

(To be precise…) Being declared in _htslib/*.h_ is a necessary but not quite sufficient condition for being part of the public API. There are a (very) few functions that are declared there for technical reasons but which are individually documented as being private internal functions.

> [detrout] Do you have any advice about software that's linking to the cram functions?

I've taken the liberty of filing a debian bug about this and a couple of other libhts-dev things. Link here when it finally appears…

**Comment by detrout** [comment]
Just to check, have you looked into export lists or using visibility attributes to hide symbols you consider private? It looks like those are alternatives to the static keyword that can keep a symbol private in the shared library while still allowing visibility between different object files.

One write up:
https://www.ibm.com/developerworks/aix/library/au-aix-symbol-visibility/index.html

"How to write shared libraries."
https://www.akkadia.org/drepper/dsohowto.pdf
A very detailed discussion about how shared libraries work on linux. (I really should read that document, but so far I've just skimmed it)

If you have considered that and chosen not to, then this bug is probably done, and there's just the issue of working out a public cram API.

**Comment by jkbonfield** [comment]
I can't recall us ever having the conversation and deliberately excluding ways of limiting symbol visibility, but it's what I was referring to above when I said "There are _compiler specific_ ways of removing functions from a library so we can have them as library-only external, but we don't use these due to portability".

It's possible after a review we could find these methods although non-standard are sufficiently supported by most compilers to be a workable solution, but it adds to complexity of the build process considerably.  Note we're not just a Linux only library either.  Windows for example has a *very* different way of defining symbol scope.

PS.  Thanks for the Drepper link.  As always he's thorough. :-)

**Comment by detrout** [comment]
I found an example macro on the GCC wiki to control visibility on both windows and unix like operating systems. Its more of an issue for C++, but it looks like it should work with C functions too.
https://gcc.gnu.org/wiki/Visibility

Documentation for clang suggests they support the same __attribute__((visibility("")) syntax as gcc.
https://clang.llvm.org/docs/LTOVisibility.html

It looks like you're just using autotools so I'm guessing you just support gcc and clang? and don't support compiling with visual studio?

**Comment by detrout** [comment]
Also I found a more complicated symbol question.

in 1.4.1 ks_destroy, ks_getuntil2, and ks_init are missing from the library. However they're implemented via macros in kseq.h They seem to have been around for a long time, so I'm less clear how they should be handled.

**Comment by jmarshall** [comment]
`git log -S ks_init` brings you to 71c03b88edf892a93eae7bb7932a6da84858480a. As it happens, this change appeared in the release that bumped the SOVERSION.
