### ISSUE TITLE
htslib 1.6 breaking CRAM fetch: "truncated file or corrupt BAM index file"

### ISSUE THREAD

**Issue by ihaque-freenome** [samtools/htslib#651]
From https://github.com/pysam-developers/pysam/issues/567

It appears that certain CRAM files that work fine under htslib < 1.6 (tested with 1.5 and 1.3.1, using either samtools or pysam <0.13) throw errors when queried using tools built against htslib 1.6. Reproducing examples are given in the linked issue.

cc @kyleabeauchamp

**Comment by daviesrob** [comment]
The issue turned up in commit 6b56bc11, although that only changed how errors are propagated so the bug was already there, it just didn't cause an error to be reported before this.  The actual problem is that `cram_get_seq()` can under certain conditions return NULL (as there is no more data) with the `cram_fd` `eof` and `err` fields both zero.  This makes the `cram_eof()` check in `cram_readrec()` return an error instead of end-of-file.

It looks like the actual bug is at [cram_next_slice() line 2954](https://github.com/samtools/htslib/blob/1c5c5089/cram/cram_decode.c#L2954), where it fails to set `fd->eof = 1` when it has found that the next container is outside the desired region.

I've also noticed a bug in the loop at line 2942, although I think it was mostly harmless.  When checking to see if the region covered by the container ended before the one in the range query, it failed to check that the reference ids matched.  If the desired region started at a sufficiently high position there were a lot of unnecessary seeks and container reads until either the container end location was high enough (albeit on the wrong chromosome), it found a container with reference id -2 (mixed references) or it reached the end of the file.

I'll make a pull request to fix these.  It'll need to be checked by @jkbonfield to make sure I've got it right.
