### ISSUE TITLE
bgzip - hardcoded names of temporary files prevent running in parallel in the same folder

### ISSUE THREAD

**Issue by estolle** [samtools/htslib#652]
Hi there

Is there a way (argument passed to the bgzip command) to specify the name/location of bgzip-temporary files?

Quite often I run into trouble when I launch multiple instances of bgzip (e.g. through a GNU parallel) and each instance is launched from the same folder. It seems each instance creates temporary files with the very same hardcoded names (1.bcf 2.bcf etc). This typically crashes each instance or the output is mixed/truncated. I had this issue with older version as well as a recent one (Version: 1.6).
example code (in a bash script which is launched multiple time in parallel)
cat file | some other commands | bgzip -f -@ 20 -c /dev/stdin > $FOLDER/$ID.vcf.gz
tabix -fp vcf $FOLDER/$ID.filtered.vcf.gz

At the moment I workaround by changing the folder, which can be a pain.
Any suggestions how to otherwise circumvent the problem?

thanks

**Comment by daviesrob** [comment]
I'm not sure if I understand where the temporary files are coming from.  `bgzip -@ 20 -c` shouldn't make any.

Is the problem `$ID` not changing?  If that's the case, assuming a new enough version of GNU parallel you could try using `$PARALLEL_SEQ` to give a unique sequence number to each job.  If it's not this, I would suspect the problem is coming from somewhere earlier in the pipeline.

Incidentally, mixing a 20 thread bgzip with many jobs running in parallel would seem ambitious unless you have a lot of CPU cores available...

**Comment by estolle** [comment]
Thanks for this answer. It made me investigate a bit more specifically into where the temporary files come from. I'd always assumed they come from bgzip.
I think I found the origin/problem. In the commands before piping into bgzip, I am using vt to sort a large .vcf file. Since I am piping it, there is no output-name, but vt names the temporary files "<output_vcf>.<no>.bcf", thus in my case only names it "<no>.bcf". Thus, nothing to do with bgzip. 
Thanks again =)
