### ISSUE TITLE
VCF iterator broken?

### ISSUE THREAD

**Issue by stolpeo** [samtools/htslib#659]
Hello,

I'm trying to read a vcf file by chromosome. While it can read the VCF as a whole,
the iterator seems broken (or do I use it wrong?). I based it on the test in [test-vcf-api.c](https://github.com/samtools/htslib/blob/44c47501378e537632526b8e033985a912554093/test/test-vcf-api.c).

Here is an example:

```
#include <iostream>
#include <htslib/hts.h>
#include <htslib/vcf.h>

using namespace std;

int main(int argc, char* argv[]) {
    htsFile *in;
    bcf_hdr_t *hdr;
    bcf1_t *rec = bcf_init();

    in = bcf_open("example.vcf.gz", "r");
    hdr = bcf_hdr_read(in);
    bcf_index_build("example.vcf.gz", 0);
    hts_idx_t *idx = bcf_index_load("example.vcf.gz");
    hts_itr_t *itr = bcf_itr_querys(idx, hdr, "20");
    int ret = bcf_itr_next(in, itr, rec);
    cout << "return: " << ret << endl;

    in = bcf_open("example.vcf.gz", "r");
    hdr = bcf_hdr_read(in);
    while (bcf_read(in, hdr, rec) == 0) {
        cout << bcf_hdr_id2name(hdr, rec->rid) << ":" << rec->pos << endl;
    }

    return 0;
}
```

This returns the following, indicating that it can't read the vcf using the iterator but the whole VCF file:

```
return: -2
20:14369
20:17329
20:1110695
20:1230236
20:1234566
```

The example VCF is taken from the specifications:

https://samtools.github.io/hts-specs/VCFv4.2.pdf
[example.vcf.gz](https://github.com/samtools/htslib/files/1716040/example.vcf.gz)

**Comment by jkbonfield** [comment]
Do you have an index?  The file needs to be compressed using `bgzip` and indexed with `bcftools index`.

**Comment by stolpeo** [comment]
Hello James,

thanks for the quick reply. I had the line
```
    bcf_index_build("example.vcf.gz", 0);
```
included in my code, which I thought was supposed to create an index.

To be sure, I removed the line, recompiled the program and also unpacked and `bgzip`'d the example file and indexed it with `bcftools index` as you suggested. I still get the same return code.

```
$ file example.vcf.gz
example.vcf.gz: gzip compressed data, extra field
```

**Comment by valeriuo** [comment]
@stolpeo there a few caveats to your code:

1. `bcf_index_build` function generates an index file (ending in **.csi** or **.tbi**), which you need to load explicitly back into your code 

`hts_idx_t *idx = bcf_index_load("example.bcf.csi");`

2. Unfortunately, the BCF iterator **doesn't work** with VCF files (not even compressed VCF), due to the limitations of the underlying file access function (`bcf_readrec`). We will add a relevant message to warn developers of this issue. So you need to convert the VCF file to BCF and create and index for the BCF file.

`bcftools view -o example.bcf -Ob example.vcf.gz`
`bcftools index example.bcf`

3. After creating the iterator, use it in a reading loop:
```c
while ((ret = bcf_itr_next(in, itr, rec)) == 0) {
    //read the info from rec
}
```

4. Check the pointers that you are using for nullness after each assignment: `in`, `rec`, `hdr`, `idx`, `itr`.

5. Destroy the relevant structures before exiting:
```c
    bcf_itr_destroy(itr);
    hts_idx_destroy(idx);
    bcf_hdr_destroy(hdr);
    bcf_destroy1(rec);
    bcf_close(in);
```

A working version would be:
```c
#include <stdio.h>
#include <htslib/hts.h>
#include <htslib/vcf.h>

int main(int argc, char* argv[]) {
    int ret;
    htsFile *in;
    bcf_hdr_t *hdr;
    bcf1_t *rec = bcf_init();

    in = bcf_open("example.bcf", "r");
    if (!in)
        printf("Null file pointer\n");
    hdr = bcf_hdr_read(in);
    //printf("Index creation: %d\n", bcf_index_build("example.bcf", 14));
    hts_idx_t *idx = bcf_index_load("example.bcf.csi");
    if(!idx)
        printf("Null index\n");
    hts_itr_t *itr = bcf_itr_querys(idx, hdr, "20");
    if(!itr)
        printf("Null iterator\n");
    while ((ret = bcf_itr_next(in, itr, rec)) == 0) {
        printf("ret: %d - id: %d, pos: %d, len: %d\n", ret, rec->rid, rec->pos, rec->rlen);
    }

    bcf_itr_destroy(itr);
    hts_idx_destroy(idx);
    bcf_hdr_destroy(hdr);
    bcf_destroy1(rec);
    bcf_close(in);

    return 0;
}
```

**Comment by valeriuo** [comment]
A new [commit](https://github.com/samtools/htslib/commit/9f9631d297e8b9b5968d705f5136397d15775fbd) has been added, that describes in grater detail the usage of function `bcf_index_build`.
