### ISSUE TITLE
Using sam.h and hts.h header files in C++

### ISSUE THREAD

**Issue by gkarthik** [samtools/htslib#669]
Hello, 

I've been trying to use sam.h and hts.h in a C++ program to read a bam file but I keep getting the following error, 

````
Undefined symbols for architecture x86_64:
  "_BZ2_bzBuffToBuffCompress", referenced from:
      _cram_compress_block in cram_io.o
      _cram_compress_by_method in cram_io.o
  "_BZ2_bzBuffToBuffDecompress", referenced from:
      _cram_uncompress_block in cram_io.o
....
....
  "_curl_version_info", referenced from:
      _hfile_plugin_init_libcurl in libhts.a(hfile_libcurl.o)
....
....
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
````

GCC version 6.3.0 
Operating System: Mac OS 10.13.3

I'm using the following command for compilation. 

`g++ -g -Ihtslib -I htslib-1.7/ -L/usr/local/lib/ -D__STDC_LIMIT_MACROS ./main.cpp  /usr/local/lib/libhts.a -lz -lpthread -o main`

Thank you.

**Comment by jkbonfield** [comment]
These are link errors rather than compilation ones, so this isn't an issue of the language.

If you linked against the dynamic htslib (eg if it was installed, via -L/usr/local/lib -lhts) then this should automatically bring in all of the dependencies.  If you really have to link statically, then you will need to know all the dependencies of libhts.a and link those in yourself.

You can get this from pkg-config via, e.g.

```
pkg-config --static --libs /usr/local/lib/pkgconfig/htslib.pc
```

Alternatively the source tree will have an htslib_static.mk Makefile stub that defines `HTSLIB_static_LIBS` for you to use in a Makefile.

**Comment by gkarthik** [comment]
Using -lhts solved it. I kept trying to use -lhtslib. 
Thank you!
