### ISSUE TITLE
warnings with GCC

### ISSUE THREAD

**Issue by imgag** [samtools/htslib#676]
I get these warnings about narrowing conversion when compiling htslib with GCC5 on Ubuntu 16.04.3.

	> g++ --version
	g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
	Copyright (C) 2015 Free Software Foundation, Inc.
	This is free software; see the source for copying conditions.  There is NO
	warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	> g++ -c -m64 -pipe -O3 -std=c++0x -Wall -W -D_REENTRANT -fPIC -I../../htslib/include -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o test.o test.cpp
	../../htslib/include/htslib/sam.h:84:29: warning: narrowing conversion of '((*(((unsigned int*)cigar) + ((sizetype)(((long unsigned int)i) * 4ul)))) & 15u ' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
	 #define bam_cigar_op(c) ((c)&BAM_CIGAR_MASK)
	../../htslib/include/htslib/sam.h:85:32: warning: narrowing conversion of '((*(((unsigned int*)cigar) + ((sizetype)(((long unsigned int)i) * 4ul)))) >> 4)' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
	 #define bam_cigar_oplen(c) ((c)>>BAM_CIGAR_SHIFT)

Is it possible to fix the warnings?
Since they come from a header file, I also get the warnings every time I compile our project that uses the htslib headers and library.

Thanks,
  Marc

**Comment by jkbonfield** [comment]
I think we'd need to see your code.

I tried a noddy example myself, as I wanted to see how we handled using a C++ compiler (in theory it works, but C++ has stricter type checking so something may has slipped), but my test worked fine using g++ 5.3.0 and 7.1.0.  My test code is as follows:

```
#include <stdio.h>
#include "htslib/sam.h"

int main(void) {
    samFile *in;
    bam_hdr_t *h;
    bam1_t *b = bam_init1();
    int nreads = 0;
    int nm = 0;

    in = sam_open("-", "r");
    h = sam_hdr_read(in);

    while (sam_read1(in, h, b) >= 0) {
        nreads++;
        unsigned int i;
        uint32_t *cig = bam_get_cigar(b);
        for (i = 0; i < b->core.n_cigar; i++) {
            if (bam_cigar_type(bam_cigar_op(cig[i])) & 2)
                nm += bam_cigar_oplen(cig[i]);
        }
    }

    bam_destroy1(b);
    bam_hdr_destroy(h);
    sam_close(in);

    printf("%d reads, %d bases mapped\n", nreads, nm);

    return 0;
}
```

I can get some *different* errors if I use `int *cig = bam_get_cigar(b);` instead of uint32_t, but still not the "narrowing conversion" ones you see.

**Comment by jkbonfield** [comment]
Ok by being deliberately obtuse I can get this exact error, but it's due to a coding error in the test code.  Eg:

```
        uint32_t *cig = bam_get_cigar(b);
        for (i = 0; i < b->core.n_cigar; i++) {
            int32_t c[] = {bam_cigar_op(cig[i]), bam_cigar_oplen(cig[i])};
            if (bam_cigar_type(c[0]) & 2)
                nm += c[1];
        }
```

Here c[] should be uint32_t and not int32_t as the internal members are unsigned.  This is where the narrowing conversion error comes from:

```
a.c: In function 'int main()':
/nfs/users/nfs_j/jkb/work/samtools_master/htslib/htslib/sam.h:84:29: warning: narrowing conversion of '((*(cig + ((sizetype)(((long unsigned int)i) * 4ul)))) & 15u)' from 'uint32_t {aka unsigned int}' to 'int32_t {aka int}' inside { } [-Wnarrowing]
 #define bam_cigar_op(c) ((c)&BAM_CIGAR_MASK)
                             ^
a.c:19:21: note: in expansion of macro 'bam_cigar_op'
      int32_t c[] = {bam_cigar_op(cig[i]), bam_cigar_oplen(cig[i])};
```

Indeed the following line after the error lists the offending line of code too.  (It would be useful if you include that in the message.)

I suspect this problem isn't htslib at fault though, but the code calling it.

**Comment by imgag** [comment]
Hi James,

you were right, the assignment of the result was the problem.
The error mislead me because it says it's inside the #define, but it's actually outside.
Thanks for your time.

Best,
  Marc
