### ISSUE TITLE
Could bgzip be made fastq-aware?

### ISSUE THREAD

**Issue by jenzopr** [samtools/htslib#677]
Hi all,

I'm currently exploring possibilities of bgzip'ed FASTQ files and noticed that FASTQ entries might get split somewhere in between when the block size is reached.
Would it be possible to allow splits into different blocks only when certain criteria are met (e.g. a new FASTQ entry starts, or easier: if the line_number can be divided by 4 without remainder)?

Best and thanks for a short notice,
Jens

**Comment by jamesthegiantpeach** [comment]
I can think of a lot of reasons to want this. One would be: you have a seeker library into AWS S3 objects, and you want to be able to seek to a number of workers and pass the shards out to workers in your cluster.

**Comment by jkbonfield** [comment]
Not a direct solution to the above, but as a workaround you could convert your fastq to unmapped SAM (trivial) and then to CRAM.  This then permits indexing and retrieval by Nth-Mth container using io_lib's `cram_fitler` tool.  The resultant CRAM would then need converting back to FASTQ probably.

Alternatively even if it's just unmapped BAM then you'll get the benefits of automatically attempting to start a new sequence on a new bgzf boundary.

All messy, but the data is more compact and with better random access than permitted by fastq.gz.

It doesn't invalidate this request, but given locally we never use fastq if we can help it (as it's a dire format and unaligned SAM et al is preferable for many reasons) it's also not going to be high on the priority.  [As is evidenced by the fact this issue was long forgotten apparently.]

**Comment by jamesthegiantpeach** [comment]
I agree with above. Although, is there no way to feed an unmapped SAM into bwa?

**Comment by jenzopr** [comment]
I think we can close this. Thanks!
