### ISSUE TITLE
Is there a way to update an integer aux value?

### ISSUE THREAD

**Issue by sfchen** [samtools/htslib#686]
I see `bam_get_aux()` and `bam_aux_update_str()`, but I cannot find a `bam_aux_update` for an integer type value.

For example, `AS`, which means alignment score, is an integer aux. How to update it? How many bits does this integer takes?

**Comment by daviesrob** [comment]
The only way to do this with the current API is to remove the existing tag with bam_aux_del() and then add it back again with bam_aux_append().  This will work, but is a bit slow and the tag will move to the end of the sam record.

An alternative would be to use bam_aux_get() to find where the record is and then poke the data in yourself.  This isn't too difficult if the size of the stored data doesn't change but you do need to know about how the data is stored internally.

One of these days I will get around to improving this rather unsatisfactory situation by adding a better API to manipulate integer tags.

**Comment by sfchen** [comment]
```
/// Append tag data to a bam record
/* @param b    The bam record to append to.
   @param tag  Tag identifier
   @param type Tag data type
   @param len  Length of the data in bytes
   @param data The data to append
   @return 0 on success; -1 on failure.
If there is not enough space to store the additional tag, errno is set to
ENOMEM.  If the type is invalid, errno may be set to EINVAL.  errno is
also set to EINVAL if the bam record's aux data is corrupt.
*/
int bam_aux_append(bam1_t *b, const char tag[2], char type, int len, const uint8_t *data);
```

What is the `type` and `len` should I use if I want to update `Alignment Score` by  bam_aux_del() and then add it back again with bam_aux_append() ?

**Comment by daviesrob** [comment]
For `AS`, `type` should be `i`, `len` should be 4 (= sizeof(int32_t)) and `data` should point to an `int32_t` value.

```
int32_t score = 42;
if (bam_aux_append(b, "AS", 'i', 4, (uint8_t *) &score) < 0) {
  fprintf(stderr, "Out of memory");
  return -1;
}
```

**Comment by jkbonfield** [comment]
That'll work, but it's inefficient.  It depends how you want to roll I guess.  The recommendation is to write integer values using the smallest size necessary.  Ideally bam_aux_append would do this automatically for type 'i' and convert appropriately, but sadly it doesn't.  That's probably a useful feature addition.

See the `sam_parse1` function for an example of how to manually choose the correct BAM encoding for an integer parameter.  Yes that's reading code, but when reading SAM it "writes" an in-memory BAM record so this is where the i to [cCsSiI] calculation happens in our existing code.

https://github.com/samtools/htslib/blob/develop/sam.c#L1312-L1338

**Comment by sfchen** [comment]
bam_aux_del() and bam_aux_append() may cause memory reallocation, right? Why don't implement a bam_aux_update for integer/float values?

**Comment by sfchen** [comment]
what's the structure for bam_get_aux()? Is it `1-byte char` followed by `data`?

**Comment by jkbonfield** [comment]
The problem here is a bam_aux_update function would also sometimes need to perform memory reallocation, even for integers.  This is because, for example, XX:i:100 can be store in BAM with type 'C' (uint8_t) while XX:i:500 would need type 'S' (uint16_t).  So there can only be very limited ability to change an integer.

If you wish to change a value from one very small integer to another very small integer then you can already sort of do that with bam_aux_get and direct memory manipulation. Bam_aux_get returns the a pointer to the TYPE byte, so 2 bytes after the XX (etc) ID.

Bam_get_aux (not note bam_aux_get!) returns a pointer to the entire set of aux data, which is serialised in the format listed in the BAM specification.  It'll be 2 byte  code, 1 byte type and then format specific number of bytes per type (eg nul terminated string for Z or H, 1, 2 or 4 bytes for type c,C,s,S,i,I,f,  something more complex for type B).  This just keeps going until we've consumed the remainder of the bam record (ie to b->data + b->l_data).

**Comment by daviesrob** [comment]
I decided to add the missing interfaces.  See pull request #694.
