### ISSUE TITLE
unused1 used to store custom value?

### ISSUE THREAD

**Issue by gkarthik** [samtools/htslib#697]
Hello,

I'm trying to store an amplicon index number(int) for each read within the BAM format. Can I use  unused1 in bam1_core_t to do so? Is unused1 intended for anything specific? 

Also, is there a better provision to store such custom values? 

Thank you!

**Comment by jkbonfield** [comment]
It appeared in 6d927dfa (Dec 2016), and may at some stage disappear again if we find a use for it ourselves.  It is not meant to be used by applications directly.  (Note that it's also only 8-bits of data, so may not be large enough for you anyway.)  You can of course still use it, but we'd strongly advise against it if you wish your code to be used by other people and you don't have any control over which version of htslib they'll be linking against.

You'd be better off defining your own structure that contains both bam1_t and additional fields at the end of that structure.  The bam reallocation functions manipulate (ie grow) bam1_t->data and not the bam1_t itself, thus any structure which starts with a bam1_t could be cast into that before passing over to htslib functions.

**Comment by gkarthik** [comment]
Ok I can do that. Thanks!
I also had a question about writing the struct into the bam file. Do I just rewrite the function bam_write1?

**Comment by jkbonfield** [comment]
I'd assumed before this was simply some in-memory tracking of information to speed up processing, but it sounds like you plan on writing this back to disk.   Don't do that by this means!  If you modify bam_write1 then you'll end up with something that isn't a BAM file and no one else will be able to process your data.

If you want to store data in BAM in a way that doesn't create a new incompatible file format then you need to look at the auxiliary tags.  There are htslib functions for doing this, ie `bam_aux_append` and friends.

You should create something with a new type, using the private name space (starting with a lowercase letter or X, Y or Z) and a numeric type code.  Eg in SAM this may be listed as `an:i:2`.   In BAM this is likely encoded in binary as `"anC\x02"` with "C" being 1 byte unsigned and \x02 meaning a byte holding the value 2, written using eg `bam_aux_append(b, "an", "C", 1, &data);` with data=2.  (Sadly bam_aux_append does require you to know how large the integer is - we ought add a bam_aux_append_int that takes values instead of addresses and appends the correct size.)

**Comment by gkarthik** [comment]
Thank you!
