### ISSUE TITLE
How does the bam_mplp_auto api work

### ISSUE THREAD

**Issue by EvanTheB** [samtools/htslib#755]
Hello,
I am trying to add a flag to either bedcov or bam2depth. I wanted to do a little more analysis of the distribution of coverage numbers, and could not find the usecase I need, postprocessing bam2depth in python is a little slow.

I could not work out how the bam_mplp_auto function works, sadly it is not documented in sam.h, and the two functions I mentioned seem to use it in different ways. Or at least what they are doing is too confusing for me. They seem to deal with skipped positions differently, and neither? dealt with skips after the last iterator.

* tid and pos are the low and high order words of the position? 
* What order are positions iterated through?
  * Are positions without reads skipped?

Not sure if the dev mailing list is still alive, this might belong there.

Here is my attempt so far: https://github.com/EvanTheB/samtools/commit/f21c6a6546122fb5916d10dc841d9d938eb3c7c5

**Comment by daviesrob** [comment]
Yes, the mpileup interface is not very well documented.

`tid` is the current target ID (header `@SQ` lines).

`pos` is the position.

The input file needs to be in position order to work, so `pos` will increase as you iterate through.

Locations with zero depth are skipped.  See for example where [mpileup fills in the gaps](https://github.com/samtools/samtools/blob/ae1f9d8809/bam_plcmd.c#L624) if asked to output zero-depth locations.

Looking at your code, you should check the return value from `calloc` and `realloc` for `NULL`.  Yes, I know the rest of the code doesn't do that, but I hope to get around to fixing it one day and always checking return values is a good habit for C programmers to get into.  Also remember that `realloc` doesn't zero the new bit of memory that it's allocated.  You need to call `memset()` after growing the array.

I assume that you're going to add an option to turn this on and off at some point.  Would you also consider other statistics?  Having made a depth histogram, it would be fairly easy to print out the median along with the upper and lower quartiles.

**Comment by EvanTheB** [comment]
Thanks @daviesrob I will have another look at mpileup. Yes I forgot my memset. I see now that sam is limited to 31 bit positions :/. I will have a go at getting it to work with just the case I need and add the rest at the end.

**Comment by EvanTheB** [comment]
I have continued:
https://github.com/samtools/samtools/compare/develop...EvanTheB:evan-depth?expand=1

I am getting a core dump so I have tried to clean up the mallocs. Core dump is in bgzf reading though, I am not sure.

**Comment by daviesrob** [comment]
I suspect that your problem might be that:
```
int64_t *new = realloc(histogram, histogram_size * sizeof **histogram);
```
should be:
```
int64_t *new = realloc(histogram[i], histogram_size * sizeof **histogram);
```

With memory problems, the actual bug can often be quite a bit before where you eventually crash.
`valgrind` is useful for finding the real cause, albeit slow.

If you have a recent gcc or clang, you can alternately try using address sanitizer.  You need to configure both htslib and samtools like this:

./configure CFLAGS='-g -Wall -fsanitize=address' LDFLAGS='-fsanitize=address'

Then build them and run the resulting samtools.

Note that mixing address sanitizer and valgrind is unlikely to work well.

The way that the `histogram` array is handled here adds quite a bit of complexity.  There are a couple of ways you could simplify it.  Either:

Expand `aux_t` with:
```
int64_t *histogram;
size_t histogram_size;
```
so you can get rid of the separate `int **` array.  It also allows the histogram for each input file to only grow as big as it needs to be.

Or:

Allocate a single `int64_t *histogram` of size `n * histogram_size * sizeof(*histogram)`, and then access it using `histogram[depth * n + i]`.  That way you only have one array to resize instead of lots of them.

**Comment by EvanTheB** [comment]
Probably the best code review of my life, thank you for your help. I had trouble as Asan seems to want to allocate a massive amount of vmem (>10TB). My cluster was preventing me from doing this due to ulimit  -v restrictions. And my smaller test cases were not triggering the bug. Valgrind helped though, and I realised my core dump stack trace was not working correctly. I had a quite a few errors. I am not used to the no declaration in for-loop style, and was using `i` too much. 

I'm now thinking I should turn this code into a bcftools plugin, as I am only calculating the depth in order to annotate VCF calls. Does that sound sensible or should I keep this in samtools bedcov?

Thanks again
