### ISSUE TITLE
tabix manuals page: section name

### ISSUE THREAD

**Issue by zx8754** [samtools/htslib#768]
In the tabix manuals, one of the section names is off, using Google Chrome (Version 56.0.2924.87). Maybe newline is missing somewhere. But it looks fine using IE11 (Version: 11.0.9600.19100).

http://www.htslib.org/doc/tabix.html

![tabix](https://user-images.githubusercontent.com/5212915/45477226-f74efa80-b738-11e8-96d9-621d4ed4f0e8.PNG)

**Comment by daviesrob** [comment]
Odd.  It's broken in Safari too.

Manually putting `<p></p>` tag between the closing `</dl>` and the opening `<h1>` gets the header back where it's supposed to be.

Possibly there should be a `.PP` tag before the `.SH` section header in the `tabix.1` file, although the `man` command seems to render it correctly.  Otherwise I'll have to tweak the script that renders the manual page to HTML to make sure it puts an empty paragraph before the heading.

**Comment by valeriuo** [comment]
To be tested with the new 1.10 web man page.

**Comment by valeriuo** [comment]
Fixed in http://www.htslib.org/doc/tabix.1.html
by https://github.com/samtools/www.htslib.org/pull/22
