### ISSUE TITLE
aclocal.m4

### ISSUE THREAD

**Issue by jkbonfield** [samtools/htslib#774]
A new issue as https://github.com/samtools/htslib/pull/733 cannot be reopened.

This debate is still raging.

@daviesrob claims the aclocal.m4 is not needed at all, in which case we should delete it.

Others seem to think it is needed, but it should not be checked in as we get dirty builds when following the build notes.  Options here are to remove the file or to fix the build notes (they explicitly state autoreconf may be used).

@jmarshall persuaded me before, hence why I closed the issue, that the appropriate m4 file must be checked in because it's not a standard part of the autotools package (it only exists if you have the pkgconfig bits installed).

With hindsight I now disagree, but rather than revert it, I think I'll punt to Rob who understands the whole pkgconfig auto-detection stuff a lot more (as he wrote it I think).

We don't bundle a compiler, just incase it hasn't been installed.  That would be lunacy! (Hello iRODS).  We don't bundle autotools just incase they're not installed either.  So I don't have an issue with needing pkgconfig installed if you want the aclocal.m4 part to be added either, especially if as Rob points out it does nothing whatsoever anyway.

**Comment by daviesrob** [comment]
The problem here is that `aclocal` is updating `pkg.m4` which is pretty much the only thing in our `aclocal.m4`.  We currently have serial 1, the latest seems to be serial 12, which is about [a year and a half old](https://cgit.freedesktop.org/pkg-config/log/pkg.m4.in).

There are a few possible solutions:

- Check in the updated `aclocal.m4`.
- Copy it into the `m4` directory and `m4_include` it.  Remove `aclocal.m4` as it's no longer needed.
- Just copy in the single function we use (`PKG_PROG_PKG_CONFIG`).
- Copy the single function and rename it.

With the first option we would eventually learn about newer versions of `pkg.m4` as `aclocal` would modify `aclocal.m4` again.

The second option seems to be enough to stop `aclocal.m4` from coming back, even if a newer `pkg.m4` is available.

The third means we only ship the bit we need, and the fourth would stop our possibly out of date version from interfering with the real `pkg.m4`.

I suspect the second option may be the best, but other opinions are welcome.

**Comment by zamaudio** [comment]
Sorry just saw this thread but already submitted a PR to fix it #1091

**Comment by jmarshall** [comment]
PR #1091 is an incomplete fix — choosing that route also requires adding `aclocal` to the instructions, at least.

I agree with @daviesrob that the second option is probably best: copy `pkg.m4` into the `m4` directory and `m4_include` it, and remove (but don't .gitignore) `aclocal.m4`.

**Comment by zamaudio** [comment]
Have updated my PR #1091 to reflect option 2.

**Comment by zamaudio** [comment]
Fixed in #1091
