### ISSUE TITLE
write to s3 buckets

### ISSUE THREAD

**Issue by LeoWelter** [samtools/htslib#776]
I've got samtools/bcftools compiled to use bam/vcf files directly from s3 buckets. Is it possible to write back to S3 buckets as well or only to local disk? use case: read VCF from a public S3 bucket and deliver the filtered VCF to another S3 bucket (private). (the script itself does not run on a AWS instance, but on our  local university server)

**Comment by jmarshall** [comment]
Have you tried it? What happened?

**Comment by daviesrob** [comment]
It doesn't work, because you need to know the number of bytes you're going to write when you open the connection.  As htslib mostly doesn't know this, it can't currently support writing to s3 buckets.

There are a couple of ways around this, but both are non-trivial.  We could either cache the data somewhere and then upload it on file close when we know how long it would be (not ideal), or we could add support for uploading the data in multiple segments.  The second of these requires us to support version 4 signatures and much more complexity in htslib's s3 plug-in as it will need to make more than one upload connection.

We're working on it, but it maybe a while before it will turn up.

**Comment by LeoWelter** [comment]
Thanks, in between I will go for the intermediate file solution and use the command line aws client to upload the files after they have been created.
A nice example can be found here: https://dariancabot.com/2017/05/07/aws-s3-uploading-and-downloading-from-linux-command-line/
