### ISSUE TITLE
Samtools not seeing cram index file when generating pre-signed AWS url

### ISSUE THREAD

**Issue by mebbert** [samtools/htslib#784]
Hello,

A large sequencing consortium recently released data for ~5000 new whole genomes that are hosted on `AWS`. They require the downloader to specify `--request-payer requester` for billing. Per the very helpful tip from @delagoya at #346, I was able to generate a pre-signed URL using `boto3`.

I only want to download specific regions from all samples, so I'm using `samtools view`. Unfortunately, `samtools` is complaining that `[main_samview] random alignment retrieval only works for indexed BAM or CRAM files`, eventhough I downloaded the `.crai` file for the associated `.cram` file *before* attempting to access the region of interest. `samtools` specifications state that it will look for a local `.crai` file. NOTE: I do receive the header for the `.cram` file.

Can anyone tell me why `samtools` doesn't see the local index file?

Here is my request and directory contents:

### Command
    samtools view -h 'https://[bucket].s3.amazonaws.com/path/to/cram/[sample].cram?AWSAccessKeyId=XXXXXXXXXXX&x-amz-request-payer=requester&Expires=XXXXXXXXXXX&Signature=XXXXXXXXXXXXX' chrX:XXXXXX-XXXXXX > test.sam

### Directory contents (after running command)

> [sample].cram.crai
> test.sam

I even tried mimicking the directory structure in the bucket (`path/to/cram/`) within the working directory, in case `samtools` was looking there. No dice.

I would appreciate any help.

**Comment by jkbonfield** [comment]
I'm not sure samtools supports this yet.  #346 is a proposal, rather than something that was implemented, but that aside there is also a bug still.

I experimented with some 1000 genomes public S3 data and there's clearly something broken here.

```
samtools view 'https://1000genomes.s3.amazonaws.com/data/NA12878/alignment/NA12878.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram' chr21:10013337-10013337
# 26 records returned
```

Now put any old ?a=b http parameter on and the entire behaviour changes.  It no longer does a range query, but downloads the complete file to <blah>.cram?a=b.crai.    This is clearly a bug somewhere in htslib.  (I can verify this with htsfile -c too).

**Comment by jkbonfield** [comment]
ARGH I see it now.

Normally doing a range query on http://<server>/<path>.cram will download http://<server>/<path>.cram.crai first.  It does this by simply adding .crai onto the filename.

Here we have http://<server>/<path>.cram?key=value and it is fetching http://<server>/<path>.cram?key=value.crai (and writing it to <path>.cram?key=value.crai).  The fetch is fine - it'll just ignore the ?key=value.crai - and we end up downloading the entire file as the index. Sigh.

The correct query is obviously http://<server>/<path>.cram.crai?key=value instead (as file <path>.cram.crai).

I'm guessing this was just never thought of when the http interface to samtools was first written.

**Comment by jmarshall** [comment]
Argh indeed :smile:

Fortunately the `?query` and `#fragment` conventions are part of the [generic URI syntax](https://tools.ietf.org/html/rfc3986#section-3) rather than specific to http(s). So it'd be appropriate to have smarts in _hfile.c_ to insert suffices at the end of the URI `hier-part` — delegating this to the individual backends via a new function pointer is unnecessary.

Alternatively this could be punted back to the user by exposing a way to explicitly specify index file names in samtools commands. Cf samtools/samtools#485, with its steady drip of people complaining to samtools about various network BAM repositories' inconvenient index file naming conventions.

**Comment by jkbonfield** [comment]
The issue has a bad enough outcome that while 485 can indeed work around this, a proper fix needs to be done too.

I'm happy with all URIs to have the same ?/# checking, but it's still a difference between the file backend and the URI backends.  That probably doesn't need a function pointer though.  I haven't had time to investigate how this code works yet as I'm in tangling myself in more threads at the moment. :-)

**Comment by mebbert** [comment]
Thank you both for the detailed explanations. Sounds like there isn't a workaround at present?

**Comment by mebbert** [comment]
Thank you, @jkbonfield. Can you help me determine exactly what `samtools` is looking for? 

I tried several iterations, but `samtools` still isn't seeing the index file. Here's the command I used to create the soft link (escaping the `?`, `=`, and `&` characters):

    ln -s [sample].cram.crai [sample].cram\?AWSAccessKeyId\=XXXXXXXXXX\&x-amz-request-payer\=requester\&Expires\=XXXXXXXXX\&Signature\=XXXXXXXXX.crai

Here are the directory contents after creating the soft link:

    lrwxrwxrwx 1 <user> <group>   45 Oct 29 19:21 [sample].cram?AWSAccessKeyId=XXXXXXXXX&x-amz-request-payer=requester&Expires=XXXXXXXXXXXX&Signature=XXXXXXXXXXXX.crai -> [sample].cram.crai
    -rw-r----- 1 <user> <group> 2.1M Jul 31 11:59 [sample].cram.crai
    -rw-r----- 1 <user> <group>  631 Oct 25 16:57 generate_presigned_s3_url.py
    -rw-r----- 1 <user> <group> 111K Oct 29 19:31 tmp.sam

Same `samtools view` command as original posting, but I still get the same error:

    [main_samview] random alignment retrieval only works for indexed BAM or CRAM files.

**Comment by jkbonfield** [comment]
Is it downloading a large file when you do the samtools view command?  If so, that's the filename you'll need to sybolic link the index too.  If not then I'm stumped.  Maybe there is some character in those keys that is causing it to choke.

I'd advise using something like "strace -s 200 -o strace.out  samtools view ...." and then after a while looking at the strace.out file and look for .crai.  You'll be able to see the queries it is sending to the remote end as well as the filename it attempts to open.  (That's how I discovered what was going on locally.)

I'm really not thinking this is a good workaround though!  We need to fix the bug, but it's not part of the code I'm that familiar with.  We can discuss it at our weekly meeting today.

**Comment by mebbert** [comment]
It doesn't download anything. Just gives the error. I believe @mp15 saw the same behavior on #346.

**Comment by mebbert** [comment]
Any news come out of your weekly meeting?

**Comment by jkbonfield** [comment]
I'm working on a fix, starting from @jmarshall's PR.

For what it's worth, I realised we can trick another bug to almost doing what we want!

Firstly, manually download the index via wget, using any ?param=value parameters as needed. Eg with wget -O:

```
wget 'http://1000genomes.s3.amazonaws.com/data/NA12878/alignment/NA12878.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram.crai?a=b&c=d' -O NA12878.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram.crai
```

Then, when doing a samtools query, add your own parameter to the end specifying the local filename starting with a slash.  This tricks the local filename parsing (due to another bug) to look elsewhere.  Ie:

```
samtools view -c 'http://1000genomes.s3.amazonaws.com/data/NA12878/alignment/NA12878.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram?a=b&c=d&local=/NA12878.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram' chr21:10013337-10013337
```

Hideous!

**Comment by mebbert** [comment]
But yet so beautiful! It works!

I have to say that this is a first for me. I've never had a bug that worked in my favor--and certainly not one that works around the bug that was working against me!

**Comment by cmdcolin** [comment]
This is sort of unrelated...but maybe a little related

I believe get this error "[main_samview] random alignment retrieval only works for indexed BAM or CRAM files." when the download of the bai was incomplete on a remote file. I thought I was going a little crazy till I realized the incomplete bai was in the same folder that I was doing this
