### ISSUE TITLE
memory leak? with bam + hts_set_threads

### ISSUE THREAD

**Issue by brentp** [samtools/htslib#822]
related to #577 

I've noticed this in other code and have finally been able to make a reproducer. If I repeat the code below on cram, there is no leak. If `hts_set_threads` it not used (on bam or cram) there is no leak. However, as-is, there's a rapid increase in memory. I think this can be replicated on any bam with a few thousand contigs. The leak becomes apparent at ~3000 in my case. It is not subtle, by tid of 20K it is using ~10G of memory. With cram it is not even measurable. (I ran in valgrind and it found 0 leaks, I assume that's because it turns off threading?)

This persists with samtools develop pulled on Feb 4th 2019.

```C
#include "htslib/sam.h"
#include "htslib/hts.h"
#include <stdio.h>
#include <unistd.h>


int main(char *argv[], int argc) {
    // if I change this to pigeon.cram which is a simple samtools view of the bam there is no leak.
    char *fname = "pigeon/pigeon.bam";

    htsFile *hf = hts_open(fname, "r");
    hts_set_fai_filename(hf, "pigeon/pigeon.fasta");

    // if I comment out this line, there is no memory leak.
    hts_set_threads(hf, 3);

    bam_hdr_t *hdr = sam_hdr_read(hf);
    hts_idx_t *idx = sam_index_load(hf, fname);
    bam1_t *rec = bam_init1();


    int i;
    int slen;
    for(i = 0; i < hdr->n_targets; i++){
        fprintf(stderr, "target: %d\n", i);
        //hts_itr_t *qiter = sam_itr_queryi(idx, i, 0, hdr->target_len[i]);
        hts_itr_t *qiter = sam_itr_queryi(idx, i, 0, 1);
        if (qiter == NULL) {
            fprintf(stderr, "BAD\n");
            return 2;
        }
        slen = sam_itr_next(hf, qiter, rec);
        while(slen >= 0) {
          slen = sam_itr_next(hf, qiter, rec);
        }
        if(slen < -1) {
            fprintf(stderr, "BAD slen\n");
            return 3;
        }
        hts_itr_destroy(qiter);
    }

    bam_destroy1(rec);
    hts_idx_destroy(idx);
    bam_hdr_destroy(hdr);

    hts_close(hf);
    return 0;
}
```

**Comment by daviesrob** [comment]
Thanks for the test case.  Profiling with [tcmalloc's heap profiler](https://github.com/gperftools/gperftools) shows that all the memory is being used by `bgzf_mt_reader()` calling `pool_alloc()` to make new job structs.  It looks like these aren't being freed properly when the reader seeks to the next reference, so they slowly accumulate.  At close time they will be freed, when the pool is destroyed, which is why Valgrind doesn't report anything.

**Comment by daviesrob** [comment]
Hmm, it looks like the problem is that `bgzf_mt_seek()` calls `hts_tpool_process_reset()`, and the latter function has no way of cleaning up data associated with jobs on the input queue.

The quick solution might be to make a new `hts_tpool_process_reset()` that can take callbacks for freeing the job argument and any result data.

More long-term would be a way of telling the bgzf layer exactly which bits of file are needed so that the thread reader doesn't get too far ahead resulting in discarded work.

**Comment by brentp** [comment]
@daviesrob thanks for looking into it and diagnosing!
