### ISSUE TITLE
kstring.c: Incorrect return value for kvsprintf on windows

### ISSUE THREAD

**Issue by Jiefei-Wang** [samtools/htslib#854]
Hello htslib devs,

our group has encountered a bug when developing a package in Bioconductor. This bug is only specific for Windows. 

The function `kvsprintf` incorrectly return value -1 when the input `kstring_t* s` is not large enough to hold all the values in `va_list ap`. The root cause is the return values of `vsnprintf`. if the character number n is not sufficiently large and cause a truncation of the output, on Windows `vsnprintf` will return -1 and on Linux it returns the length of untruncated output. This behavior breaks the function `kvsprintf` on Windows since it assumes `vsnprintf` always returns the length of the untruncated output.

The problem with the `kvsprintf` can be verified by:
```
#include <stdarg.h>
#include <stdio.h>
void test(char* str,int len,...) {
	va_list ap;
	int l;
	va_start(ap, len);
	l = vsnprintf(str, len, "%s", ap);
	printf("total length:%d\n",l);
}

void main() {
	//Insufficient character length
	int len = 10;
	char* str = (char*)malloc(len * sizeof(char));
	char* arg = "LLLLLLong test";
	test(str,len, arg);

	//Try it with larger size
	len = 1000;
	str = (char*)malloc(len * sizeof(char));
	test(str, len, arg);

}
```
Compile with gcc, on windows the output is:

> total length: -1
> total length: 14

On Ubuntu it is:

> total length: 14
> total length: 14

**Comment by jkbonfield** [comment]
There are two vsnprintf implementations on windows, one with the modern API and one without.   Eg see this from https://github.com/samtools/htslib/commit/75d9f0d9a973898686a51b60277f239c7e729ea5 2 years ago:

> - Setting of _POSIX_C_SOURCE=600 define so that snprintf return values
  work and to enable %lld and %z formatting options.

I have a horrible feeling though that defining that causes other problems.   It'll be compiler specific too no doubt.

**Comment by daviesrob** [comment]
It looks like the problem is that [Rhtslib](https://github.com/Bioconductor/Rhtslib) is not running htslib's configure script, which is pretty much compulsory to get a working build on Windows.

The correct variable to set is actually `_XOPEN_SOURCE=600`.  (See da5c0c7b, although it looks like both this and 75d9f0d manage to blow away `CPPFLAGS` in the process of setting it so we may have another bug to fix there.)  We could add something to set  `_XOPEN_SOURCE=600` for MinGW users in the stub `config.h` that gets made if you don't run `configure`, although that wouldn't solve other issues like .dll extensions.

The fix in for this problem in Bioconductor/Rhtslib@9b55d87 (and the next few commits) is wrong because the format string is interpreted differently between the two versions of `kvsprintf` on Windows, and htslib expects the POSIX-compliant one.  So those changes should be reverted in favour of either running htslib's configure script, or at least adding `-D_XOPEN_SOURCE=600` to [Makevars.win](https://github.com/Bioconductor/Rhtslib/blob/master/src/Makevars.win).

**Comment by Jiefei-Wang** [comment]
Thanks for your responses @jkbonfield and @daviesrob . That's the project we are talking about. I will let Hervé@hpages know.

**Comment by hpages** [comment]
Will look into using the `_XOPEN_SOURCE=600` flag, thanks!

Just to provide some context: Rhtslib is a Bioconductor package (http://bioconductor.org/packages/Rhtslib) and Windows users are expected to install the package binary. This binary is produced on our Windows builders which we fully control. This gives us the luxury to skip the configure step. The reason we really like to be able to skip this step is that configure scripts in R packages are causing too much pain on Windows.
