### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by iqbal-lab** [samtools/htslib#86]
Would it be possible to add (64 bit) Windows support to htslib?
I've just emailed Petr Danecek, who says he is unaware of anyone already having done this. If noone is already doing it, we will have a go in my team, but we need only a tiny fraction of htslib functionality (reading BAM, fastq, fastq.gz).

**Comment by nhayden** [comment]
Hi, I'm one of the maintainers of the [Rsamtools](http://bioconductor.org/packages/release/bioc/html/Rsamtools.html) package for [Bioconductor](http://bioconductor.org/) project. I'm trying to get the new and improved htslib into an R package as a replacement for the old samtools. We support Windows with a toolset dictated by the [R](http://www.r-project.org/) project, which currently means MinGW-w64. MSVC is not of interest.

Because the (busy-)work involved to get htslib ready for MinGW is non-trivial and supporting Windows is of interest to the htslib project, it seems like it'd be worth sharing upstream to see what has already been ruled out. (Before I go ahead with my proposal I should mention that I am an Autotools novice.)

As I started busy-working through htslib code to adapt it to MinGW I stumbled across [Gnulib: The GNU portability library](https://www.gnu.org/software/gnulib/), which looks like just what the doctor ordered. The caveat is it relies on use of Automake and Autoconf in the project. At this time all the modules I think are needed from Gnulib are licensed as LGPLv2+. IANAL but that seems to work with the current htslib licensing. Gnulib has a [list of ISO C and POSIX Header File Substitutes](http://www.gnu.org/software/gnulib/manual/gnulib.html#Header-File-Substitutes) for what's been addressed for which platforms. I think Gnulib would obviate the need for most of the platform-/feature-checking macros in the source code.

And have you considered Autotools independent of Gnulib? Elements of the build setup look like they were once part of an Autotools-based project. I think much of the complexity of the current Makefile would be addressed automatically by Autotools, while also affording all the configuration goodness that comes with the `./configure` `make` `make install` incantation.

**Comment by jmarshall** [comment]
As noted in e.g. #137, we plan to have an autoconf-maintained `configure` script but not to use automake or the other autotools.  This will be landing soon, as it is a prerequisite for merging #146.

@nhayden: What particular functions have you found to be missing in your R / MinGW-w64 environment?  We would probably prefer to work around such problems in ways other than Gnulib, so evaluating what is involved really depends on exactly which library functions are problematic.

**Comment by nhayden** [comment]
I adapted HTSlib using Gnulib and Automake, and then used Libtool to enable building the shared library versions of htslib. If you’d like to try building it I suggest cloning from https://github.com/nhayden/htslib and running `autoreconf -i && ./configure --disable-dependency-tracking && make && make check`.

We've released an R package [Rhtslib](http://bioconductor.org/packages/devel/bioc/html/Rhtslib.html) that contains htslib. The htslib unit tests (pulled prior to iRODS support) pass on Linux (Ubuntu and Fedora), Mac OS X (10.6.8 and 10.9.5), and MinGW-w64 (Windows).

I compared time required to build various targets on my Ubuntu laptop. The `./configure` step (not included) takes 10 secs; bin-programs includes bgzip, tabix, and htsfile. Time is in seconds:

|                         targets          | nhayden:develop | samtools:develop |
| :--------------------------------------- | --------------: | ---------------: |
|`make bin-programs shared-only-libhts`    |            12.7 |             23.7 |
|`"               " static-only-libhts`     |      	     12.8 |             12.1 |
|`"               " static-and-shared-libhts` |            24.2 |             23.8 |

So you can see how competitive the Gnulib version is. The discrepancy on the shared-only-libhts is because samtools:develop also needs to build the non-PIC .o files.

##### Highlights of the Gnulib / Autotools approach

* Streamlined build system with near-zero maintenance cost, added configuration
I invite you to check out the simplicity of the [Makefile.am](https://github.com/nhayden/htslib/blob/develop/Makefile.am) and [test/Makefile.am](https://github.com/nhayden/htslib/blob/develop/test/Makefile.am) in comparison to the current build system. Each .c or .h file appears exactly once. The setup in my [develop branch](https://github.com/nhayden/htslib) handles installing headers and man pages, and automatically offers a slew of configuration options that are currently missing or hand-maintained in the htslib Makefile.

* Near-automatic portability
With Gnulib I was able to make the codebase work on MinGW-w64 with very few changes to the codebase--mostly adding `#include “config.h”` to source files and adding the `O_BINARY` flag where appropriate. With Gnulib integrated the number of supported platforms has increased dramatically, and it’s easy to add modules if new portability issues come up.

* POSIX-style programming, cleanup of source
I removed some preprocessor platform / feature tests, but could have removed many more, because this is now handled by Gnulib. I think the only preprocessor platform checks that will remain will test for when O_BINARY is necessary, and where the obsolete `valloc` function is used since it’s not available for Windows. Another advantage is going forward you’ll be able to continue writing htslib in a POSIX-y way and Gnulib will make it “just work.”

##### Integration

I would have preferred to submit a corresponding pull request, but I have not pulled from htslib/develop since iRODS support was added due to the complexity of integrating the configury. I've tried merging from develop branch and most everything merges automatically. I have faked version.h-related stuff and have not updated the pkg-config file.

If you are interested in the Gnulib direction I would be happy to work with you to integrate iRODS support and other configury. I welcome contributions and feedback.

##### What’s missing from MinGW-w64 / R environment

@jmarshall: It's hard to get an accurate count, as Gnulib operates in terms of "modules" of portability code, and it automatically pulls in module dependencies. Some of the portability issues are trivial, e.g., defining the missing `ETIMEDOUT` symbol, while others require significant expertise; all Unix-style file control / file system and socket features are missing, for example.

The list of modules--which roughly correspond to either missing / incomplete headers or missing components of unistd.h--is as follows:
* _headers_: alloca, arpa_inet, fcntl, inttypes, netdb, stat-size (size-related components of sys/stat.h), stddef, stdint, stdlib, string, sys_select, sys_socket (and modules recv, send), sys_stat, sys_time, unistd
* _unistd.h_: fdatasync, getpagesize,

###### Licensing

Almost all the modules are LGPLv2+ (or unlimited or public domain); stat-size is GPL. I imported stat-size because the `st_blksize` member is missing from `struct stat`.

Is the GPL a problem? It seems like it would be manageable to find a workaround for st_blksize's missingness, or even just fake it with reasonable values for relevant platforms. If I don't import the stat-size module all imported modules and deps are LGPLv2+, unlimited, or public domain.

Again, I welcome contributions and feedback.

**Comment by wookietreiber** [comment]
:+1: @nhayden

**Comment by mp15** [comment]
For htslib code LGPL is not a problem, but GPL is. The reason for this is that we are pitching htslib as a reference implementation that anyone (including commercial companies) can take and integrate into their code instead of writing their own implementation.

**Comment by jkbonfield** [comment]
On Fri, Mar 13, 2015 at 03:24:40AM -0700, Martin Pollard wrote:
> For htslib code LGPL is not a problem, but GPL is. The reason for
> this is that we are pitching htslib as a reference implementation that
> anyone (including commercial companies) can take and integrate into
> their code instead of writing their own implementation. 

I am not sure it matters greatly if it is simply for the Windows
version.  Essentially we'd be dual licensing it and all windows code
inherently then becomes GPLed, but the primary code is still also
released under MIT.

However I'm no expert and it's a valid concern that needs consideration.


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jkbonfield** [comment]
On Thu, Mar 12, 2015 at 04:15:44PM -0700, Nate Hayden wrote:
> Almost all the modules are LGPLv2+ (or unlimited or public domain);
> stat-size is GPL. I imported stat-size because the `st_blksize` member
> is missing from `struct stat`. 

One question I have on Windows is, does st_blksize actually work? Ie
does it change per file system type?  Or alternatively is it just
botched in there as a constant figure (eg 4096) in order to make code
compile correctly by exposing this field in the structure?

If it is the latter then for sure the best route is simply to have a
#ifdef in the one place in htslib that accesses this variable.  Make
it return 0 instead and then hfile_init will fall back on picking its
own default for "capacity".


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by nhayden** [comment]
stat-size module
- @jkbonfield It looks like the stat-size module (see [`stat-size.h`](https://github.com/nhayden/htslib/blob/c352f109723a1cd99b9690f9f2ab2f9e7f9a354a/lib/stat-size.h), rather readable) relies on `DEV_BSIZE`, `BSIZE`, or `BBSIZE` to be defined or it falls through to `4096` as you guessed. (`param.h` exists in the MinGW-w64 / R environment but is missing those constants.) From there it does some extra probing on platforms for cases where relevant `struct stat` members can be misreported. I've [updated `hfile.c`](https://github.com/nhayden/htslib/commit/600962a307cc49755814b7c90a5cc756472e9423#diff-d4154a6c038e691a1f95f89356359ef0) to return `0` if `struct stat` lacks `st_blksize` member, per your suggestion.

Licensing
- @mp15 @jkbonfield I updated so all included Gnulib modules licensed under LGPLv2+, public domain, or unlimited: 600962a307cc49755814b7c90a5cc756472e9423

With licensing concerns out of the way, what are your thoughts on the Gnulib direction?

**Comment by dalexander** [comment]
+1

**Comment by dalexander** [comment]
my company has some internal windows-based tooling that we need to migrate to read BAM, we have had to roll our own windows support using mingw-w64... I know windows support isn't a big priority for you guys but I hope we could eventually get it in upstream

**Comment by ctsa** [comment]
I just submitted a small PR for binary mode in all bgzf_*open calls on windows. Note these edits are based on msvc builds, participants on this thread might have comments re mingw/cygwin:

https://github.com/samtools/htslib/pull/283

**Comment by dridk** [comment]
I m trying to compile htslib using mingw32 on windows. Is that possible ?

**Comment by jrandall** [comment]
@dalexander it looks like you now have a completely working mingw-w64 build that does not require anything other than permissively licensed code, is that correct? Do you think that's ready to be submitted as a PR?

**Comment by hzpc-joostk** [comment]
I was able to compile Windows binaries using MSYS2: 

![image](https://cloud.githubusercontent.com/assets/10130907/21315932/b089898a-c5fe-11e6-9f20-4acf03f3f78d.png)

I was able to run the following executables directly from Windows:

- bcftools.exe
- samtools.exe
- bgzip.exe
- tabix.exe
- htsfile.exe
- ace2sam.exe
- maq2sam-long.exe
- maq2sam-short.exe
- md5fa.exe
- md5sum-lite.exe
- wgsim.exe

But only in presence of the following MSYS2 DLLs in the same directory as the exe: 

- msys-ncursesw6.dll
- msys-z.dll
- msys-2.0.dll

**Comment by dridk** [comment]
@hzpc-joostk Could you tell me the step by step process to compile htslib for windows  ? Which repositories, which compiles ( mingw or emulate with msys) etc... 
Thanks!

**Comment by dridk** [comment]
I finally successed to compile on windows and link htslib to my Qt application. Here are the step : 

## htslib Compilation with mingw32
- Install [Msys2](https://msys2.github.io/) and follow the guide from the website
- There are 3 MSYS2 shell. ( MSYS2 , mingw32, mingw64).  Open MSYS2 MinGW32-bits client
- From the shell, Install libtool and gcc as follow . ( mingw-w64 means for 32 and 64 bits)

       pacman -S mingw-w64-i686-libtool
       pacman -S mingw-w64-i686-toolchain
       pacman -S wget 
       pacman -S unzip

- Get the repository from  https://github.com/nhayden/htslib and compile it 

      wget https://github.com/nhayden/htslib/archive/develop.zip
      unzip develop.zip 
      cd htslib-develop
      autoreconf -i
      ./configure --disable-dependency-tracking
      make
      make check

- You should have now a .libs folder which contains libhts.a

## Link htslib to a Qt application on windows 

- Install Qt from https://www.qt.io/download/ and select mingw32 compilator. 
- From QtCreator, Tool > Options > Compiler  , Add the mingw compiler from the msys2 folder.   
![image](https://cloud.githubusercontent.com/assets/1911063/21530390/c9520b06-cd40-11e6-9d5b-d92d4442f3d9.png)
- Then configure a kit from Tool > Option > Compiler as follow : 
![image](https://cloud.githubusercontent.com/assets/1911063/21530406/f46ab112-cd40-11e6-84f2-ff673b6d30ef.png)
- You now can create a new project , file > new >  Application and set the msys2 as the tool chain.
- To link htslib previously compiled , just add the following line in your *.pro file after you copied the htslib-develop folder inside your project.

       LIBS += -L$$PWD/htslib-develop/.libs/ -lhts
       INCLUDEPATH += $$PWD/htslib-develop
       DEPENDPATH += $$PWD/htslib-develop

 - If you are not familiar with C langage, I create a Qt wrapper in C++. Just add those two files in  your project. 
[qtabix.cpp](https://github.com/labsquare/CuteVCF/blob/master/qtabix.cpp)
[qtabix.h](https://github.com/labsquare/CuteVCF/blob/master/qtabix.h)
Then you can parse a Vcf.gz file using the following lines : 

```
    QTabix tabix("C:/myfile.vcf.gz");
    tabix.setRegion("chr1");
    QByteArray line;
    while (tabix.readLineInto(line))
      qDebug()<<line;
```

**Comment by hzpc-joostk** [comment]
Oh wow. @dridk That is awesome! Very well done. 👍 I'll check into it next week. Cheers and happy new year y'all!

**Comment by SoapGentoo** [comment]
@jmarshall would you be willing to accept CMake next to the autoconf-based build system? CMake as a build system is more composable than Autoconf+Make and has better Windows support. Many projects have dual CMake/Autoconf-based buildsystems. Would you be willing to accept such an addition if I took the time to write it? This is especially important for industry, where most C/C++ projects use CMake over Autotools/Make based solutions.

**Comment by jmarshall** [comment]
@SoapGentoo: Since you ask me in particular, I will give you my opinion, which is unchanged from every other time you have told us we need to change our build system.  You seem to think we are not using CMake because we are unaware of it; instead, we are not using CMake because we are [familiar with it](https://twitter.com/jomarnz/status/826760391803944960), have considered it, and prefer an alternative.

FYI every time you reappear to teach me to suck eggs once again, I become more disinclined to listen to a word you say on any topic.  When you suggest that HTSlib should maintain two duplicate complex build systems in parallel, doubly so.

To date, building via Cygwin or MinGW has been our Windows story, and at present there are very few remaining problems there (and they are becoming fewer with @jkbonfield's laudable anti-`alloca()` crusade).  If there are suitably motivated Windows HTSlib users, it would be good to have a native Windows build story.  It seems to me that the best way to do that would be to have a [bespoke config-win.h for Windows](https://twitter.com/jomarnz/status/826732209763655681) to avoid needing to run _configure_, along with a trivial (and ideally generated from a file listing) Visual Studio project.

Other maintainers may have other opinions.

**Comment by jkbonfield** [comment]
Firstly, we really do need to go through all our old issues culling some or at least re-evaluating which ones need working on (this included in that category).  We are working on Windows support, as a background project really, but it's getting there.

Cmake is a total disaster - I'm with @jmarshall here.  My heart sinks any time I download a package with a cmake config as I know it'll be a total pain to build and install!  Yes we could have it in *addition* to autoconf, but are you willing to act as user support for everyone that asks about cmake usage, and willing to keep it up to date for ever, after any code reorganisation or new source files appearing?

I also dispute the claim that most C/C++ projects using Cmake over Autotools/Make based solutions.  I see maybe 1 in 20 packages I download using cmake.  I don't see why industry would be so wildly different to open source (and we are open source here, not in industry).

If we were to add anything to windows build support it would be a user-driven (ie "contrib" directory style) MSVC project file.  It also needs new windows specific unistd.h to #define away all those POSIX things that Miorosoft don't want to support but kept anyway with subtly different function names.  It's doable (I did it with another package one), but dirty.  There needs to be a compelling reason why this is necessary though.

I suspect our users want, more than anything else, prebuilt binaries so they can simply avoid the whole "how to compile on windows" question.  Therefore building under mingw and packaging the binaries seems like the best solution.

**Comment by yarongolan** [comment]
would someone be willing to either provide a precompiled bcftools or provide information about how to build it in mingw/MSYS2?

**Comment by hzpc-joostk** [comment]
@yarongolan , have you tried the approach [mentioned before](#issuecomment-269533620) by @dridk ? You may want to skip the Qt part. That is how I did it, sort of. :)

**Comment by yarongolan** [comment]
@hzpc-joostk thanks for the quick response - I was able to compile htslib, but not to compile bcftools

**Comment by sjackman** [comment]
Since it's not mentioned so far in this thread, for those using Windows 10, Windows Subsystem for Linux (WSL) is a good option for those wishing to use POSIX software on Windows.

I maintain Linuxbrew, the port of the Homebrew package manager to Linux, which also works on Windows with WSL. You can install `htslib` on Windows with…
```sh
# Install Linuxbrew
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
# Install htslib
brew install htslib
```
See http://linuxbrew.sh/#install-linuxbrew

**Comment by yarongolan** [comment]
@servicemanli, I strongly recommend installing Ubuntu or other distribution under Windows 10 (which now has a linux subsystem) and compiling/installing these tools natively, either by compiling or using package manager. Ubuntu 18.04 on the Windows Store, for example, would work for you.

**Comment by hzpc-joostk** [comment]
Hi @servicemanli, 

It is best you run htslib in a unix environment; try the suggestion of @yarongolan. Or compile htslib by yourself using MSYS as I have tried.

Here are the executables, DLLs and some Perl scripts zipped. It has been a while I have compiled these (version 1.3.1 on 19 Dec 2016):

[SAMtools.zip](https://github.com/samtools/htslib/files/2370362/SAMtools.zip)

Please note, as mentioned before, you need to have the MSYS DDLs in your path to work.

> I was able to run the following executables directly from Windows:
> 
> - bcftools.exe
> - samtools.exe
> - bgzip.exe
> - tabix.exe
> - htsfile.exe
> - ace2sam.exe
> - maq2sam-long.exe
> - maq2sam-short.exe
> - md5fa.exe
> - md5sum-lite.exe
> - wgsim.exe
> 
> But only in presence of the following MSYS2 DLLs in the same directory as the exe:
> 
> - msys-ncursesw6.dll
> - msys-z.dll
> - msys-2.0.dll

Cheers.

**Comment by valeriuo** [comment]
Windows support in htslib has been added since version [1.6](https://github.com/samtools/htslib/commit/75d9f0d9a973898686a51b60277f239c7e729ea5). You can download [MSYS2](https://www.msys2.org/), install the necessary dependencies (zlib, libbz2, liblzma, libcurl, curses), fetch the software from github ([htslib](https://github.com/samtools/htslib/releases/latest), [samtools](https://github.com/samtools/samtools/releases/latest), [bcftools](https://github.com/samtools/bcftools/releases/latest)), either as clone repos or tarballs, and build according to shipped instructions.

**Comment by servicemanli** [comment]
Thank you all @yarongolan@hzpc-joostk@valeriuo. I will try.

**Comment by bolunfeng** [comment]
How can this project be compiled with MinGW and make on Windows 10? Who can give an execution order? I really need this way to compile. Because other third-party libraries in my project are compiled with MinGW.

**Comment by dridk** [comment]
You can use dynamic library: -L$$PWD/win32 -lhts
You can download my win32 folder here https://github.com/labsquare/CuteVCF/tree/master/win32
