### ISSUE TITLE
cram_tell declared but not defined

### ISSUE THREAD

**Issue by mtmorgan** [samtools/htslib#915]
It seems that `cram_tell()` is declared but not defined?

```
htslib develop$ grep -r cram_tell *
cram/cram_io.h:int64_t cram_tell(cram_fd *fd);
htslib develop$
```

**Comment by daviesrob** [comment]
Thanks.  It looks like this function appeared and disappeared during the development of #608, but the declaration got left behind.

Note that HTSlib's official API is in the `htslib/*.h` files only.  Please don't use functions in other header files as they may be changed without notice.

**Comment by mtmorgan** [comment]
Thanks, probably it was left out of htslib/*h for accidental reasons, too...?

**Comment by jkbonfield** [comment]
No - the CRAM code arrived lock, stock and barrel as a copy from Staden io_lib (https://github.com/jkbonfield/io_lib/) and we didn't expose anything to the public API by design until we worked out which bits were relevant.  The theory is that you shouldn't need to be manipulating CRAM directly and should use the format agnostic alternatives instead.
