### ISSUE TITLE
CRAM with no quality values

### ISSUE THREAD

**Issue by Fazulur** [samtools/htslib#941]
Dear Team,

I am trying to convert whole genome bam to cram using samtools. I used the below command to get lossless & lossy cram.

lossless lev9  command
samtools view -T hs37d5.fa -@ 32 -C --output-fmt-option level=9 -o test-losslesslev9.cram test.bam

lossy level9
samtools view --output-fmt cram,version=3.0 --output-fmt-option lossy_names --output-fmt-option level=9 -T hs37d5.fa -@ 32 -o test-lev9.cram test.bam

I am not able to find options to remove all quality values & store only sequence to cram file which will be used for visualization purpose. 
http://www.htslib.org/doc/samtools.html
In cramtools specification it was mentioned we can compress bam to cram without quality values, but cramtools is no longer supported and recommending to use samtools only. 

Could you please suggest me the options to get cram without quality values?

Thanks In Advance
Fazulur Rehaman

**Comment by daviesrob** [comment]
You might want to try using [crumble](https://github.com/jkbonfield/crumble) for this.  It's a lossy quality value compressor for cram.  It won't normally get rid of all the quality values, but whatever remains will take up very little space.

If you want to get rid of all of them, I don't think there is a `samtools` option to do this but it's not too difficult to make something that does.  For example, you can convert to SAM, set column 11 (QUAL) to `*` and then convert the result to CRAM:

```
samtools view -h test.bam | perl -lne 'if (/^@/) { print } else { @F = split(/\t/, $_); $F[10] = "*"; print join("\t", @F); }'  | samtools view -T hs37d5.fa -@ 32 -C --output-fmt-option level=9 -o test-lev9.cram -
```

Another method would be to convert to CRAM, then re-encode it using `--input-fmt-option required_fields=0x1bff` to drop the quality values (unfortunately this option does not currently work for BAM or SAM, which is why it has to be done in two stages):

```
samtools view --output-fmt cram -T hs37d5.fa -@ 32 test.bam | samtools view --output-fmt cram,version=3.0 --output-fmt-option lossy_names --output-fmt-option level=9 --input-fmt-option required_fields=0x1bff -@ 32 -o test-lev9.cram -
```

**Comment by Fazulur** [comment]
Dear Daviesrob,

Thanks a lot for your detailed explanation & commands. It will help me a lot. I will try this.

Thanks & Regards
Fazulur Rehaman

**Comment by jkbonfield** [comment]
You are correct that in the CRAM format there is a way to completely avoid storing quality values.  Htslib supports decoding of this, but it doesn't have any way to enable it.  Our preferred solution is quality reduction through e.g. Crumble or similar tools or simply setting the quality string to "*" (and storing it still, as it's an irrelevance in space then).  Maybe we should reconsider, but that's not an immediate solution.   Ideally we'd have a general filter option, acting more strictly than the required_fields hint, that also permits dropping aux tags for example.

As an amendment to @daviesrob second command line above, I'd add a "-u" to the first one to speed it up so there is no need to use multiple threads for compression. You can also combine multiple output-fmt-options together with the format with the "-O" option.  Eg:

```
samtools view -T hs37d5.fa -u -C in.bam | samtools view -@32 -O cram,lossy_names,level=9 --input-fmt-option required_fields=0x1bff -o out.cram
```

**Comment by Fazulur** [comment]
Dear James Bonfield,

Thanks a lot.

Thanks & Regards
Fazulur Rehaman

**Comment by Fazulur** [comment]
Dear Team,

As per above suggestions, I ran samtools to get cram without quality and for 139GB bam it took around 2 hours to convert to cram with size of 22GB.

I got the below message when I ran 

[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/1b22b98cdeb4a9304cb5d48026a85128": Protocol not supported
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/1b22b98cdeb4a9304cb5d48026a85128": Protocol not supported

Is it ok to ignore this message, because job continue without any issues. Please confirm?

Thanks & Regards
Fazulur Rehaman

**Comment by jkbonfield** [comment]
This is because it's trying to find the reference remotely, presumably because it wasn't specified locally and your compilation of htslib didn't include libcurl.   A few suggestions here.

1. Add -T ref.fa to all of your samtools lines, not just the first one. (It can remember the location in some scenarios only)

2. Compile your htslib with libcurl.  The "protocol not supported" is presumably because you used "make" instead of "./configure; make" or ran configure using the option to disable curl.  Curl is the only way htslib can access https and s3.

3. Consider setting up a local cache of reference sequences so you don't need to keep specifying -T or to fetch remotely.  See `REF_PATH` and `REF_CACHE` section of the samtools manual page.

I'm unsure why the job continued without complaint.  Maybe it managed to find a copy locally still and this was just a complaint about the first method failing.

**Comment by jkbonfield** [comment]
Also, if you're interested in knowing where your CRAM space is being spent, the [io_lib](https://github.com/jkbonfield/io_lib/) `cram_size` tool can give you a break down per type of data (QS being quality score).

(At some point I should move that, `cram_dump` and `cram_filter` over to samtools.)

**Comment by Fazulur** [comment]
Dear James Bonfield,

Thanks a lot for your quick response & thanks for tool on CRAM space.
After adding -T ref.fa to all samtools lines, it worked without any protocol not supported message.
I will also try compiling samtools htslib with libcurl & check the same command again.

Thanks & Regards
Fazulur Rehaman
