### ISSUE TITLE
cram_get_ref- Failed to populate reference error

### ISSUE THREAD

**Issue by Sames-Jtudd** [samtools/htslib#950]
Hi there, 
Im running a pipeline (battenberg from the sanger) that uses htslib to decode CRAM files. 
One such command (ascatSnpPanelGenerator.pl) takes the reference file (.fa) as an argement. 
However apparently this doesnt get passed to htslib, as I get a "Failed to populate reference error"

I have tried setting the variable REF_PATH to the ref path and it still doesnt work. 
I read another issue page where it was suggested to use seq_cache_populate.pl. Ive download this script and run it. eg
./seq_cache_populate.pl -root path/Md5_ref/ path/GRCh38.fa
After running this I set 
REF_PATH and REF_CACHE to path/Md5_ref
however if I run samtools view cram_file.cram I also get an error

[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/6aef897c3d6ff0c78aff06ac189178dd": Protocol not supported
[E::cram_get_ref] Failed to populate reference for id 0
[E::cram_decode_slice] Unable to fetch reference #0 9998..38548
[E::cram_next_slice] Failure to decode slice

however if I use the samtools -T option it works fine. 
The cram files have been moved from where they were originally created so the path in UR field of the cram header does not exist. However the ref files are the same.

If you had any idea how to remedy this I would be very grateful. 
Can the cram header be updated for the new ref path?

many thanks

**Comment by jkbonfield** [comment]
You shouldn't need to update the header.  It contains the md5 checksums (SQ M5 tag) which is sufficient to find the reference if you've set up REF_PATH and ran seq_cache_populate.  I suspect you've set it as a local variable but not exported, as the error message appears to be indicating it is still attempting to fetch from the EBI.

The REF_PATH section in the samtools.1 man page gives instructions on the format that the environment variable should take.  An example usage, using data in the htslib test directory:

```
# Obtain a local copy of our reference and produce the ref cache
$ cd /tmp
$ cp ~/htslib/test/ce.fa .
$ cp ~/htslib/test/ce.fa.fai .
$ ~/samtools/misc/seq_cache_populate.pl -root=ref ce.fa
Reading ce.fa ...
ref/8e/de/36131e0dbf3417807e48f77f3ebd CHROMOSOME_I
ref/8e/79/93f7a93158587ee897d7287948ec CHROMOSOME_II
ref/3a/dc/b065e1cf74fafdbba1e8c352b323 CHROMOSOME_III
ref/25/1a/f66a69ee589c9f3757340ec2de6f CHROMOSOME_IV
ref/cf/20/0a65fb754836dcc56b24b3170ee8 CHROMOSOME_V
ref/6f/93/68fd2192c89c613718399d2d31fc CHROMOSOME_X
ref/cd/05/857ece6411f40257a565ccfe15bb CHROMOSOME_MtDNA

# blank output from echo statements; variables not set.
$ echo $REF_PATH
$ echo $REF_CACHE

# Convert our file from SAM to CRAM using local reference copy, and test we can decode it.
# Note this is fetching ce.fa by spotting the UR line in the CRAM header.
$ samtools view -T ce.fa ~/htslib/test/ce#5.sam -o tmp.cram
$ samtools view tmp.cram|wc -l
6

# Now remove our local copy of reference file and observe the failures as UR file doesn't exist.
$ rm ce.fa ce.fa.fai
$ samtools view tmp.cram|wc -l
[E::cram_get_ref] Failed to populate reference for id 0
[E::cram_decode_slice] Unable to fetch reference #0 2..100101

[E::cram_next_slice] Failure to decode slice
[main_samview] truncated file.
0

# Now add back our reference via the REF_PATH.
$ export REF_PATH=`pwd`/ref/%2s/%2s/%s
$ samtools view tmp.cram|wc -l
6
```

If you don't have REF_PATH and REF_CACHE set it'll try to go to the EBI, which in this case wouldn't find it either as these are our own test references.  In your case this produced an error message "Protocol not supported" because you built htslib without using lib-curl.  Please rebuild using the "./configure;make" script instead of just typing "make" as this then enables curl.

In that case, if your reference is at the EBI (which it is) then samtools would fetch it remotely and use that instead.  By default it'll then also store a local copy of that reference in ~/.cache/hts-ref/ directory (assuming default environment).

**Comment by Sames-Jtudd** [comment]
Amazballs, it works 
thanks very much for getting back to me so quickly

**Comment by bw2** [comment]
For anyone else that runs into this issue, the following worked for me:

```
wget https://storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta
wget https://storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.fai 
wget https://storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.ref_cache.tar.gz

tar xzf Homo_sapiens_assembly38.ref_cache.tar.gz
export REF_PATH="$(pwd)/ref/cache/%2s/%2s/%s:http://www.ebi.ac.uk/ena/cram/md5/%s"
export REF_CACHE="$(pwd)/ref/cache/%2s/%2s/%s"

...

{command that was generating the '[W::find_file_url] Failed to open reference..' error}
```
