### ISSUE TITLE
htslib fails to build on mips/mipsel

### ISSUE THREAD

**Issue by azlicic** [samtools/htslib#98]
Hello,
Your package htslib fails to build on Debian for mips/mipsel architectures.

I have already reported a bug on Debian bug tracking system at:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=749367,
with proposed patches attached.

Build logs for mips and mipsel are available at
https://buildd.debian.org/status/fetch.php?pkg=htslib&arch=mips&ver=0.2.0~rc3-1&stamp=1386050228
and
https://buildd.debian.org/status/fetch.php?pkg=htslib&arch=mipsel&ver=0.2.0~rc3-1&stamp=1386204701

Current version of htslib on Debian is 0.2.0~rc3-1.

I am currently adapting the patch to fit the latest htslib version.

I will send you a pull request as soon as I'm done.

Best Regards
Aleksandar Zlicic

**Comment by xnox** [comment]
Hi, these failures affect armhf, powerpc and s390x builds too. W.r.t. build and testing, all debian developers have access to such machines and can run occasional builds for you. If you want access yourself you can request access to debian porter boxes, after agreeing to the Debian Machine Usage Policy (?! can't remember exact name) and somebody sponsoring (a DD recommending you) your access. Can we please resolve this? At the moment there is a chain of dependencies that fails to build due to this. blasr in debian stopped using bundled libs, and thus now depends on pbseqlib and htslib to be available on more arches. Specifically armhf and big-endian systems (powerpc, s390x). What's outstanding to resolve with this merge proposal?

**Comment by daviesrob** [comment]
There are some forks that should work on big-endian platforms in:

https://github.com/daviesrob/samtools/tree/SPARC
https://github.com/daviesrob/htslib/tree/SPARC

but I'm afraid they're now well out of date.  Unfortunately more pressing 
things got in the way so it's been ignored for a while and would now need 
a bit of rework to get it merged.

How much demand is there for this?  As it's not something we need 
ourselves it gets a low priority at the moment.



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by mr-c** [comment]
`mipsel` and `mips64el` have been successfully building for many years on Debian, so this issue can be closed:

https://buildd.debian.org/status/logs.php?pkg=htslib&arch=mips64el
https://buildd.debian.org/status/logs.php?pkg=htslib&arch=mipsel

**Comment by xnox** [comment]
Cool, btw, there is now arm64 & s390x support in travis, thus if you use travis it is trivial to enable them.
